force-app/main/default/objects/FifthSetConfirm__c/FifthSetConfirm__c.object-meta.xml
<CustomObject>
    <label>5点確定</label>
    <nameField>
        <displayFormat>FS-{000000000}</displayFormat>
        <label>5点確定名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FifthSetConfirm__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipName>FifthSetConfirmNewMatterRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matching__c/Matching__c.object-meta.xml
<CustomObject>
    <label>マッチング</label>
    <nameField>
        <label>マッチング名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Matching__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>マッチング</relationshipLabel>
    <relationshipName>MatchingNewMatterRelation1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matching__c/fields/PaperType__c.field-meta.xml
<CustomField>
    <fullName>PaperType__c</fullName>
    <label>帳票種類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>重説</fullName>
            </value>
            <value>
                <fullName>契約書</fullName>
            </value>
            <value>
                <fullName>請求書</fullName>
            </value>
            <value>
                <fullName>図面</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matching__c/recordTypes/Bill.recordType-meta.xml
<RecordType>
    <fullName>Bill</fullName>
    <active>true</active>
    <label>請求書</label>
</RecordType>

force-app/main/default/objects/Matching__c/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <label>契約書</label>
</RecordType>

force-app/main/default/objects/Matching__c/recordTypes/Drawing.recordType-meta.xml
<RecordType>
    <fullName>Drawing</fullName>
    <active>true</active>
    <label>図面</label>
</RecordType>

force-app/main/default/objects/MatchingComparisonResult__c/MatchingComparisonResult__c.object-meta.xml
<CustomObject>
    <label>マッチング比較結果</label>
    <nameField>
        <label>マッチング比較結果名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptBill__c.field-meta.xml
<CustomField>
    <fullName>IsExceptBill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>請求書不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptContract__c.field-meta.xml
<CustomField>
    <fullName>IsExceptContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>契約書不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptDrawing__c.field-meta.xml
<CustomField>
    <fullName>IsExceptDrawing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>図面不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptImportantExplanation__c.field-meta.xml
<CustomField>
    <fullName>IsExceptImportantExplanation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>重説不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipName>MatchingComparisonResultNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/MatchingComparisonTarget__mdt.object-meta.xml
<CustomObject>
    <label>マッチング比較対象</label>
</CustomObject>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsBill__c.field-meta.xml
<CustomField>
    <fullName>IsBill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>請求書フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsContract__c.field-meta.xml
<CustomField>
    <fullName>IsContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>契約書フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsDrawing__c.field-meta.xml
<CustomField>
    <fullName>IsDrawing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>図面フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsImportantExplanation__c.field-meta.xml
<CustomField>
    <fullName>IsImportantExplanation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>重説フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/ReferenceName__c.field-meta.xml
<CustomField>
    <fullName>ReferenceName__c</fullName>
    <label>参照名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/MatchingSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>マッチング</label>
</CustomObject>

force-app/main/default/objects/MatchingSetting__c/fields/FieldSuffix__c.field-meta.xml
<CustomField>
    <fullName>FieldSuffix__c</fullName>
    <label>項目接尾辞</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/PaperTypeBill__c.field-meta.xml
<CustomField>
    <fullName>PaperTypeBill__c</fullName>
    <label>帳票種類‗請求書</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/PaperTypeContract__c.field-meta.xml
<CustomField>
    <fullName>PaperTypeContract__c</fullName>
    <label>帳票種類‗契約書</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/PaperTypeDrawing__c.field-meta.xml
<CustomField>
    <fullName>PaperTypeDrawing__c</fullName>
    <label>帳票種類‗図面</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/PaperTypeImportantExplanation__c.field-meta.xml
<CustomField>
    <fullName>PaperTypeImportantExplanation__c</fullName>
    <label>帳票種類‗重説</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/ResultFieldSuffix__c.field-meta.xml
<CustomField>
    <fullName>ResultFieldSuffix__c</fullName>
    <label>結果項目接尾辞</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/SendTaskAutoProcessCompleteMessage__c.field-meta.xml
<CustomField>
    <fullName>SendTaskAutoProcessCompleteMessage__c</fullName>
    <label>TODO自動マッチング完了コメント</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/SendTaskAutoProcessCompleteSubject__c.field-meta.xml
<CustomField>
    <fullName>SendTaskAutoProcessCompleteSubject__c</fullName>
    <label>TODO自動マッチング完了件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/SendTaskAutoProcessErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>SendTaskAutoProcessErrorMessage__c</fullName>
    <label>TODO自動マッチングエラーコメント</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/SendTaskAutoProcessErrorSubject__c.field-meta.xml
<CustomField>
    <fullName>SendTaskAutoProcessErrorSubject__c</fullName>
    <label>TODO自動マッチングエラー件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/TaskErrorPriority__c.field-meta.xml
<CustomField>
    <fullName>TaskErrorPriority__c</fullName>
    <label>TODOエラー通知_優先度</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/TaskErrorStatus__c.field-meta.xml
<CustomField>
    <fullName>TaskErrorStatus__c</fullName>
    <label>TODOエラー通知_ステータス</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/TaskErrorSubtype__c.field-meta.xml
<CustomField>
    <fullName>TaskErrorSubtype__c</fullName>
    <label>TODOエラー通知_サブ種別</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/TaskPriority__c.field-meta.xml
<CustomField>
    <fullName>TaskPriority__c</fullName>
    <label>TODO通知_優先度</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/TaskStatus__c.field-meta.xml
<CustomField>
    <fullName>TaskStatus__c</fullName>
    <label>TODO通知_ステータス</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/TaskSubtype__c.field-meta.xml
<CustomField>
    <fullName>TaskSubtype__c</fullName>
    <label>TODO通知_サブ種別</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingSetting__c/fields/TypeFieldSuffix__c.field-meta.xml
<CustomField>
    <fullName>TypeFieldSuffix__c</fullName>
    <label>区分項目接尾辞</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/FifthSetConfirm__c.field-meta.xml
<CustomField>
    <fullName>FifthSetConfirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約条件</label>
    <referenceTo>FifthSetConfirm__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>FifthSetConfirmNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MatchingTriggerHandler.cls
/**
 * @description トリガ：マッチング
 * 
 * @author t-ooshiro-bp
 * @date 2022/02/15
 */
public with sharing class MatchingTriggerHandler {
    /**
     * 
     * @param news 
     */
    public void matchingComparison(List<Matching__c> news) {

        // カスタム設定
        MatchingSetting__c matchingSetting = MatchingSetting__c.getOrgDefaults();

        // 処理対象の新規IDを抽出
        Set<Id> newMatterIds = new Set<Id>();
        for (Matching__c matching : news) {
            newMatterIds.add(matching.NewMatter__c);
        }

        // カスタムメタデータ：マッチング比較対象 取得
        List<MatchingComparisonTarget__mdt> matchingTargets =
            MatchingComparisonModel.getMatchingComparisonTargetMdt();

        // マッチング、5点確定、マッチング比較結果の取得項目リストを生成
        List<String> matchingFieldNames = new List<String>();
        List<String> matchingResultFieldNames = new List<String>();
        for (MatchingComparisonTarget__mdt matchingTarget : matchingTargets) {
            // 比較対象の書類件数を算出
            Integer matchingTargetCnt = 0;
            if (matchingTarget.IsImportantExplanation__c) {
                matchingTargetCnt++;
            }
            if (matchingTarget.IsContract__c) {
                matchingTargetCnt++;
            }
            if (matchingTarget.IsBill__c) {
                matchingTargetCnt++;
            }
            if (matchingTarget.IsDrawing__c) {
                matchingTargetCnt++;
            }

            if (matchingTargetCnt > 0) {
                matchingFieldNames.add(MatchingComparisonUtils.concat(matchingTarget.ReferenceName__c, matchingSetting.FieldSuffix__c));
                // 比較対象書類が2種類以上の場合、マッチング比較結果の取得フィールドに追加
                if (matchingTargetCnt > 1) {
                    matchingResultFieldNames.add(MatchingComparisonUtils.concat(matchingTarget.ReferenceName__c, matchingSetting.TypeFieldSuffix__c));
                    matchingResultFieldNames.add(MatchingComparisonUtils.concat(matchingTarget.ReferenceName__c, matchingSetting.ResultFieldSuffix__c));
                }
            }
        }

        // 新規 取得
        List<NewMatter__c> newMatters =
            MatchingComparisonModel.getNewMatters(newMatterIds);

        // マッチング 取得
        List<Matching__c> matchings =
            MatchingComparisonModel.getMatchingsByNewMatterIds(newMatterIds, matchingFieldNames);

        // 取得したマッチングを新規ID毎にMap化
        Map<Id, MatchingTargetData> matchingMap = new Map<Id, MatchingTargetData>();
        for (Matching__c matching : matchings) {
            MatchingTargetData targetData;
            if (matchingMap.containsKey(matching.NewMatter__c)) {
                targetData = (MatchingTargetData)matchingMap.get(matching.NewMatter__c);
            } else {
                targetData = new MatchingTargetData();
            }

            if (matchingSetting.PaperTypeImportantExplanation__c.equals(matching.PaperType__c)) {
                targetData.importantExplanation = matching;
            } else if (matchingSetting.PaperTypeContract__c.equals(matching.PaperType__c)) {
                targetData.contract = matching;
            } else if (matchingSetting.PaperTypeBill__c.equals(matching.PaperType__c)) {
                targetData.bill = matching;
            } else if (matchingSetting.PaperTypeDrawing__c.equals(matching.PaperType__c)) {
                targetData.drawing = matching;
            }
            matchingMap.put(matching.NewMatter__c, targetData);
        }

        // マッチング比較結果 取得
        List<MatchingComparisonResult__c> matchingComparisonResults =
            MatchingComparisonModel.getMatchingComparisonResultsByNewMatterIds(newMatterIds, matchingResultFieldNames);

        // 取得したマッチング比較結果を新規ID毎にMap化
        Map<Id, MatchingComparisonResult__c> matchingResultMap = new Map<Id, MatchingComparisonResult__c>();
        for (MatchingComparisonResult__c matchingComparisonResult : matchingComparisonResults) {
            matchingResultMap.put(matchingComparisonResult.NewMatter__c, matchingComparisonResult);
        }

        // 5点確定 取得
        List<FifthSetConfirm__c> fifthSetConfirms =
            MatchingComparisonModel.getFifthSetConfirmsByNewMatterIds(newMatterIds, matchingFieldNames);

        // 取得した5点確定を新規ID毎にMap化
        Map<Id, FifthSetConfirm__c> fifthSetMap = new Map<Id, FifthSetConfirm__c>();
        for (FifthSetConfirm__c fifthSetConfirm : fifthSetConfirms) {
            fifthSetMap.put(fifthSetConfirm.NewMatter__c, fifthSetConfirm);
        }

        // 登録／更新用マッチング比較結果リスト
        List<MatchingComparisonResult__c> upsertMatchingComparisonResults = new List<MatchingComparisonResult__c>();
        // 登録／更新用5点確定リスト
        List<FifthSetConfirm__c> upsertFifthSetConfirms = new List<FifthSetConfirm__c>();
        // 通知用Taskリスト
        List<Task> insertTasks = new List<Task>();

        for (NewMatter__c newMatter : newMatters) {
            // 自動マッチング実施可否判定
            if (this.isContinueMatchingComparison(matchingResultMap.get(newMatter.Id), (MatchingTargetData)matchingMap.get(newMatter.Id))) continue;

            MatchingResultData matchingResultData =
                this.executeAutoMatchingComparison(
                    newMatter,
                    matchingMap.get(newMatter.Id),
                    matchingResultMap.get(newMatter.Id),
                    fifthSetMap.get(newMatter.Id),
                    matchingTargets,
                    matchingSetting
                );

            // 登録／更新用マッチング比較結果リストに追加
            upsertMatchingComparisonResults.add(matchingResultData.matchingComparisonResult);
            // 登録／更新用5点確定リストに追加
            upsertFifthSetConfirms.add(matchingResultData.fifthSetConfirm);
            // 通知用Taskリストに追加
            insertTasks.add(
                new Task(
                    WhatId = newMatter.Id, // 関連先
                    TaskSubtype = matchingSetting.TaskSubtype__c , // ToDoのサブ種別
                    Status = matchingSetting.TaskStatus__c, // 状況
                    Priority = matchingSetting.TaskPriority__c, // 優先度
                    Subject = matchingSetting.SendTaskAutoProcessCompleteSubject__c, // 件名
                    Description = matchingSetting.SendTaskAutoProcessCompleteMessage__c // コメント
                )
            );
        }

        try {
            // マッチング比較結果 登録／更新
            MatchingComparisonModel.upsertMatchingComparisonResult(upsertMatchingComparisonResults);
            // 5点確定 登録／更新
            MatchingComparisonModel.upsertFifthSetConfirm(upsertFifthSetConfirms);
            // ToDo 登録
            MatchingComparisonModel.insertTask(insertTasks);
        } catch (Exception e) {
            // 例外が発生した場合、新規ユーザへTODOを通知

            // エラー通知用Taskリスト
            List<Task> insertErrorTasks = new List<Task>();
            for (Id newMatterId : newMatterIds) {
                insertErrorTasks.add(
                    new Task(
                        WhatId = newMatterId, // 関連先
                        TaskSubtype = matchingSetting.TaskErrorSubtype__c, // ToDoのサブ種別
                        Status = matchingSetting.TaskErrorStatus__c, // 状況
                        Priority = matchingSetting.TaskErrorPriority__c, // 優先度
                        Subject = matchingSetting.SendTaskAutoProcessErrorSubject__c, // 件名
                        Description = matchingSetting.SendTaskAutoProcessErrorMessage__c // コメント
                    )
                );
            }
            // ToDo 登録
            MatchingComparisonModel.insertTask(insertErrorTasks);
        }
    }

    /**
     * 
     * @param newMatter 
     * @param matchingTargetData 
     * @param matchingComparisonResult 
     * @param fifthSetConfirm 
     * @param matchingTargets 
     * @param matchingSetting 
     * @return  `MatchingResultData`
     */
    private MatchingResultData executeAutoMatchingComparison(
        NewMatter__c newMatter,
        MatchingTargetData matchingTargetData,
        MatchingComparisonResult__c matchingComparisonResult,
        FifthSetConfirm__c fifthSetConfirm,
        List<MatchingComparisonTarget__mdt> matchingTargets,
        MatchingSetting__c matchingSetting
    ){
        // 重説不要フラグ
        Boolean isExceptImportantExplanation = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptImportantExplanation__c;
        // 契約書不要フラグ
        Boolean isExceptContract = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptContract__c;
        // 請求書不要フラグ
        Boolean isExceptBill = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptBill__c;
        // 図面不要フラグ
        Boolean isExceptDrawing = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptDrawing__c;

        // マッチング比較処理呼び出し
        return MatchingComparisonUtils.executeMatchingComparison(
            newMatter, // 新規
            matchingTargetData, // マッチング
            matchingComparisonResult, // マッチング比較結果
            fifthSetConfirm, // 5点確定
            matchingTargets, // カスタムメタデータ
            isExceptImportantExplanation, // 重説不要フラグ
            isExceptContract, // 契約書不要フラグ
            isExceptBill, // 請求書不要フラグ
            isExceptDrawing // 図面不要フラグ
        );
    }

    /**
     * 
     * @param newMatter 
     * @param matchingTargetData 
     * @param matchingSetting 
     * @return  `Boolean`
     */
    private Boolean isContinueMatchingComparison(MatchingComparisonResult__c matchingComparisonResult, MatchingTargetData matchingTargetData) {
        // 重説不要フラグ
        Boolean isExceptImportantExplanation = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptImportantExplanation__c;
        if (!isExceptImportantExplanation && matchingTargetData.importantExplanation == null) {
            return true;
        }

        // 契約書不要フラグ
        Boolean isExceptContract = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptContract__c;
        if (!isExceptContract && matchingTargetData.contract == null) {
            return true;
        }

        // 請求書不要フラグ
        Boolean isExceptBill = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptBill__c;
        if (!isExceptBill && matchingTargetData.bill == null) {
            return true;
        }

        // 図面不要フラグ
        Boolean isExceptDrawing = matchingComparisonResult == null ? false : matchingComparisonResult.IsExceptDrawing__c;
        if (!isExceptDrawing && matchingTargetData.drawing == null) {
            return true;
        }
        return false;
    }
}