force-app/main/default/objects/FbData__c/FbData__c.object-meta.xml
<CustomObject>
    <label>FBデータ</label>
    <nameField>
        <displayFormat>FB-{000000000}</displayFormat>
        <label>FBデータ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/CreateFbDataNotificationBody__c.field-meta.xml
<CustomField>
    <fullName>CreateFbDataNotificationBody__c</fullName>
    <label>FBデータ作成完了通知本文</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyatakusanSetting__c/fields/CreateFbDataNotificationTitle__c.field-meta.xml
<CustomField>
    <fullName>CreateFbDataNotificationTitle__c</fullName>
    <label>FBデータ作成完了通知タイトル</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateFbDataCustomNotification.cls
/**
 * @description        : FBデータ作成カスタム通知
 * @author             : h-nakata
**/
public class CreateFbDataCustomNotification {
    /**
    * @description カスタム通知送信
    * @author h-nakata
    * @param Set<String> recipientsIds 通知受信ユーザID
    * @return void
    **/
    public static void notifyUsers(Set<String> recipientsIds) {
        //カスタム通知種別取得
        CustomNotificationType notificationType = 
            [SELECT Id
             FROM CustomNotificationType 
             WHERE DeveloperName = 'CreateFbDataCompleted'];
        
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        //しゃたくさん設定取得
        SyatakusanSetting__c syatakusanSetting = SyatakusanSetting__c.getOrgDefaults();
        //通知タイトル
        notification.setTitle(syatakusanSetting.CreateFbDataNotificationTitle__c);
        //通知本文
        notification.setBody(syatakusanSetting.CreateFbDataNotificationBody__c);
        //カスタム通知種別
        notification.setNotificationTypeId(notificationType.Id);
        //遷移先をFBデータリストビューに設定
        String pageRef = '{"type":"standard__objectPage", "attributes":{"objectApiName":"FbData__c", "actionName":"list"}, "state":{"filterName":"Recent"}}';
        notification.setTargetPageRef(pageRef);
        
        //カスタム通知送信
        try {
            notification.send(recipientsIds);
        } catch (Exception e) {
            System.debug('Problem sending notification: ' + e.getMessage());
        }
    }
}