force-app/main/default/objects/SystemControl_ApexBatch__mdt/SystemControl_ApexBatch__mdt.object-meta.xml
<CustomObject>
    <label>Apexバッチ情報</label>
</CustomObject>

force-app/main/default/objects/SystemControl_ApexBatch__mdt/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <label>バッチサイズ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApexBatchUtils.cls
/**
 * @File Name          : ApexBatchUtils.cls
 * @Description        : APEXバッチ処理のユーティリティークラス
**/
public  class ApexBatchUtils {
    /**
     * デフォルトバッチサイズ取得
     */
    public static Integer getDefaultBatchSize() {
        // カスタムメタデータ型「Apexバッチ情報.[パラメータ]Apexバッチクラス名」取得
        SystemControl_ApexBatch__mdt defaultBatchSize = [SELECT BatchSize__c FROM SystemControl_ApexBatch__mdt WHERE DeveloperName='Default' LIMIT 1];
        return defaultBatchSize.BatchSize__c.intValue();
    }

    /**
     * バッチクラス指定バッチサイズ取得
     */
    public static Integer getBatchSize(String apexBatchClassName) {
        // カスタムメタデータ型「Apexバッチ情報.[パラメータ]Apexバッチクラス名」取得
        SystemControl_ApexBatch__mdt[] apexBatchSize = [SELECT BatchSize__c FROM SystemControl_ApexBatch__mdt WHERE DeveloperName=:apexBatchClassName LIMIT 1];
        if (apexBatchSize.isEmpty()) {
            return getDefaultBatchSize();
        }
        return apexBatchSize[0].BatchSize__c.intValue();
    }
}