force-app/main/default/objects/Cancel__c/Cancel__c.object-meta.xml
<CustomObject>
    <label>解約申入</label>
    <nameField>
        <displayFormat>CA-{000000000}</displayFormat>
        <label>解約申入No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancel__c/fields/CancelCalculate__c.field-meta.xml
<CustomField>
    <fullName>CancelCalculate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約精算</label>
    <referenceTo>CancelCalculate__c</referenceTo>
    <relationshipName>ApplicationCancelCalculate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cancel__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>解約申入</relationshipLabel>
    <relationshipName>NewMatterCancel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CancelCalculate__c/CancelCalculate__c.object-meta.xml
<CustomObject>
    <label>解約精算</label>
    <nameField>
        <displayFormat>CC-{000000000}</displayFormat>
        <label>解約精算名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/CancelCalculate__c.field-meta.xml
<CustomField>
    <fullName>CancelCalculate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約精算</label>
    <referenceTo>CancelCalculate__c</referenceTo>
    <relationshipLabel>ケース</relationshipLabel>
    <relationshipName>CancelCalculateCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>入替</label>
    <referenceTo>Change__c</referenceTo>
    <relationshipLabel>ケース</relationshipLabel>
    <relationshipName>tqMt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change__c/Change__c.object-meta.xml
<CustomObject>
    <label>入替</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>入替名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ConditionChange__c/ConditionChange__c.object-meta.xml
<CustomObject>
    <label>条件変更</label>
    <nameField>
        <displayFormat>CC-{000000000}</displayFormat>
        <label>条件変更名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Cancel__c.field-meta.xml
<CustomField>
    <fullName>Cancel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約</label>
    <referenceTo>Cancel__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>NewMatterCancel_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Renewal__c/Renewal__c.object-meta.xml
<CustomObject>
    <label>更新</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>更新NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Renewal__c/fields/Cancel__c.field-meta.xml
<CustomField>
    <fullName>Cancel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約申入</label>
    <referenceTo>Cancel__c</referenceTo>
    <relationshipLabel>更新</relationshipLabel>
    <relationshipName>Concelinjp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/classes/PhaseGateTriggerTest.cls
/**
 * @Description: Testing for class PhaseGate.
 * 
 * @author t-ooshiro-bp
 * @date 2022/07/26
 */
@isTest
private class PhaseGateTriggerTest {
    /*
    @isTest static void newMatterTest(){
        //カスタム設定を作成
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        //SyatakusanSetting__c customSetting = createCustomSetting();

        Test.startTest();
        try{
            List<NewMatter__c> newMatterList = PhaseGateCreateNewMatterTestData.createData();//新規テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void cancelTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Cancel__c> cancelList = PhaseGateCreateCancelTestData.createData();//解約テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void renewalTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Renewal__c> renewalList = PhaseGateCreateRenewalTestData.createData();//更新テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }
    @isTest static void conditionChangeTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<ConditionChange__c> conditionChangeList = PhaseGateCreateConditionChangeTestData.createData();//条件変更テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void changeTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Change__c> changeList = PhaseGateCreateChangeTestData.createData();//入替テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void caseTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Case> caseList = PhaseGateCreateCaseTestData.createData();//ケーステストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void cancelCalculateTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<CancelCalculate__c> cancelCalculateList = PhaseGateCreateCancelCalculateTestData.createData();//解約精算テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }
    */
}