force-app/main/default/objects/Cancel__c/Cancel__c.object-meta.xml
<CustomObject>
    <label>解約申入</label>
    <nameField>
        <displayFormat>CA-{000000000}</displayFormat>
        <label>解約申入No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancel__c/fields/CancelCalculate__c.field-meta.xml
<CustomField>
    <fullName>CancelCalculate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約精算</label>
    <referenceTo>CancelCalculate__c</referenceTo>
    <relationshipName>ApplicationCancelCalculate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cancel__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>解約申入</relationshipLabel>
    <relationshipName>NewMatterCancel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cancel__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>申請待ち</fullName>
            </value>
            <value>
                <fullName>解約保留中</fullName>
            </value>
            <value>
                <fullName>条件確認中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CancelCalculate__c/CancelCalculate__c.object-meta.xml
<CustomObject>
    <label>解約精算</label>
    <nameField>
        <displayFormat>CC-{000000000}</displayFormat>
        <label>解約精算名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CancelCalculate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>入居中</fullName>
            </value>
            <value>
                <fullName>見積り準備中</fullName>
            </value>
            <value>
                <fullName>内容確認中</fullName>
            </value>
            <value>
                <fullName>決裁申請中</fullName>
            </value>
            <value>
                <fullName>対応中（返金/支払い)</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CancelCalculate__c.field-meta.xml
<CustomField>
    <fullName>CancelCalculate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約精算</label>
    <referenceTo>CancelCalculate__c</referenceTo>
    <relationshipLabel>ケース</relationshipLabel>
    <relationshipName>CancelCalculateCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>入替</label>
    <referenceTo>Change__c</referenceTo>
    <relationshipLabel>ケース</relationshipLabel>
    <relationshipName>tqMt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change__c/Change__c.object-meta.xml
<CustomObject>
    <label>入替</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>入替名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Change__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>申請待ち</fullName>
            </value>
            <value>
                <fullName>申請確認中</fullName>
            </value>
            <value>
                <fullName>条件確認中</fullName>
            </value>
            <value>
                <fullName>見積り待ち</fullName>
            </value>
            <value>
                <fullName>見積り確認中</fullName>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>対応中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>再査中</fullName>
                <isActive>false</isActive>
                <label>再査中</label>
            </value>
            <value>
                <fullName>決裁申請中</fullName>
                <isActive>false</isActive>
                <label>決裁申請中</label>
            </value>
            <value>
                <fullName>申請受付</fullName>
                <isActive>false</isActive>
                <label>申請受付</label>
            </value>
            <value>
                <fullName>見積り内容確認中</fullName>
                <isActive>false</isActive>
                <label>見積り内容確認中</label>
            </value>
            <value>
                <fullName>請求書待ち</fullName>
                <isActive>false</isActive>
                <label>請求書待ち</label>
            </value>
            <value>
                <fullName>退去手続き</fullName>
                <isActive>false</isActive>
                <label>退去手続き</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConditionChange__c/ConditionChange__c.object-meta.xml
<CustomObject>
    <label>条件変更</label>
    <nameField>
        <displayFormat>CC-{000000000}</displayFormat>
        <label>条件変更名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ConditionChange__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>受付中</fullName>
            </value>
            <value>
                <fullName>内容確認中</fullName>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>対応中(精算・締結等）</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>作業中</fullName>
                <isActive>false</isActive>
                <label>作業中</label>
            </value>
            <value>
                <fullName>再査中</fullName>
                <isActive>false</isActive>
                <label>再査中</label>
            </value>
            <value>
                <fullName>契約書原本保管</fullName>
                <isActive>false</isActive>
                <label>契約書原本保管</label>
            </value>
            <value>
                <fullName>手配/依頼</fullName>
                <isActive>false</isActive>
                <label>手配/依頼</label>
            </value>
            <value>
                <fullName>新規</fullName>
                <isActive>false</isActive>
                <label>新規</label>
            </value>
            <value>
                <fullName>書類締結</fullName>
                <isActive>false</isActive>
                <label>書類締結</label>
            </value>
            <value>
                <fullName>条件確認/調整</fullName>
                <isActive>false</isActive>
                <label>条件確認/調整</label>
            </value>
            <value>
                <fullName>決裁申請/承認</fullName>
                <isActive>false</isActive>
                <label>決裁申請/承認</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Cancel__c.field-meta.xml
<CustomField>
    <fullName>Cancel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約</label>
    <referenceTo>Cancel__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>NewMatterCancel_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>申請待ち</fullName>
                <default>true</default>
                <label>申請待ち</label>
            </value>
            <value>
                <fullName>申請確認中</fullName>
            </value>
            <value>
                <fullName>選定中</fullName>
            </value>
            <value>
                <fullName>書類準備中</fullName>
            </value>
            <value>
                <fullName>契約条件確認中</fullName>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>締結中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>決裁申請中</fullName>
            </value>
            <value>
                <fullName>作業中</fullName>
                <isActive>false</isActive>
                <label>作業中</label>
            </value>
            <value>
                <fullName>再査中</fullName>
                <isActive>false</isActive>
                <label>再査中</label>
            </value>
            <value>
                <fullName>契約内容確認中</fullName>
                <isActive>false</isActive>
                <label>契約内容確認中</label>
            </value>
            <value>
                <fullName>契約書原本保管</fullName>
                <isActive>false</isActive>
                <label>契約書原本保管</label>
            </value>
            <value>
                <fullName>承認連絡準備中</fullName>
                <isActive>false</isActive>
                <label>承認連絡準備中</label>
            </value>
            <value>
                <fullName>新規</fullName>
                <isActive>false</isActive>
                <label>新規</label>
            </value>
            <value>
                <fullName>書類到着待ち</fullName>
                <isActive>false</isActive>
                <label>書類到着待ち</label>
            </value>
            <value>
                <fullName>書類締結中</fullName>
                <isActive>false</isActive>
                <label>書類締結中</label>
            </value>
            <value>
                <fullName>条件確認中</fullName>
                <isActive>false</isActive>
                <label>条件確認中</label>
            </value>
            <value>
                <fullName>物件決定待ち</fullName>
                <isActive>false</isActive>
                <label>物件決定待ち</label>
            </value>
            <value>
                <fullName>申請受付</fullName>
                <isActive>false</isActive>
                <label>申請受付</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PhaseGate__c/PhaseGate__c.object-meta.xml
<CustomObject>
    <label>フェーズゲート</label>
    <nameField>
        <displayFormat>PhaseGate-{0000}</displayFormat>
        <label>フェーズゲート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PhaseGate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Renewal__c/Renewal__c.object-meta.xml
<CustomObject>
    <label>更新</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>更新NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Renewal__c/fields/Cancel__c.field-meta.xml
<CustomField>
    <fullName>Cancel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>解約申入</label>
    <referenceTo>Cancel__c</referenceTo>
    <relationshipLabel>更新</relationshipLabel>
    <relationshipName>Concelinjp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Renewal__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>ステータス</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>更新時期待ち</fullName>
                <default>true</default>
                <label>更新時期待ち</label>
            </value>
            <value>
                <fullName>条件確認中</fullName>
            </value>
            <value>
                <fullName>内容調整中</fullName>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>対応中（支払・締結等）</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>作業中</fullName>
                <isActive>false</isActive>
                <label>作業中</label>
            </value>
            <value>
                <fullName>経理手配待ち</fullName>
                <isActive>false</isActive>
                <label>経理手配待ち</label>
            </value>
            <value>
                <fullName>請求書待ち</fullName>
                <isActive>false</isActive>
                <label>請求書待ち</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PhaseGateHandler.cls
/**
 * @description 
 * @param accountId 取引先ID
 * @return `List<SObject>`
 */
public class PhaseGateHandler{
    
    public static boolean firstRun = true;//二重起動防止フラグ

    public static void triggerHandler(List<SObject> triggerRecord){
        PhaseGate phaseGate = new PhaseGate();
        PhaseGateModel model = new PhaseGateModel();

        phaseGate.setRecord(triggerRecord[0]);
        //オブジェクト名の取得
        String objectName = triggerRecord.getSObjectType().getDescribe().getName();
        model.setObjectName(objectName);

        //フェーズ項目名の設定
        String stageFieldName = '';
        switch on objectName {
            when  
            'NewMatter__c',
            'Cancel__c',
            'CancelCalculate__c',
            'Change__c',
            'Renewal__c',
            'ConditionChange__c'{
                stageFieldName = 'Stage__c';
            }
            when 'Case'{
                stageFieldName = 'Status';
            }
            when else {
                
            }
        }

        //レコード情報の取得
        String accountId = PhaseGate.getFieldValue('Account__c');//取引先ID
        String stage =  PhaseGate.getFieldValue(stageFieldName);//フェーズ
        model.setAccountId(accountId);

        //レコードのステップ数の取得
        integer stepNum = model.getStepNum(stage);
        System.debug(stepNum);
        if(stepNum != null){
            model.setStepNum(stepNum);

            //必須項目の取得
            boolean isNoneMediationRequest = false;
            if(phaseGate.isNewMatter(objectName))isNoneMediationRequest = true;

            Map<String,List<PhaseGate__c>> phaseGateMap = model.getPhaseGate(isNoneMediationRequest , stepNum);
            
            List<PhaseGate__c> phaseGateList = phaseGateMap.get('phaseGate');
            List<PhaseGate__c> aftterPhaseGateList = phaseGateMap.get('aftterPhaseGate');
            System.debug('phaseGateList:' + phaseGateList);
            System.debug('aftterPhaseGateList:' + aftterPhaseGateList);

            //レコードの必須項目が変更されていないか確認(変更されていたらエラーメッセージリストに追加)
            phaseGate.checkRequiredFields(triggerRecord[0] , phaseGateList);

            //後フェーズでの必須項目が入力されていないか確認
            phaseGate.checkAftterPhaseRequiredFields(triggerRecord[0] , aftterPhaseGateList);
        }

    }

}