force-app/main/default/objects/RemoteAccessSetting__c/RemoteAccessSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>在宅アクセス権限制御</label>
</CustomObject>

force-app/main/default/objects/RemoteAccessSetting__c/fields/ApexErrorEmailTemplate__c.field-meta.xml
<CustomField>
    <fullName>ApexErrorEmailTemplate__c</fullName>
    <label>APEX異常時通知テンプレートID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/ApexErrorEmailtoAddress__c.field-meta.xml
<CustomField>
    <fullName>ApexErrorEmailtoAddress__c</fullName>
    <label>APEX異常時通知メール宛先</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/GroupTypeQueue__c.field-meta.xml
<CustomField>
    <fullName>GroupTypeQueue__c</fullName>
    <label>グループタイプ_キュー</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/OfficeGroupId__c.field-meta.xml
<CustomField>
    <fullName>OfficeGroupId__c</fullName>
    <label>出社グループID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/OfficeGroupMemberResetBatchSize__c.field-meta.xml
<CustomField>
    <fullName>OfficeGroupMemberResetBatchSize__c</fullName>
    <label>出社グループメンバーリセットバッチサイズ</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/SearchEventErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>SearchEventErrorMessage__c</fullName>
    <label>検索イベントエラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/SwitchingOfficeRemoteEventErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>SwitchingOfficeRemoteEventErrorMessage__c</fullName>
    <label>出社在宅切り替えイベントエラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/WorkStyleTypeOffice__c.field-meta.xml
<CustomField>
    <fullName>WorkStyleTypeOffice__c</fullName>
    <label>勤務形態_出社</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteAccessSetting__c/fields/WorkStyleTypeRemote__c.field-meta.xml
<CustomField>
    <fullName>WorkStyleTypeRemote__c</fullName>
    <label>勤務形態_在宅</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>セクション</label>
    <nameField>
        <label>セクション名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/QueueName__c.field-meta.xml
<CustomField>
    <fullName>QueueName__c</fullName>
    <label>キュー名</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <externalId>true</externalId>
    <label>セクションID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RemoteAccessAuthorityTestDataFactory.cls
/**
 * @Description: TestDataactory.
 * 
 * @author hi-takada
 * @date 2022/03/01
 */
@isTest
public class RemoteAccessAuthorityTestDataFactory {

    /**
     * @Description カスタム設定を作成
     * @return `void`
     */
    public static RemoteAccessSetting__c createRemoteAccessSetting(){

        RemoteAccessSetting__c remoteAccessSetting = new RemoteAccessSetting__c();
        remoteAccessSetting.ApexErrorEmailTemplate__c = '00XO0000000l99dMAA';
        remoteAccessSetting.ApexErrorEmailtoAddress__c = 'ml-snt-sfdc@virtualex.co.jp';
        remoteAccessSetting.GroupTypeQueue__c = 'Queue';
        remoteAccessSetting.WorkStyleTypeRemote__c = 'remote';
        remoteAccessSetting.WorkStyleTypeOffice__c = 'office';
        remoteAccessSetting.SearchEventErrorMessage__c = '検索処理に失敗しました。システム管理者へご連絡ください。';
        remoteAccessSetting.OfficeGroupId__c = '00GO000000PNWEvMAP';
        remoteAccessSetting.OfficeGroupMemberResetBatchSize__c = 200;
        remoteAccessSetting.SwitchingOfficeRemoteEventErrorMessage__c = '出社在宅切り替え処理に失敗しました。システム管理者へご連絡ください。';

        insert remoteAccessSetting;

        return remoteAccessSetting;
    }

    /**
     * @Description テストレコード作成
     * @return `List<Section__c>`
     */
    public static List<Section__c> createSections() {

        // セクション
        List<Section__c>  sectionList = new List<Section__c>();

        Section__c section_1 = new Section__c(
            SectionId__c = '00001',
            Name = '入替チーム',
            QueueName__c = '入替チーム'
        );
        sectionList.add(section_1);

        Section__c section_2 = new Section__c(
            SectionId__c = '00002',
            Name = '解約申入チーム',
            QueueName__c = '解約申入チーム'
        );
        sectionList.add(section_2);

        Section__c section_3 = new Section__c(
            SectionId__c = '00003',
            Name = '受付チーム',
            QueueName__c = '受付チーム'
        );
        sectionList.add(section_3);

        insert sectionList;

        return sectionList;

    }


}