force-app/main/default/objects/RemoteAccessSetting__c/RemoteAccessSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>在宅アクセス権限制御</label>
</CustomObject>

force-app/main/default/objects/RemoteAccessSetting__c/fields/OfficeGroupMemberResetBatchSize__c.field-meta.xml
<CustomField>
    <fullName>OfficeGroupMemberResetBatchSize__c</fullName>
    <label>出社グループメンバーリセットバッチサイズ</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OfficeGroupMemberResetSchedulable.cls
/**
 * @description 出社グループメンバーリセットスケジュール
 * 
 * @author hi-takada
 * @date 2022/03/01
 */
global class OfficeGroupMemberResetSchedulable implements Schedulable {
	
	global void execute(SchedulableContext ctx) {
        // カスタム設定
        RemoteAccessSetting__c remoteAccessSetting = 
            RemoteAccessSetting__c.getOrgDefaults();

		// バッチサイズ
		Integer	batchSize = 
			Integer.valueOf(
				remoteAccessSetting.OfficeGroupMemberResetBatchSize__c);
		OfficeGroupMemberResetBatchable batchable = 
			new OfficeGroupMemberResetBatchable();
        Database.executeBatch(batchable, batchSize);
	}
  }