force-app/main/default/objects/PhaseGate__c/PhaseGate__c.object-meta.xml
<CustomObject>
    <label>フェーズゲート</label>
    <nameField>
        <displayFormat>PhaseGate-{0000}</displayFormat>
        <label>フェーズゲート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PhaseGate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>フェーズゲート</relationshipLabel>
    <relationshipName>PhaseGate7BO6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/AfterStageMandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>AfterStageMandatoryFieldsErrorMessage__c</fullName>
    <label>後フェーズ必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>この項目には項目のAPI名を記述してください。</inlineHelpText>
    <label>チェック項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/MandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>MandatoryFieldsErrorMessage__c</fullName>
    <label>必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>業務</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewMatter__c</fullName>
                <default>true</default>
                <label>新規</label>
            </value>
            <value>
                <fullName>Cancel__c</fullName>
                <label>解約申入</label>
            </value>
            <value>
                <fullName>CancelCalculate__c</fullName>
                <label>解約精算</label>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
                <label>更新</label>
            </value>
            <value>
                <fullName>ConditionChange__c</fullName>
                <label>条件変更</label>
            </value>
            <value>
                <fullName>Case</fullName>
                <label>ケース</label>
            </value>
            <value>
                <fullName>Change__c</fullName>
                <label>入替</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>ステップ</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>種別</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>必須項目</fullName>
            </value>
            <value>
                <fullName>表示メッセージ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PhaseGateModel.cls
/**
 * フェーズゲートのモデルクラス
 */

public class PhaseGateModel{
     
     public String objectName = null;//オブジェクト名
     public Id accountId = null;//取引先ID
     public integer stepNum = null;//ステップ数

     /**
      * @description 必須項目レコードを取得
      * @param null
      * @return 'List<PhaseGate__c>'
      */
     public Map<String,List<PhaseGate__c>> getPhaseGate(boolean isNoneMediationRequest , integer stepNum){
          Map<String,List<PhaseGate__c>> result = new Map<String,List<PhaseGate__c>>();
          List<PhaseGate__c> phaseGateList = new List<PhaseGate__c>();
          List<PhaseGate__c> aftterPhaseGateList = new List<PhaseGate__c>();
          stepNum += 1;
          String addText = '';
          if(isNoneMediationRequest)addText = ' AND Stage__c != \'斡旋中\'';
           
          String soqlTextSelect = 'SELECT Field__c,Step__c,MandatoryFieldsErrorMessage__c,AfterStageMandatoryFieldsErrorMessage__c';
          String soqlTextFrom = 'FROM PhaseGate__c';
          String soqlTextWhere = 'WHERE (Account__c=\''+ this.accountId +'\'OR Account__c=\'\') AND Operation__c =\''+this.objectName+'\' AND Type__c = \'必須項目\' AND Step__c != '+stepNum+addText;

          String soqlText = createSoqlText(soqlTextSelect, soqlTextFrom, soqlTextWhere);
          System.debug('SOQLテキスト：'+soqlText);

          for(PhaseGate__c phaseGate : Database.query(soqlText)){
               if(phaseGate.Step__c <= this.stepNum){
                    //必須項目の追加
                    phaseGateList.add(phaseGate);
               }else{
                    //後フェーズ必須項目の追加
                    aftterPhaseGateList.add(phaseGate);
               }
          }
          //返却値の格納
          result.put('phaseGate', phaseGateList);
          result.put('aftterPhaseGate', aftterPhaseGateList);

          return result;
     }

     /**
      * @description ステップ数を取得
      * @param str オブジェクト名
      * @return 'void'
      */
     public integer getStepNum(String stage){
          integer result = null;
          String soqlTextSelect = 'SELECT Step__c';
          String soqlTextFrom = 'FROM PhaseGate__c';
          String soqlTextWhere = 'WHERE Operation__c =\'' + this.objectName + '\' AND Stage__c = \'' + stage + '\' AND Type__c = \'必須項目\' LIMIT 1';
          System.debug('objectName:'+this.objectName);
          System.debug('stage:'+stage);
          String soqlText = createSoqlText(soqlTextSelect, soqlTextFrom, soqlTextWhere);
          System.debug('SOQL_TEXT:'+soqlText);
          try{
               PhaseGate__c phaseGateSubSObject =  Database.query(soqlText);
               result = integer.valueOf(phaseGateSubSObject.Step__c);
          }catch(QueryException e){
               System.debug('取得できるフェーズゲートレコードはありませんでした。');
          }
         
          return result;
     }

     public String createSoqlText(String soqlTextSelect, String soqlTextFrom, String soqlTextWhere){
          String result = soqlTextSelect + ' ' + soqlTextFrom + ' ' + soqlTextWhere;
          return result;
     }
     
     /**
      * @description objectNameのsetter
      * @param str オブジェクト名
      * @return 'void'
      */
     public void setObjectName(String str){
          this.objectName = str;
     }

     /**
      * @description accountIdのsetter
      * @param id 取引先ID
      * @return 'void'
      */
     public void setAccountId(Id id){
          this.accountId = id;
     }

     /**
      * @description stepNumのsetter
      * @param num ステップ数
      * @return 'void'
      */
     public void setStepNum(integer num){
          this.stepNum = num;
     }


}