force-app/main/default/objects/AgencyCapacity__c/AgencyCapacity__c.object-meta.xml
<CustomObject>
    <label>不動産キャパ</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>不動産キャパNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AgencyCapacity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>不動産キャパ</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>口座</label>
    <nameField>
        <label>口座番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>口座</relationshipLabel>
    <relationshipName>VCdf</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BankCode__c.field-meta.xml
<CustomField>
    <fullName>BankCode__c</fullName>
    <label>銀行コード</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BankKana__c.field-meta.xml
<CustomField>
    <fullName>BankKana__c</fullName>
    <label>銀行フリガナ</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BranchOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>BranchOfficeCode__c</fullName>
    <label>支店コード</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BranchOfficeKana__c.field-meta.xml
<CustomField>
    <fullName>BranchOfficeKana__c</fullName>
    <label>支店フリガナ</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/ContractorKana__c.field-meta.xml
<CustomField>
    <fullName>ContractorKana__c</fullName>
    <label>名義フリガナ</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/CustomerCode2__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode2__c</fullName>
    <label>顧客コード2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/DepositTypeForFbData__c.field-meta.xml
<CustomField>
    <fullName>DepositTypeForFbData__c</fullName>
    <formula>IF ( TEXT(DepositType__c) = &quot;普通預金&quot;, &quot;1&quot;, IF ( TEXT(DepositType__c)= &quot;当座預金&quot;, &quot;2&quot;, IF ( TEXT(DepositType__c)= &quot;貯蓄預金&quot;, &quot;4&quot;, &quot;1&quot;) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>預金種目(FBデータ用)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>支払</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>支払ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>支払</relationshipLabel>
    <relationshipName>PaymentAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/AccountingTicketType__c.field-meta.xml
<CustomField>
    <fullName>AccountingTicketType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>経理伝票種別</label>
    <referenceTo>SlipType__c</referenceTo>
    <relationshipName>PaymentSlipTypeRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>PaymentBankAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/FBDataName__c.field-meta.xml
<CustomField>
    <fullName>FBDataName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FBデータ名</label>
    <referenceTo>FbData__c</referenceTo>
    <relationshipName>PaymentFbDataRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RemittanceDate__c.field-meta.xml
<CustomField>
    <fullName>RemittanceDate__c</fullName>
    <label>送金日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RentId__c.field-meta.xml
<CustomField>
    <fullName>RentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>家賃ID</label>
    <referenceTo>Rent__c</referenceTo>
    <relationshipName>PaymentRentRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/TotalAmount_PaymentTarget__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount_PaymentTarget__c</fullName>
    <label>合計金額_支払対象</label>
    <summarizedField>PaymentDetail__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>PaymentDetail__c.IsPaymentTarget__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>PaymentDetail__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/TransfererAccount__c.field-meta.xml
<CustomField>
    <fullName>TransfererAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>送金元口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>PaymentBankAccountRelation2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/TransfererAccountContractor__c.field-meta.xml
<CustomField>
    <fullName>TransfererAccountContractor__c</fullName>
    <label>送金元口座名義</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RealEstate__c/RealEstate__c.object-meta.xml
<CustomObject>
    <label>物件</label>
    <nameField>
        <label>物件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent__c/Rent__c.object-meta.xml
<CustomObject>
    <label>家賃</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>家賃名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>RentBankAccountRelation19</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/RealEstateName__c.field-meta.xml
<CustomField>
    <fullName>RealEstateName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>物件</label>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipName>RentRealEstateRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/RentId__c.field-meta.xml
<CustomField>
    <fullName>RentId__c</fullName>
    <externalId>true</externalId>
    <label>家賃ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SlipType__c/SlipType__c.object-meta.xml
<CustomObject>
    <label>伝票種別</label>
    <nameField>
        <label>伝票種別名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/PaymentCategoryNotCreateSpotFbData__c.field-meta.xml
<CustomField>
    <fullName>PaymentCategoryNotCreateSpotFbData__c</fullName>
    <label>スポットFBデータ作成対象外支払区分</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateMonthlyFbData.cls
/**
 * @description        : 毎月支払用FBデータ作成バッチ
 * @author             : h-nakata
**/
public class CreateMonthlyFbData implements Database.Batchable<sObject>, Database.Stateful {
    //取引先ID
    public String accountId {get; set;}
    //FBデータIDリスト
    public List<String> fbDataIds {get; set;}
    //終了フラグ
    public Boolean isEnd {get; set;}

    /**
    * @description 開始処理 対象データ抽出　
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return Iterable 
    **/
    public Iterable<SObject> start(Database.BatchableContext BC) {
        this.isEnd = TRUE;
        //しゃたくさん設定取得
        SyatakusanSetting__c syatakusanSetting = SyatakusanSetting__c.getOrgDefaults();
        //毎月支払用FBデータ作成対象の支払区分を取得
        String paymentCategoryCreateMonthlyPaymentFbData = syatakusanSetting.PaymentCategoryNotCreateSpotFbData__c;
        //処理対象の支払レコード取得(2000件)
        String query = 'SELECT BankAccount__c, AccountingTicketType__r.PaymentCategory__c, ';
        query += 'TransfererAccountContractor__c, ';
        query += 'RemittanceDate__c, ';
        query += 'RentId__r.RealEstateName__r.Account__r.TransfererAccount__r.BankCode__c, ';
        query += 'RentId__r.RealEstateName__r.Account__r.TransfererAccount__r.BankKana__c, ';
        query += 'RentId__r.RealEstateName__r.Account__r.TransfererAccount__r.BranchOfficeCode__c, ';
        query += 'RentId__r.RealEstateName__r.Account__r.TransfererAccount__r.BranchOfficeKana__c, ';
        query += 'RentId__r.RealEstateName__r.Account__r.TransfererAccount__r.DepositTypeForFbData__c, ';
        query += 'RentId__r.RealEstateName__r.Account__r.TransfererAccount__r.Name, ';
        query += 'RentId__r.RealEstateName__r.Account__r.TransfererAccount__r.ContractorKana__c, ';
        query += 'BankAccount__r.BankCode__c, ';
        query += 'BankAccount__r.BankKana__c, ';
        query += 'BankAccount__r.BranchOfficeCode__c, ';
        query += 'BankAccount__r.BranchOfficeKana__c, ';
        query += 'BankAccount__r.DepositTypeForFbData__c, ';
        query += 'BankAccount__r.Name, ';
        query += 'BankAccount__r.ContractorKana__c, ';
        query += 'BankAccount__r.CustomerCode1__c, ';
        query += 'BankAccount__r.CustomerCode2__c, ';
        query += 'TotalAmount_PaymentTarget__c, ';
        query += 'FBDataName__c ';
        query += 'FROM Payment__c ';
        query += 'WHERE RentId__r.RealEstateName__r.Account__c = \'';
        query += this.accountId;
        query += '\' AND FBDataName__c = NULL ';
        query += ' AND AccountingTicketType__r.PaymentCategory__c = \'';
        query += paymentCategoryCreateMonthlyPaymentFbData;
        query += '\' ORDER BY RemittanceDate__c,BankAccount__c';
        query += ' LIMIT 2000';
        //クエリロケーターを利用し、最大5000万件までレコード参照可能とする
        System.debug('---CreateMonthlyFbData---');
        System.debug('start query: ' + query);
        return Database.getQueryLocator(query);
    }
    /**
    * @description 実行処理
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @param List<SObject> records 
    * @return void 
    **/
    public void execute(Database.BatchableContext BC, List<SObject> records) {
        this.isEnd = FALSE;
        Boolean isSpotFb = FALSE;
        Date remittanceDate;
        if(this.fbDataIds == NULL){
            this.fbDataIds = new List<String>();
        }
        //FBデータを作成し、作成したFBデータのIDをリストに追加
        this.fbDataIds.addAll(CreateFbData.CreateFbData(records, remittanceDate, this.fbDataIds, isSpotFb));
    }
    /**
    * @description 終了処理 同バッチを再実行する
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return void 
    **/
    public void finish(Database.BatchableContext BC) {
        if(!this.isEnd){
            //毎月支払用FBデータ作成バッチを再実行
            String batchName = 'CreateMonthlyFbData';
            CreateMonthlyFbData batch = new CreateMonthlyFbData();
            batch.accountId = this.accountId;
            batch.fbDataIds = this.fbDataIds;
            //バッチサイズを取得
            Integer batchSize = ApexBatchUtils.getBatchSize(batchName);
            Database.executeBatch(batch, batchSize);
        }
    }
}