force-app/main/default/objects/AgencyCapacity__c/AgencyCapacity__c.object-meta.xml
<CustomObject>
    <label>不動産キャパ</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>不動産キャパNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AgencyCapacity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>不動産キャパ</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>申請</relationshipLabel>
    <relationshipName>RequestAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/ApplicantCode__c.field-meta.xml
<CustomField>
    <fullName>ApplicantCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社員</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>申請 (社員)</relationshipLabel>
    <relationshipName>RequestContactRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DesiredAgency__c.field-meta.xml
<CustomField>
    <fullName>DesiredAgency__c</fullName>
    <label>希望不動産会社</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DesiredAreaState__c.field-meta.xml
<CustomField>
    <fullName>DesiredAreaState__c</fullName>
    <label>希望エリア_都道府県</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>北海道</fullName>
            </value>
            <value>
                <fullName>青森県</fullName>
            </value>
            <value>
                <fullName>岩手県</fullName>
            </value>
            <value>
                <fullName>宮城県</fullName>
            </value>
            <value>
                <fullName>秋田県</fullName>
            </value>
            <value>
                <fullName>山形県</fullName>
            </value>
            <value>
                <fullName>福島県</fullName>
            </value>
            <value>
                <fullName>茨城県</fullName>
            </value>
            <value>
                <fullName>栃木県</fullName>
            </value>
            <value>
                <fullName>群馬県</fullName>
            </value>
            <value>
                <fullName>埼玉県</fullName>
            </value>
            <value>
                <fullName>千葉県</fullName>
            </value>
            <value>
                <fullName>東京都</fullName>
            </value>
            <value>
                <fullName>神奈川県</fullName>
            </value>
            <value>
                <fullName>新潟県</fullName>
            </value>
            <value>
                <fullName>富山県</fullName>
            </value>
            <value>
                <fullName>石川県</fullName>
            </value>
            <value>
                <fullName>福井県</fullName>
            </value>
            <value>
                <fullName>山梨県</fullName>
            </value>
            <value>
                <fullName>長野県</fullName>
            </value>
            <value>
                <fullName>岐阜県</fullName>
            </value>
            <value>
                <fullName>静岡県</fullName>
            </value>
            <value>
                <fullName>愛知県</fullName>
            </value>
            <value>
                <fullName>三重県</fullName>
            </value>
            <value>
                <fullName>滋賀県</fullName>
            </value>
            <value>
                <fullName>京都府</fullName>
            </value>
            <value>
                <fullName>大阪府</fullName>
            </value>
            <value>
                <fullName>兵庫県</fullName>
            </value>
            <value>
                <fullName>奈良県</fullName>
            </value>
            <value>
                <fullName>和歌山県</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋依頼</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/RealEstate1__c.field-meta.xml
<CustomField>
    <fullName>RealEstate1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>対象物件1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RealEstate__c.ContractorName__c</field>
            <operation>equals</operation>
            <valueField>$Source.ApplicantCode__c</valueField>
        </filterItems>
        <filterItems>
            <field>RealEstate__c.Status__c</field>
            <operation>notEqual</operation>
            <value>解約, 管理外</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipLabel>申請 (物件ID1)</relationshipLabel>
    <relationshipName>RealEstateId1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/RealEstate2__c.field-meta.xml
<CustomField>
    <fullName>RealEstate2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>対象物件2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RealEstate__c.ContractorName__c</field>
            <operation>equals</operation>
            <valueField>$Source.ApplicantCode__c</valueField>
        </filterItems>
        <filterItems>
            <field>RealEstate__c.Status__c</field>
            <operation>notEqual</operation>
            <value>解約, 管理外</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipLabel>申請 (物件ID2)</relationshipLabel>
    <relationshipName>RealEstateId2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/RealEstate3__c.field-meta.xml
<CustomField>
    <fullName>RealEstate3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>対象物件3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ApplicantCode__c</field>
            <operation>equals</operation>
            <valueField>RealEstate__c.ContractorName__c</valueField>
        </filterItems>
        <filterItems>
            <field>RealEstate__c.Status__c</field>
            <operation>notEqual</operation>
            <value>解約, 管理外</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipLabel>申請 (物件3)</relationshipLabel>
    <relationshipName>RealEstateId3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/CorporateHousingRegulation__c.object-meta.xml
<CustomObject>
    <label>社宅規定</label>
    <nameField>
        <label>社宅規定名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>社宅規定</relationshipLabel>
    <relationshipName>CorporateHousingRegulation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DesiredCondition__c/DesiredCondition__c.object-meta.xml
<CustomObject>
    <label>希望条件</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>希望条件NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DesiredCondition__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>希望条件</relationshipLabel>
    <relationshipName>DesiredTermsApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DesiredCondition__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>斡旋依頼</label>
    <referenceTo>MediationRequest__c</referenceTo>
    <relationshipLabel>希望条件</relationshipLabel>
    <relationshipName>MediationRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationPossibleArea__c/MediationPossibleArea__c.object-meta.xml
<CustomObject>
    <label>紹介可能エリア</label>
    <nameField>
        <label>紹介可能エリア名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationPossibleArea__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>紹介可能エリア</relationshipLabel>
    <relationshipName>MediationPossibleArea</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContractNewMatter__c/ServiceContractNewMatter__c.object-meta.xml
<CustomObject>
    <label>サービス_新規</label>
    <nameField>
        <label>サービス契約_新規名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceContractNewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountServiceContractNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutoTraderSelectionModel.cls
public class AutoTraderSelectionModel {
    /**
     * @description 申請レコードのIDから申請を取得
     * @param applicationIds // 申請IDリスト
     * @return `Map<Id, Application__c>`
     */
    public static Application__c getApplicationWhereId(Id applicationId) {

        // 申請を取得
        // 条件；新規．申請
        List<Application__c> results = [
            SELECT 
                Id
                , ApplicantCode__c // 申請者社員コード（参照：取引先担当者）
                , Account__c // 取引先（参照：取引先）
                , MediationRequest__c // 斡旋依頼（True: 自動斡旋依頼、False:手動斡旋依頼）
                , RealEstate1__c //対象物件1
                , RealEstate2__c //対象物件2
                , RealEstate3__c //対象物件3
                , DesiredAgency__c // 希望不動産会社
                , DesiredAreaState__c // 希望エリア_都道府県
                , DesiredAreaCity__c // 希望エリア_市町村
                , ToSNTComment__c // SNT連絡事項
                , ErrorMessage__c //エラーメッセージ
                , AlertMessage__c //アラートメッセージ
            FROM Application__c
           WHERE Id = :String.valueOf(applicationId) 
           LIMIT 1
        ];

        System.debug([
            SELECT Id
            FROM Contact
        ]);
        System.debug('results:'+results);
        return results[0];
    }

    /**
     * @description 不動産キャパを取得
     * @param accountIds // 取引先IDリスト
     * @return `List<AgencyCapacity__c>`
     */
    public static List<AgencyCapacity__c> getAgencyCapacityDesc(
        Set<Id> accountIds) {

        List<AgencyCapacity__c> result = new List<AgencyCapacity__c>();
        result = [
            SELECT 
                Id
                , Account__c // 取引先
                , ReserveNum__c
            FROM AgencyCapacity__c 
            WHERE Account__c IN :accountIds
            ORDER BY ReserveNum__c DESC
        ];
        return result;
    }

    /**
     * @description 希望条件を取得
     * @param newMatterId // 新規Id
     * @return DesiredCondition__c
     */
    //TODO自動
    public static DesiredCondition__c getDesiredConditionWhereApplicationId(
        Id applicationId) {

        DesiredCondition__c results = [
            SELECT 
                Id ,
                Application__c
            FROM DesiredCondition__c
            WHERE Application__c = :String.valueOf(applicationId)
            LIMIT 1
        ];

        return results;
    }

    

     /**
     * @description 取引先担当者を取得
     * @param applicantCodes // 申請者社員コード
     * @return `Map<Id, Contact>`
     */
    //TODO自動
    public static Contact getContact(
        Id applicantCode) {

        
        Contact result = ( [            
            SELECT 
                Id
                , CorporateHousingRegulation__c // 社宅規定ID
                , CorporateHousingRegulation__r.SelectionCount__c // 選定数
            FROM Contact
            WHERE Id = :String.valueOf(applicantCode)
        ]);
        return result ;
    }

    public static Set<SpecifyAgency__c> getspecifyAgencys(
        Id corporateHousingRegulationId
    ){

        Set<SpecifyAgency__c> result = new Set<SpecifyAgency__c>(
            [
            SELECT 
                Id
                , RealEstateAgency__c // 不動産仲介会社（参照：取引先）
            FROM SpecifyAgency__c
            WHERE IsMediation__c = false 
                AND CorporateHousingRegulation__c = :corporateHousingRegulationId
            ]
        );
        return result;
    }

    public static Map<Id, MediationPossibleArea__c> getMediationPossibleAreas(
        String state,
        String city
        ) {
        Map<Id, MediationPossibleArea__c> result = new Map<Id, MediationPossibleArea__c>();

        //希望エリアがNullの場合処理を終了
        if(String.isBlank(state) && String.isBlank(city)){
            return result;
        }

        Boolean addWhere = false;
        String query = 'SELECT Id, Account__c , District__c , State__c , City__c , IsAllCity__c FROM MediationPossibleArea__c WHERE';

        //希望エリア_都道府県に値がある場合、条件に追記
        if(!String.isBlank(state)){
            query += ' ';
            query += 'District__r.State__c IN :states';
        }
        //希望エリア_市町村に値がある場合、条件に追記
        if(!String.isBlank(city)){
            if(addWhere == false){
                query += ' ';
            query += '&';
            }
            query += ' ';
            query += 'District__r.State__c IN :states';
        }

        for (MediationPossibleArea__c mediationPossibleArea : Database.query(query)){
            if(String.isNotBlank(mediationPossibleArea.Account__c)){
                result.put(
                    mediationPossibleArea.Account__c,
                    mediationPossibleArea);
            }
        }

        return result;
    }

    /**
     * @description 斡旋依頼を登録
     * @param mediationRequests // 斡旋依頼リスト
     * @return `void`
     */
    //TODO自動
    public static void insertMediationRequest(
        List<MediationRequest__c> mediationRequests) {

        try {

            if (!mediationRequests.isEmpty()) {
                insert mediationRequests;
            }

        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }


    /**
     * @description TODOを登録
     * @param sendTasks // ToDoリスト
     * @return `void`
     */
    //自動
    public static void insertTask(
        List<Task> sendTasks) {

        try {

            if (!sendTasks.isEmpty()) {
                insert sendTasks;
            }

        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }


}