force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/MaskedItem__mdt/MaskedItem__mdt.object-meta.xml
<CustomObject>
    <label>マスキング項目</label>
</CustomObject>

force-app/main/default/objects/MaskedItem__mdt/fields/AccountRecordType__c.field-meta.xml
<CustomField>
    <fullName>AccountRecordType__c</fullName>
    <label>取引先レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>委託企業</fullName>
            </value>
            <value>
                <fullName>不動産会社/家主</fullName>
            </value>
            <value>
                <fullName>引越業者</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MaskedItem__mdt/fields/ItemApiName__c.field-meta.xml
<CustomField>
    <fullName>ItemApiName__c</fullName>
    <label>項目API名</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaskedItem__mdt/fields/MaskedValue__c.field-meta.xml
<CustomField>
    <fullName>MaskedValue__c</fullName>
    <label>マスキング値</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaskedTarget__mdt/MaskedTarget__mdt.object-meta.xml
<CustomObject>
    <label>マスキング対象</label>
</CustomObject>

force-app/main/default/objects/MaskedTarget__mdt/fields/AccountRecordType__c.field-meta.xml
<CustomField>
    <fullName>AccountRecordType__c</fullName>
    <label>取引先レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>委託企業</fullName>
                <default>true</default>
                <label>委託企業</label>
            </value>
            <value>
                <fullName>不動産会社/家主</fullName>
            </value>
            <value>
                <fullName>引越業者</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MaskedTarget__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaskedTarget__mdt/fields/KeyItemApiName__c.field-meta.xml
<CustomField>
    <fullName>KeyItemApiName__c</fullName>
    <label>キー項目API名</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaskedTarget__mdt/fields/SObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>SObjectApiName__c</fullName>
    <label>オブジェクトAPI名</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OldDeletePersonalInfoFlowAction.cls
/**
 * 
 * @author t-ooshiro-bp
 * @since 2022/03/01
 */
public class OldDeletePersonalInfoFlowAction {
    /**
     * 
     * @param requests 
     */
    @InvocableMethod
    public static void deletePersonalInfo(List<Request> requests) {
        // カスタムメタデータ型：マスキング対象取得
        List<MaskedTarget__mdt> maskedTargets = [
            SELECT AccountRecordType__c, SObjectApiName__c, KeyItemApiName__c
            FROM MaskedTarget__mdt
            WHERE IsActive__c = TRUE
        ];

        // 有効なマスキング対象がない場合は終了
        if (maskedTargets.isEmpty()) {
            return;
        }

        // カスタムメタデータ型：マスキング項目取得
        List<MaskedItem__mdt> maskedItems = [
            SELECT AccountRecordType__c, SObjectApiName__c, ItemApiName__c, MaskedValue__c
            FROM MaskedItem__mdt
            WHERE IsActive__c = TRUE
        ];

        // 取引先レコードタイプ取得
        Map<Id, String> recordTypeMap = new Map<Id, String>();
        for (RecordType rType : [SELECT Id, Name FROM RecordType WHERE IsActive = TRUE AND SobjectType = 'Account']) {
            recordTypeMap.put(rType.Id, rType.Name);
        }

        // 個人情報削除バッチ起動
        for (Request req : requests) {
            executeBatch(req, maskedTargets, maskedItems, recordTypeMap);
        }
    }

    /**
     * 
     * @param req 
     * @param maskedTargets 
     * @param maskedItemMap 
     */
    private static void executeBatch(Request req, List<MaskedTarget__mdt> maskedTargets, List<MaskedItem__mdt> maskedItems, Map<Id, String> recordTypeMap) {
        List<MaskedTarget__mdt> tmpMaskedTargets = new List<MaskedTarget__mdt>();
        for (MaskedTarget__mdt target : maskedTargets) {
            if (target.AccountRecordType__c == null
                    || target.AccountRecordType__c.equals(recordTypeMap.get(req.recordTypeId))) {
                tmpMaskedTargets.add(target);
            }
        }
        List<MaskedItem__mdt> tmpMaskedItems = new List<MaskedItem__mdt>();
        for (MaskedItem__mdt item : maskedItems) {
            if (item.AccountRecordType__c == null
                    || item.AccountRecordType__c.equals(recordTypeMap.get(req.recordTypeId))) {
                tmpMaskedItems.add(item);
            }
        }
        Map<String, Map<String, String>> maskedItemMap = new Map<String, Map<String, String>>();
        for (MaskedItem__mdt maskedItem : tmpMaskedItems) {
            if (!maskedItemMap.containsKey(maskedItem.SObjectApiName__c)) {
                maskedItemMap.put(maskedItem.SObjectApiName__c, new Map<String, String>());
            }
            maskedItemMap.get(maskedItem.SObjectApiName__c).put(maskedItem.ItemApiName__c, maskedItem.MaskedValue__c);
        }

        List<OldDeletePersonalInfoBatch> batchs = new List<OldDeletePersonalInfoBatch>();
        for (MaskedTarget__mdt target : tmpMaskedTargets) {
            // マスキング項目が定義されていないオブジェクトは除外
            if (!maskedItemMap.containsKey(target.SObjectApiName__c)) {
                continue;
            }
            // 起動対象バッチに追加
            batchs.add(
                new OldDeletePersonalInfoBatch(
                    target.SObjectApiName__c,
                    target.KeyItemApiName__c,
                    req.accountId,
                    maskedItemMap.get(target.SObjectApiName__c)
                )
            );
        }
        // 起動対象バッチがない場合は終了
        if (batchs.isEmpty()) {
            return;
        }

        // 個人情報削除バッチのチェーンを生成
        for (Integer i = batchs.size() - 1; i > 0; i--) {
            batchs.get(i - 1).nextBatch = batchs.get(i);
        }

        // 個人情報削除バッチ起動
        Database.executeBatch(batchs.get(0));
    }

    /**
     * 入力値定義
     */
    public class Request {
        /* 取引先.ID */
        @InvocableVariable(required=true label='取引先.ID')
        public Id accountId;
        /* 取引先.レコードタイプID */
        @InvocableVariable(required=true label='取引先.レコードタイプID')
        public Id recordTypeId;
    }
}