force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/AgencyCapacity__c/AgencyCapacity__c.object-meta.xml
<CustomObject>
    <label>不動産キャパ</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>不動産キャパNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AgencyCapacity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>不動産キャパ</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgencyCapacity__c/fields/ReserveNum__c.field-meta.xml
<CustomField>
    <fullName>ReserveNum__c</fullName>
    <formula>CapacityNum__c  -  RequestingNum__c  -  RequestingFmNum__c  -  RequestingNewCommodity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>余力</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>申請</relationshipLabel>
    <relationshipName>RequestAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DesiredAreaCity__c.field-meta.xml
<CustomField>
    <fullName>DesiredAreaCity__c</fullName>
    <label>希望エリア_市町村</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DesiredAreaState__c.field-meta.xml
<CustomField>
    <fullName>DesiredAreaState__c</fullName>
    <label>希望エリア_都道府県</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>北海道</fullName>
            </value>
            <value>
                <fullName>青森県</fullName>
            </value>
            <value>
                <fullName>岩手県</fullName>
            </value>
            <value>
                <fullName>宮城県</fullName>
            </value>
            <value>
                <fullName>秋田県</fullName>
            </value>
            <value>
                <fullName>山形県</fullName>
            </value>
            <value>
                <fullName>福島県</fullName>
            </value>
            <value>
                <fullName>茨城県</fullName>
            </value>
            <value>
                <fullName>栃木県</fullName>
            </value>
            <value>
                <fullName>群馬県</fullName>
            </value>
            <value>
                <fullName>埼玉県</fullName>
            </value>
            <value>
                <fullName>千葉県</fullName>
            </value>
            <value>
                <fullName>東京都</fullName>
            </value>
            <value>
                <fullName>神奈川県</fullName>
            </value>
            <value>
                <fullName>新潟県</fullName>
            </value>
            <value>
                <fullName>富山県</fullName>
            </value>
            <value>
                <fullName>石川県</fullName>
            </value>
            <value>
                <fullName>福井県</fullName>
            </value>
            <value>
                <fullName>山梨県</fullName>
            </value>
            <value>
                <fullName>長野県</fullName>
            </value>
            <value>
                <fullName>岐阜県</fullName>
            </value>
            <value>
                <fullName>静岡県</fullName>
            </value>
            <value>
                <fullName>愛知県</fullName>
            </value>
            <value>
                <fullName>三重県</fullName>
            </value>
            <value>
                <fullName>滋賀県</fullName>
            </value>
            <value>
                <fullName>京都府</fullName>
            </value>
            <value>
                <fullName>大阪府</fullName>
            </value>
            <value>
                <fullName>兵庫県</fullName>
            </value>
            <value>
                <fullName>奈良県</fullName>
            </value>
            <value>
                <fullName>和歌山県</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipLabel>取引先担当者</relationshipLabel>
    <relationshipName>CorporateHousingRegulation_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/CorporateHousingRegulation__c.object-meta.xml
<CustomObject>
    <label>社宅規定</label>
    <nameField>
        <label>社宅規定名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>社宅規定</relationshipLabel>
    <relationshipName>CorporateHousingRegulation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/SelectionCount__c.field-meta.xml
<CustomField>
    <fullName>SelectionCount__c</fullName>
    <label>選定数</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DesiredCondition__c/DesiredCondition__c.object-meta.xml
<CustomObject>
    <label>希望条件</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>希望条件NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DesiredCondition__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>希望条件</relationshipLabel>
    <relationshipName>DesiredTermsApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DesiredCondition__c/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>ServiceContractNewMatter__c</referenceTo>
    <relationshipLabel>希望条件</relationshipLabel>
    <relationshipName>DesiredConditionServiceContractNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DesiredCondition__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>希望条件</relationshipLabel>
    <relationshipName>DesiredTermsNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationPossibleArea__c/MediationPossibleArea__c.object-meta.xml
<CustomObject>
    <label>紹介可能エリア</label>
    <nameField>
        <label>紹介可能エリア名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationPossibleArea__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>紹介可能エリア</relationshipLabel>
    <relationshipName>MediationPossibleArea</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationPossibleArea__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>District__r.City__c</formula>
    <label>市区町村</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>新規 (委託企業)</relationshipLabel>
    <relationshipName>Account_NewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>CorporateHousingRegulationNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>都道府県</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpecifyAgency__c/SpecifyAgency__c.object-meta.xml
<CustomObject>
    <label>指定不動産会社</label>
    <nameField>
        <label>指定不動産会社名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SpecifyAgency__c/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipLabel>指定不動産会社</relationshipLabel>
    <relationshipName>SpecifyAgency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpecifyAgency__c/fields/IsAllCity__c.field-meta.xml
<CustomField>
    <fullName>IsAllCity__c</fullName>
    <formula>District__r.IsAllCity__c</formula>
    <label>都道府県全域</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SpecifyAgency__c/fields/RealEstateAgency__c.field-meta.xml
<CustomField>
    <fullName>RealEstateAgency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>不動産仲介会社</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>指定不動産会社</relationshipLabel>
    <relationshipName>RealEstateSelectionRuleAccountRelation10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpecifyAgency__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( District__r.State__c )</formula>
    <label>都道府県</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RequestTraderAutoTraderSelection.cls
/**
 * @description 自動で斡旋依頼業者を選定するクラス
 * @author tak-sato
 * @since 2022-11-02
 */
public with sharing class RequestTraderAutoTraderSelection{
    public NewMatter__c newMatter { get; set; }  // 新規
    public Application__c application { get; set; } // 申請
    public DesiredCondition__c desiredCondition { get; set; } //希望条件
    public Account account { get; set; } // 取引先
    public CorporateHousingRegulation__c corporateHousingRegulation { get; set; }//社宅規定
    public Contact contact { get; set; } // 取引先担当者

    public Set<SpecifyAgency__c> specifyAgencys { get; set; } //指定不動産会社

    public Map<Id,MediationPossibleArea__c> mediationPossibleAreas { get; set; } //紹介可能エリア

    public List<AgencyCapacity__c> agencyCapacitys { get; set; } //不動産キャパ    
    
    public Set<Id> mediationCompanyIds { get; } //斡旋依頼業者ID

    public Boolean isSelectionFinish(){ // 選定済みフラグ
        if(mediationCompanyIds.size() >= corporateHousingRegulation.SelectionCount__c){
            return true ;
        }else{
            return false ;
        }
    } 

    /**
     * @description 取引先（不動産会社）のIDを格納する
     */
    public void addAccountIdList(Id accountId){
        this.mediationCompanyIds.add(accountId);
    }

    /**
     * @description 指定不動産会社を選定業者に追加
     * 
     * @param tsmrs 斡旋依頼登録情報
     * @param states 都道府県リスト
     * @return `void`
     */
    public void setSelectionSpecifyAgencyAccount() {
        
        // 指定不動産会社の取引先（不動産会社）IDを斡旋依頼登録情報に格納
        // (地区情報が等しい値の場合処理)
        for (SpecifyAgency__c specifyAgency : this.specifyAgencys) {
            Id accountId = specifyAgency.RealEstateAgency__c;
            
            addAccountIdList(accountId);
        }
    }

    /**
     * @description 希望エリアに紐づく不動産キャパの取引先（不動産会社）情報を取得し
     *  tsmrs（斡旋依頼登録情報）へ格納する
     * 
     * @param tsmrs 斡旋依頼登録情報
     * @return `List<TraderSelectionMediationRequest>`
     */
    public void setSelectionMediationPossibleAreaAccount() {

        //選定が終了していた場合、処理を実行しない
        if(isSelectionFinish()){
            return;    
        }
        
        // 不動産キャパ情報クラスのリストを定義
        List<agencyCapacityWrap> agencyCapacityWrapList = new List<agencyCapacityWrap>();

        // 紹介可能エリアと不動産キャパの取引先IDで一致するデータをまとめる
        for (AgencyCapacity__c agencyCapacity : this.agencyCapacitys){

            // 取引先IDが同じ紹介可能エリアを取得
            agencyCapacityWrap agencyCapacityWrap = new agencyCapacityWrap();
            agencyCapacityWrap.agencyCapacity = agencyCapacity;
            agencyCapacityWrap.reserveNum = Integer.valueOf(agencyCapacity.ReserveNum__c);
            agencyCapacityWrap.mediationPossibleArea = this.mediationPossibleAreas.get(agencyCapacity.Account__c);
            agencyCapacityWrapList.add(agencyCapacityWrap);
        }
            

        for (agencyCapacityWrap agencyCapacityWrap : agencyCapacityWrapList){
            // 余力0件の場合、処理なし
            if(agencyCapacityWrap.isReserveFinish){
                continue;
            }

            Id accountId = agencyCapacityWrap.agencyCapacity.Account__c;
            // 希望エリア
            String desiredState = this.application.DesiredAreaState__c;
            String desiredCity = this.application.DesiredAreaCity__c;

            // 対象エリア
            String targetState = agencyCapacityWrap.mediationPossibleArea.State__c ;
            String targetCity = agencyCapacityWrap.mediationPossibleArea.City__c ;
            Boolean isAllCity = 
                agencyCapacityWrap.mediationPossibleArea.IsAllCity__c;

            if(String.isBlank(desiredCity)){
                if(desiredState == targetState){
                    /** 希望エリア_市町村が存在しない場合、
                     *  都道府県のみで比較
                     */
                    if(agencyCapacityWrap.isReserveFinishCheck()){
                        break;
                    }

                    if(isSelectionFinish()){
                        addAccountIdList(accountId);
                    }
                    
                }

            } else {
                if((isAllCity && (desiredState == targetState)) ||
                    (desiredState == targetState) && (desiredCity == targetCity)){
                    /** 希望エリア_市町村が存在する場合、
                     *  都道府県と市町村で比較
                     *  （都道府県全域についても選定に含む）
                     */
                    addAccountIdList(accountId);
                    agencyCapacityWrap.isReserveFinishCheck();
                    if(isSelectionFinish()){
                        break;
                    }
                }
            }        

        }  
    }
    


}