force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/SystemUserId__c.field-meta.xml
<CustomField>
    <fullName>SystemUserId__c</fullName>
    <label>システムユーザId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/UserRegistration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ユーザ登録</label>
</CustomObject>

force-app/main/default/objects/UserRegistration__c/fields/CommunityNicknameLabel__c.field-meta.xml
<CustomField>
    <fullName>CommunityNicknameLabel__c</fullName>
    <label>ニックネームラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/CommunityUsernameLabel__c.field-meta.xml
<CustomField>
    <fullName>CommunityUsernameLabel__c</fullName>
    <label>コミュニティユーザ名ラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/ConfirmPasswordLabel__c.field-meta.xml
<CustomField>
    <fullName>ConfirmPasswordLabel__c</fullName>
    <label>パスワード（確認）ラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/DomainAccount__c.field-meta.xml
<CustomField>
    <fullName>DomainAccount__c</fullName>
    <label>ドメイン_企業コミュニティユーザ(社員)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/DomainRealEstateAgency__c.field-meta.xml
<CustomField>
    <fullName>DomainRealEstateAgency__c</fullName>
    <label>ドメイン_不動産コミュニティユーザ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/DummyEmailDomainAccount__c.field-meta.xml
<CustomField>
    <fullName>DummyEmailDomainAccount__c</fullName>
    <label>ダミーメールドメイン_企業コミュニティユーザ(社員)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/DummyEmailDomainRealEstateAgency__c.field-meta.xml
<CustomField>
    <fullName>DummyEmailDomainRealEstateAgency__c</fullName>
    <label>ダミーメールドメイン_不動産コミュニティユーザ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailLabel__c.field-meta.xml
<CustomField>
    <fullName>EmailLabel__c</fullName>
    <label>メールアドレスラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceAccountId__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceAccountId__c</fullName>
    <label>メールテンプレート差込項目_取引先ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceCommunityNickname__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceCommunityNickname__c</fullName>
    <label>メールテンプレート差込項目_ニックネーム</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceCommunityUsername__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceCommunityUsername__c</fullName>
    <label>メールテンプレート差込項目_コミュニティユーザ名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceEmail__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceEmail__c</fullName>
    <label>メールテンプレート差込項目_メールアドレス</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceFirstName__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceFirstName__c</fullName>
    <label>メールテンプレート差込項目_名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceLastName__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceLastName__c</fullName>
    <label>メールテンプレート差込項目_姓</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplacePassword__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplacePassword__c</fullName>
    <label>メールテンプレート差込項目_パスワード</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplacePhone__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplacePhone__c</fullName>
    <label>メールテンプレート差込項目_携帯電話</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceProfileId__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceProfileId__c</fullName>
    <label>メールテンプレート差込項目_プロファイル</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceUsername__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceUsername__c</fullName>
    <label>メールテンプレート差込項目_ユーザ名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateReplaceUserPage__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateReplaceUserPage__c</fullName>
    <label>メールテンプレート差込項目_ユーザページ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/EmailTemplateUserRegistration__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateUserRegistration__c</fullName>
    <label>メールテンプレート_ユーザ登録</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/FirstnameLabel__c.field-meta.xml
<CustomField>
    <fullName>FirstnameLabel__c</fullName>
    <label>名ラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/InputErrorMessageAccountId__c.field-meta.xml
<CustomField>
    <fullName>InputErrorMessageAccountId__c</fullName>
    <label>入力エラーメッセージ_取引先ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/LastnameLabel__c.field-meta.xml
<CustomField>
    <fullName>LastnameLabel__c</fullName>
    <label>姓ラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/OrgWideEmailAddressName__c.field-meta.xml
<CustomField>
    <fullName>OrgWideEmailAddressName__c</fullName>
    <label>組織のメールアドレス名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/PasswordLabel__c.field-meta.xml
<CustomField>
    <fullName>PasswordLabel__c</fullName>
    <label>パスワードラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/PhoneLabel__c.field-meta.xml
<CustomField>
    <fullName>PhoneLabel__c</fullName>
    <label>携帯電話ラベル</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/ProfileAccount__c.field-meta.xml
<CustomField>
    <fullName>ProfileAccount__c</fullName>
    <label>プロファイル_企業コミュニティユーザ(社員)</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/ProfileRealEstateAgency__c.field-meta.xml
<CustomField>
    <fullName>ProfileRealEstateAgency__c</fullName>
    <label>プロファイル_不動産コミュニティユーザ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RecordTypeAccountAccount__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeAccountAccount__c</fullName>
    <label>レコードタイプ_取引先_委託企業</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RecordTypeAccountRealEstateAgency__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeAccountRealEstateAgency__c</fullName>
    <label>レコードタイプ_取引先_不動産会社</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RecordTypeContactAccount__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeContactAccount__c</fullName>
    <label>レコードタイプ_取引先担当者_企業社員</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RecordTypeContactCompanyStaff__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeContactCompanyStaff__c</fullName>
    <label>レコードタイプ_取引先担当者_社宅担当者</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RecordTypeContactRealEstateAgency__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeContactRealEstateAgency__c</fullName>
    <label>レコードタイプ_取引先担当者_不動産管理会社</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RequiredErrorMessageAccountId__c.field-meta.xml
<CustomField>
    <fullName>RequiredErrorMessageAccountId__c</fullName>
    <label>必須エラーメッセージ_取引先ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RequiredErrorMessageCommunityNickname__c.field-meta.xml
<CustomField>
    <fullName>RequiredErrorMessageCommunityNickname__c</fullName>
    <label>必須エラーメッセージ_ニックネーム</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RequiredErrorMessageCommunityUsername__c.field-meta.xml
<CustomField>
    <fullName>RequiredErrorMessageCommunityUsername__c</fullName>
    <label>必須エラーメッセージ_ユーザ名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RequiredErrorMessageFirstname__c.field-meta.xml
<CustomField>
    <fullName>RequiredErrorMessageFirstname__c</fullName>
    <label>必須エラーメッセージ_名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RequiredErrorMessageLastname__c.field-meta.xml
<CustomField>
    <fullName>RequiredErrorMessageLastname__c</fullName>
    <label>必須エラーメッセージ_姓</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/RequiredErrorMessagePassword__c.field-meta.xml
<CustomField>
    <fullName>RequiredErrorMessagePassword__c</fullName>
    <label>必須エラーメッセージ_パスワード</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/SobjectTypeAccount__c.field-meta.xml
<CustomField>
    <fullName>SobjectTypeAccount__c</fullName>
    <label>オブジェクトタイプ_取引先</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/SobjectTypeContact__c.field-meta.xml
<CustomField>
    <fullName>SobjectTypeContact__c</fullName>
    <label>オブジェクトタイプ_取引先担当者</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommunitiesSelfRegTestDataFactory.cls
/**
 * @Description: TestDataactory.
 * 
 * @author hi-takada
 * @date 2022/03/20
 */
@isTest
public class CommunitiesSelfRegTestDataFactory {

    /**
     * @Description カスタム設定を作成
     * @return `SyatakusanSetting__c`
     */
    public static SyatakusanSetting__c createSyatakusanSetting(){

        SyatakusanSetting__c syatakusanSetting = new SyatakusanSetting__c();
        syatakusanSetting.SystemUserId__c = '005O0000007fyxo';
        insert syatakusanSetting;

        return syatakusanSetting;
    }

    /**
     * @Description カスタム設定を作成
     * @return `UserRegistration__c`
     */
    public static UserRegistration__c createUserRegistration(){

        UserRegistration__c userRegistration = new UserRegistration__c();
        userRegistration.AccountIdLabel__c = '取引先ID(企業ID)';
        userRegistration.CommunityUsernameLabel__c = 'ユーザ名';
        userRegistration.LastnameLabel__c = '姓';
        userRegistration.FirstnameLabel__c = '名';
        userRegistration.CommunityNicknameLabel__c = 'ニックネーム';
        userRegistration.EmailLabel__c = 'メールアドレス';
        userRegistration.PhoneLabel__c = '携帯電話';
        userRegistration.PasswordLabel__c = 'パスワード';
        userRegistration.ConfirmPasswordLabel__c = 'パスワード（確認）';
        userRegistration.RequiredErrorMessageAccountId__c = '取引先ID(企業ID)は必須です。';
        userRegistration.RequiredErrorMessageCommunityUsername__c = 'ユーザ名は必須です。';
        userRegistration.RequiredErrorMessageLastname__c = '姓は必須です。';
        userRegistration.RequiredErrorMessageFirstname__c = '名は必須です。';
        userRegistration.RequiredErrorMessageCommunityNickname__c = 'ニックネームは必須です。';
        userRegistration.RequiredErrorMessagePassword__c = 'パスワードは必須です。';
        userRegistration.InputErrorMessageAccountId__c = '取引先ID(企業ID)の入力値が不正です。';
        userRegistration.SobjectTypeAccount__c = 'Account';
        userRegistration.SobjectTypeContact__c = 'Contact';
        userRegistration.RecordTypeAccountAccount__c = '委託企業';
        userRegistration.RecordTypeAccountRealEstateAgency__c = '不動産会社/家主';
        userRegistration.RecordTypeContactAccount__c = '企業社員';
        userRegistration.RecordTypeContactRealEstateAgency__c = '不動産管理会社';
        userRegistration.RecordTypeContactCompanyStaff__c = '社宅担当者';
        userRegistration.ProfileAccount__c = '企業コミュニティユーザ(社員)';
        userRegistration.ProfileRealEstateAgency__c = '不動産コミュニティユーザ';
        userRegistration.DomainAccount__c = '@invalid_01.co.jp';
        userRegistration.DomainRealEstateAgency__c = '@invalid_02.co.jp';
        userRegistration.DummyEmailDomainAccount__c = '@virtualex.co.jp';
        userRegistration.DummyEmailDomainRealEstateAgency__c = '@virtualex.co.jp';
        userRegistration.EmailTemplateUserRegistration__c = 'ポータルユーザ登録テンプレート';
        userRegistration.OrgWideEmailAddressName__c = '日本社宅サービス';
        userRegistration.EmailTemplateReplaceAccountId__c = '#AccountId#';
        userRegistration.EmailTemplateReplaceUsername__c = '#Username#';
        userRegistration.EmailTemplateReplaceCommunityUsername__c = '#CommunityUsername__c#';
        userRegistration.EmailTemplateReplaceLastName__c = '#LastName#';
        userRegistration.EmailTemplateReplaceFirstName__c = '#FirstName#';
        userRegistration.EmailTemplateReplaceCommunityNickname__c = '#CommunityNickname#';
        userRegistration.EmailTemplateReplaceEmail__c = '#Email#';
        userRegistration.EmailTemplateReplacePhone__c = '#Phone#';
        userRegistration.EmailTemplateReplacePassword__c = '#Password#';
        userRegistration.EmailTemplateReplaceProfileId__c = '#ProfileId#';
        userRegistration.EmailTemplateReplaceUserPage__c = '#UserPage#';
        
        insert userRegistration;

        return userRegistration;
    }


}