force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋依頼</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約手続き</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>斡旋依頼 (新規No)</relationshipLabel>
    <relationshipName>MediationRequestIdNewMatterRelation10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <label>新規ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ManualTraderSelectionHandlerTest.cls
@isTest
public with sharing class ManualTraderSelectionHandlerTest {
    public static Id newMatterId{get; set;}
    @isTest
    public static void createDate(){
        //テストデータ作成
        //カスタム設定
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        TraderSelectionTestDataFactory.createTraderSelectionSetting();

        //取引先(不動産会社)作成
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();

        //申請レコード作成
        List<Application__c> applications = TraderSelectionTestDataFactory.createApplication_TraderSelection();
        
        //新規レコード
        List<NewMatter__c> newMatters = TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(applications);

        NewMatter__c newMatter = newMatters[0];
        System.debug(newMatter);
        newMatterId = newMatter.Id;
        

    }
    @isTest(SeeAllData=true)
    public static void ManualTraderSelectionHandlerTest() {
        system.debug('ManualTraderSelectionHandlerTest BeforeQuerisLimits :'+limits.getQueries());
        //テストデータ作成
        //カスタム設定
        
        //TraderSelectionTestDataFactory.createSyatakusanSetting();
        //TraderSelectionTestDataFactory.createTraderSelectionSetting();
        //取引先(不動産会社)作成
        List<Account> accounts = TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();

        //申請レコード作成
        List<Application__c> applications = TraderSelectionTestDataFactory.createApplication_TraderSelection();
        
        //新規レコード
        List<NewMatter__c> newMatters = TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(applications);

        NewMatter__c newMatter = newMatters[0];
        System.debug(newMatter);
        newMatterId = newMatter.Id;
        MediationRequest__c mediationRequest = new MediationRequest__c(
            NewMatterId__c = newMatterId , 
            RequestTraderId__c = accounts[0].Id
        ); 
        insert mediationRequest;
        
        List<String> accountIds = new List<String>();
        accountIds.add(String.valueOf(accounts[0].Id));

        Test.startTest();
        ManualTraderSelection.getMediationRequestProcess(newMatterId);

        ManualTraderSelection.searchProcess('' ,'','神奈川県','');

        ManualTraderSelection.upsertMediationRequestProcess(newMatterId,accountIds);

        ManualTraderSelection.updateMediationStatusProcess(newMatterId,accountIds,accountIds[0],'依頼中');
        //ManualTraderSelection.updateMediationStatusProcess(newMatterId,accountIds,accountIds[0],'成約');

        ManualTraderSelection.deleteMediationRequestProcess(newMatterId,accounts[0].Id);

        Test.stopTest();
    }
}