force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/RealEstateName__c.field-meta.xml
<CustomField>
    <fullName>RealEstateName__c</fullName>
    <label>相手先物件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FifthSetConfirm__c/FifthSetConfirm__c.object-meta.xml
<CustomObject>
    <label>5点確定</label>
    <nameField>
        <displayFormat>FS-{000000000}</displayFormat>
        <label>5点確定名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FifthSetConfirm__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FifthSetConfirm__c/fields/FloorPlanNum__c.field-meta.xml
<CustomField>
    <fullName>FloorPlanNum__c</fullName>
    <label>間取り_数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FifthSetConfirm__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipName>FifthSetConfirmNewMatterRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FifthSetConfirm__c/fields/RealEstateName__c.field-meta.xml
<CustomField>
    <fullName>RealEstateName__c</fullName>
    <label>物件/駐車場名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FifthSetConfirm__c/fields/RealEstateNameKana__c.field-meta.xml
<CustomField>
    <fullName>RealEstateNameKana__c</fullName>
    <label>物件/駐車場名フリガナ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FifthSetConfirm__c/fields/SecurityDeposit__c.field-meta.xml
<CustomField>
    <fullName>SecurityDeposit__c</fullName>
    <label>敷金</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Matching__c/Matching__c.object-meta.xml
<CustomObject>
    <label>マッチング</label>
    <nameField>
        <label>マッチング名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Matching__c/fields/FloorPlanNum__c.field-meta.xml
<CustomField>
    <fullName>FloorPlanNum__c</fullName>
    <label>間取_数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Matching__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>マッチング</relationshipLabel>
    <relationshipName>MatchingNewMatterRelation1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matching__c/fields/PaperType__c.field-meta.xml
<CustomField>
    <fullName>PaperType__c</fullName>
    <label>帳票種類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>重説</fullName>
            </value>
            <value>
                <fullName>契約書</fullName>
            </value>
            <value>
                <fullName>請求書</fullName>
            </value>
            <value>
                <fullName>図面</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matching__c/fields/PenaltyTermStart1__c.field-meta.xml
<CustomField>
    <fullName>PenaltyTermStart1__c</fullName>
    <label>違約金1_期間始まり</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Matching__c/fields/RealEstateName__c.field-meta.xml
<CustomField>
    <fullName>RealEstateName__c</fullName>
    <label>物件名/駐車場名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matching__c/fields/RealEstateNameKana__c.field-meta.xml
<CustomField>
    <fullName>RealEstateNameKana__c</fullName>
    <label>物件名/駐車場名フリガナ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matching__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>号室/区画</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/MatchingComparisonResult__c.object-meta.xml
<CustomObject>
    <label>マッチング比較結果</label>
    <nameField>
        <label>マッチング比較結果名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptBill__c.field-meta.xml
<CustomField>
    <fullName>IsExceptBill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>請求書不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptContract__c.field-meta.xml
<CustomField>
    <fullName>IsExceptContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>契約書不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptDrawing__c.field-meta.xml
<CustomField>
    <fullName>IsExceptDrawing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>図面不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptImportantExplanation__c.field-meta.xml
<CustomField>
    <fullName>IsExceptImportantExplanation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>重説不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipName>MatchingComparisonResultNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/FifthSetConfirm__c.field-meta.xml
<CustomField>
    <fullName>FifthSetConfirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約条件</label>
    <referenceTo>FifthSetConfirm__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>FifthSetConfirmNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/RealEstateNameKana__c.field-meta.xml
<CustomField>
    <fullName>RealEstateNameKana__c</fullName>
    <formula>RealEstate__r.Kana__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>物件名カナ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>都道府県</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <formula>Account__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>郵便番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MatchingTriggerTest.cls
/**
 * @Description: Testing for class MatchingTrigger.
 * 
 * @author t-ooshiro-bp
 * @date 2022/02/16
 */
@isTest
private class MatchingTriggerTest {

    /**
     * @Description 共通テストレコード作成
     */
    /*
    @testSetup
    static void setup() {
        // カスタム設定を作成
        MatchingComparisonTestDataFactory.createTraderSelectionSetting();
        MatchingComparisonTestDataFactory.createMatchingSetting();
        MatchingComparisonTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        Application__c application = MatchingComparisonTestDataFactory.createAccount_Mass_TraderSelection(1, 'メール');
        // 新規データ作成（単一）
        // NewMatter__c newMatter = MatchingComparisonTestDataFactory.createNewMatter_one_TraderSelection(application);
    }
    */
    /**
     * @Description 
     */
    /*
    @isTest
    static void matchingComparisonTest_001() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（引越申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '引越申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：引越申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = false;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = false;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(fifthSetConfirms.isEmpty());
    }
    */
    /**
     * @Description 
     */
    /*
    @isTest
    static void matchingComparisonTest_002() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（引越申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '引越申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：引越申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = false;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = false;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Matching__c matching_2 = new Matching__c(
            Name = 'マッチング比較用_契約書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '契約書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_2);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(fifthSetConfirms.isEmpty());
    }
    */

    /**
     * @Description 
     */
    /*
    @isTest
    static void matchingComparisonTest_003() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（引越申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '引越申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：引越申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = false;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = false;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Matching__c matching_2 = new Matching__c(
            Name = 'マッチング比較用_契約書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '契約書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_2);

        Matching__c matching_3 = new Matching__c(
            Name = 'マッチング比較用_請求書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '請求書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_3);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(fifthSetConfirms.isEmpty());
    }
    */

    /**
     * @Description 
     */
    /*

    /*
    @isTest
    static void matchingComparisonTest_004() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（引越申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '引越申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：引越申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = false;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = false;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Matching__c matching_2 = new Matching__c(
            Name = 'マッチング比較用_契約書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '契約書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_2);

        Matching__c matching_3 = new Matching__c(
            Name = 'マッチング比較用_請求書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '請求書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_3);

        Matching__c matching_4 = new Matching__c(
            Name = 'マッチング比較用_図面',
            NewMatter__c = newMatter.Id,
            PaperType__c = '図面',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_4);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!fifthSetConfirms.isEmpty());
    }
    */

    /**
     * @Description 
     */
    /*
    @isTest
    static void matchingComparisonTest_101() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（駐車場申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '駐車場申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：駐車場申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = true;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = true;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(fifthSetConfirms.isEmpty());
    }
    */

    /**
     * @Description 
     */
    /*
    @isTest
    static void matchingComparisonTest_102() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（駐車場申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '駐車場申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：駐車場申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = true;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = true;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Matching__c matching_2 = new Matching__c(
            Name = 'マッチング比較用_契約書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '契約書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_2);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(fifthSetConfirms.isEmpty());
    }
    */

    /**
     * @Description 
     */
    /*
    @isTest
    static void matchingComparisonTest_103() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（駐車場申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '駐車場申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：駐車場申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = true;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = true;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Matching__c matching_2 = new Matching__c(
            Name = 'マッチング比較用_契約書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '契約書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_2);

        Matching__c matching_3 = new Matching__c(
            Name = 'マッチング比較用_請求書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '請求書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_3);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!fifthSetConfirms.isEmpty());
    }
    */

    /**
     * @Description 
     */
    /*
    @isTest
    static void matchingComparisonTest_104() {
        List<NewMatter__c> newMatters = [SELECT Id, Application__c FROM NewMatter__c];
        NewMatter__c newMatter = newMatters.get(0);
        // レコードタイプ（駐車場申請）取得
        List<RecordType> recordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Application__c' 
              AND Name = '駐車場申請' AND IsActive = true
        ];
        List<Application__c> applications = [SELECT Id, RecordTypeId FROM Application__c WHERE Id = :newMatter.Application__c];
        Application__c application = applications.get(0);
        // 申請にレコードタイプ：駐車場申請を設定
        application.RecordTypeId = recordTypes.get(0).Id;
        update application;

        MatchingComparisonResult__c matchingComparisonResult = new MatchingComparisonResult__c();
        matchingComparisonResult.NewMatter__c = newMatter.Id;
        matchingComparisonResult.IsExceptImportantExplanation__c = true;
        matchingComparisonResult.IsExceptContract__c = false;
        matchingComparisonResult.IsExceptBill__c = false;
        matchingComparisonResult.IsExceptDrawing__c = true;
        insert matchingComparisonResult;

        // マッチング
        List<Matching__c>  matchings = new List<Matching__c>();

        Matching__c matching_1 = new Matching__c(
            Name = 'マッチング比較用_重説',
            NewMatter__c = newMatter.Id,
            PaperType__c = '重説',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_1);

        Matching__c matching_2 = new Matching__c(
            Name = 'マッチング比較用_契約書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '契約書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_2);

        Matching__c matching_3 = new Matching__c(
            Name = 'マッチング比較用_請求書',
            NewMatter__c = newMatter.Id,
            PaperType__c = '請求書',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_3);

        Matching__c matching_4 = new Matching__c(
            Name = 'マッチング比較用_図面',
            NewMatter__c = newMatter.Id,
            PaperType__c = '図面',
            RealEstateName__c = 'テスト物件名1',
            RealEstateNameKana__c = 'テストブッケンメイ1',
            ZipCode__c = '105-0011',
            Room__c = '101',
            State__c = '東京都',
            City__c = '港区',
            FloorPlanNum__c = 100,
            SecurityDeposit__c = 200,
            PenaltyTermStart1__c = Date.parse('2022/02/01')
        );
        matchings.add(matching_4);

        Test.startTest();
        insert matchings;
        Test.stopTest();

        List<MatchingComparisonResult__c> matchingComparisonResults = [SELECT Id FROM MatchingComparisonResult__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!matchingComparisonResults.isEmpty());
        List<FifthSetConfirm__c> fifthSetConfirms = [SELECT Id FROM FifthSetConfirm__c WHERE NewMatter__c = :newMatter.Id];
        System.assert(!fifthSetConfirms.isEmpty());
    }
    */
}