force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MediationRequestSendTest.cls
@isTest
public with sharing class MediationRequestSendTest {
    @isTest
    public static void DoTest() {
       //カスタム設定
       TraderSelectionTestDataFactory.createSyatakusanSetting();
       TraderSelectionTestDataFactory.createTraderSelectionSetting();

        //取引先(不動産会社)作成
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();

        //申請レコード作成
        List<Application__c> applications = TraderSelectionTestDataFactory.createApplication_TraderSelection();

        //新規レコード
        test.startTest();
        List<NewMatter__c> newMatter = TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(applications);

        RequestTraderDataFactory.createRequestTraders(newMatter[0].Id);
        MediationRequestSend.accountSendNotificationFuture(newMatter[0].Id);
        test.stopTest();
    }
}