force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>口座</label>
    <nameField>
        <label>口座番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/fields/BankCode__c.field-meta.xml
<CustomField>
    <fullName>BankCode__c</fullName>
    <label>銀行コード</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BranchOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>BranchOfficeCode__c</fullName>
    <label>支店コード</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/DepositType__c.field-meta.xml
<CustomField>
    <fullName>DepositType__c</fullName>
    <label>預金種目</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AccountType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FifthSetConfirm__c/FifthSetConfirm__c.object-meta.xml
<CustomObject>
    <label>5点確定</label>
    <nameField>
        <displayFormat>FS-{000000000}</displayFormat>
        <label>5点確定名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FifthSetConfirm__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipName>FifthSetConfirmNewMatterRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matching__c/Matching__c.object-meta.xml
<CustomObject>
    <label>マッチング</label>
    <nameField>
        <label>マッチング名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Matching__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>マッチング</relationshipLabel>
    <relationshipName>MatchingNewMatterRelation1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matching__c/fields/PaperType__c.field-meta.xml
<CustomField>
    <fullName>PaperType__c</fullName>
    <label>帳票種類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>重説</fullName>
            </value>
            <value>
                <fullName>契約書</fullName>
            </value>
            <value>
                <fullName>請求書</fullName>
            </value>
            <value>
                <fullName>図面</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/MatchingComparisonResult__c.object-meta.xml
<CustomObject>
    <label>マッチング比較結果</label>
    <nameField>
        <label>マッチング比較結果名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchingComparisonResult__c/fields/DepositType__c.field-meta.xml
<CustomField>
    <fullName>DepositType__c</fullName>
    <label>保証金_区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>自動</fullName>
            </value>
            <value>
                <fullName>重説</fullName>
            </value>
            <value>
                <fullName>契約書</fullName>
            </value>
            <value>
                <fullName>請求書</fullName>
            </value>
            <value>
                <fullName>図面</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptBill__c.field-meta.xml
<CustomField>
    <fullName>IsExceptBill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>請求書不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptContract__c.field-meta.xml
<CustomField>
    <fullName>IsExceptContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>契約書不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptDrawing__c.field-meta.xml
<CustomField>
    <fullName>IsExceptDrawing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>図面不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/IsExceptImportantExplanation__c.field-meta.xml
<CustomField>
    <fullName>IsExceptImportantExplanation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>重説不要フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonResult__c/fields/NewMatter__c.field-meta.xml
<CustomField>
    <fullName>NewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>新規</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipName>MatchingComparisonResultNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/MatchingComparisonTarget__mdt.object-meta.xml
<CustomObject>
    <label>マッチング比較対象</label>
</CustomObject>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/FieldsName__c.field-meta.xml
<CustomField>
    <fullName>FieldsName__c</fullName>
    <label>項目名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsBill__c.field-meta.xml
<CustomField>
    <fullName>IsBill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>請求書フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsContract__c.field-meta.xml
<CustomField>
    <fullName>IsContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>契約書フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsDrawing__c.field-meta.xml
<CustomField>
    <fullName>IsDrawing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>図面フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/IsImportantExplanation__c.field-meta.xml
<CustomField>
    <fullName>IsImportantExplanation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>重説フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/ReferenceName__c.field-meta.xml
<CustomField>
    <fullName>ReferenceName__c</fullName>
    <label>参照名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatchingComparisonTarget__mdt/fields/RowNum__c.field-meta.xml
<CustomField>
    <fullName>RowNum__c</fullName>
    <label>行番号</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/FifthSetConfirm__c.field-meta.xml
<CustomField>
    <fullName>FifthSetConfirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約条件</label>
    <referenceTo>FifthSetConfirm__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>FifthSetConfirmNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/AccountType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>普通預金</fullName>
    </customValue>
    <customValue>
        <fullName>当座預金</fullName>
    </customValue>
    <masterLabel>口座種別</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MatchingComparisonModel.cls
/**
 * マッチング画面のモデルクラス
 */
public class MatchingComparisonModel {

    /**
     * カスタムメタデータ：マッチング比較対象 取得
     * @return  `List<MatchingComparisonTarget__mdt>`
     */
    public static List<MatchingComparisonTarget__mdt> getMatchingComparisonTargetMdt() {
        return [
            SELECT
                FieldsName__c,
                ReferenceName__c,
                RowNum__c,
                IsImportantExplanation__c,
                IsContract__c,
                IsBill__c,
                IsDrawing__c
            FROM MatchingComparisonTarget__mdt
            ORDER BY RowNum__c
        ];
    }

    /**
     * 新規レコード取得（複数）
     * @param newMatterIds 
     * @return  `List<NewMatter__c>`
     */
    public static List<NewMatter__c> getNewMatters(Set<Id> newMatterIds) {
        return [
            SELECT
                Id,
                Application__r.RecordType.Name
            FROM NewMatter__c
            WHERE Id IN :newMatterIds
        ];
    }

    /**
     * マッチング取得（新規ID指定）
     * @param newMatterIds 
     * @param fieldNames 
     * @return  `List<Matching__c>`
     */
    public static List<Matching__c> getMatchingsByNewMatterIds(Set<Id> newMatterIds, List<String> fieldNames) {
        List<String> cloneFieldNames = fieldNames.clone();
        cloneFieldNames.add(0, 'PaperType__c');
        cloneFieldNames.add(0, 'NewMatter__c');
        cloneFieldNames.add(0, 'Id');
        List<String> querys = new List<String>{
            'SELECT',
            String.join(cloneFieldNames, ', '),
            'FROM Matching__c',
            'WHERE NewMatter__c IN :newMatterIds'
        };
        return Database.query(String.join(querys, ' '));
    }

    /**
     * マッチング取得（新規ID一件指定）
     * @param newMatterIds 
     * @param fieldNames 
     * @return  `List<Matching__c>`
     */
    public static List<Matching__c> getMatchingsByNewMatterId(  
        String newMatterId) {

        return 
            [SELECT 
                Id
                , Name
                , NewMatter__c
                , PaperType__c
            FROM Matching__c
            WHERE NewMatter__c = :newMatterId
            ];
    }

    /**
     * マッチング比較結果取得（新規ID指定）
     * @param newMatterIds 
     * @param fieldNames 
     * @return  `List<MatchingComparisonResult__c>`
     */
    public static List<MatchingComparisonResult__c> getMatchingComparisonResultsByNewMatterIds(Set<Id> newMatterIds, List<String> fieldNames) {
        List<String> cloneFieldNames = fieldNames.clone();
        cloneFieldNames.add(0, 'IsExceptDrawing__c');
        cloneFieldNames.add(0, 'IsExceptBill__c');
        cloneFieldNames.add(0, 'IsExceptContract__c');
        cloneFieldNames.add(0, 'IsExceptImportantExplanation__c');
        cloneFieldNames.add(0, 'NewMatter__c');
        cloneFieldNames.add(0, 'Id');
        List<String> querys = new List<String>{
            'SELECT',
            String.join(cloneFieldNames, ', '),
            'FROM MatchingComparisonResult__c',
            'WHERE NewMatter__c IN :newMatterIds'
        };
        return Database.query(String.join(querys, ' '));
    }

    /**
     * マッチング比較結果取得（新規ID一件指定）
     * @param newMatterId 
     * @return  `List<MatchingComparisonResult__c>`
     */
    public static List<MatchingComparisonResult__c> getMatchingComparisonResultsByNewMatterId(
        String newMatterId) {

        return 
            [SELECT 
                Id,
                IsExceptImportantExplanation__c,
                IsExceptContract__c,
                IsExceptBill__c,
                IsExceptDrawing__c
            FROM MatchingComparisonResult__c
            WHERE NewMatter__c = :newMatterId
        ];
    }


    /**
     * 5点確定取得（新規ID指定）
     * @param newMatterIds 
     * @param fieldNames 
     * @return  `List<FifthSetConfirm__c>`
     */
    public static List<FifthSetConfirm__c> getFifthSetConfirmsByNewMatterIds(Set<Id> newMatterIds, List<String> fieldNames) {
        List<String> cloneFieldNames = fieldNames.clone();
        cloneFieldNames.add(0, 'NewMatter__c');
        cloneFieldNames.add(0, 'Id');
        for(String str : fieldNames){
            System.debug(str);
        }
        List<String> querys = new List<String>{
            'SELECT',
            String.join(fieldNames, ', '),
            'FROM FifthSetConfirm__c',
            'WHERE NewMatter__c IN :newMatterIds'
        };
        return Database.query(String.join(querys, ' '));
    }


    /**
     * 口座取得（銀行番号、支店番号、口座番号、種別指定）
     * @param bankAccountBankNum 
     * @param bankAccountBranchOfficeNum 
     * @param bankAccountNum 
     * @param bankAccountType 
     * @return  `List<BankAccount__c>`
     */
    public static List<BankAccount__c> getBankAccounts(
        String bankAccountBankNum, String bankAccountBranchOfficeNum,
        String bankAccountNum, String bankAccountType) {

        return  
            [SELECT 
                Id
            FROM BankAccount__c
            WHERE BankCode__c = :BankAccountBankNum
                AND BranchOfficeCode__c = :BankAccountBranchOfficeNum
                AND Name= :BankAccountNum
                AND DepositType__c = :BankAccountType
            ];
    }


    /**
     * 
     * @param matchingComparisonResults 
     */
    public static void upsertMatchingComparisonResult(List<MatchingComparisonResult__c> matchingComparisonResults) {
        // 登録／更新対象がnullまたは空の場合は何もしない
        if (matchingComparisonResults == null || matchingComparisonResults.isEmpty()) {
            return;
        }
        try {
            upsert matchingComparisonResults;
        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

    /**
     * 
     * @param matchingComparisonResults 
     */
    public static void updateMatchingComparisonResult(List<MatchingComparisonResult__c> matchingComparisonResults) {
        // 更新対象がnullまたは空の場合は何もしない
        if (matchingComparisonResults == null || matchingComparisonResults.isEmpty()) {
            return;
        }
        try {
            update matchingComparisonResults;
        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

    /**
     * 
     * @param fifthSetConfirms 
     */
    public static void upsertFifthSetConfirm(List<FifthSetConfirm__c> fifthSetConfirms) {
        // 登録／更新対象がnullまたは空の場合は何もしない
        if (fifthSetConfirms == null || fifthSetConfirms.isEmpty()) {
            return;
        }
        try {
            upsert fifthSetConfirms;
        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

    /**
     * 
     * @param fifthSetConfirms 
     */
    public static void updateFifthSetConfirm(List<FifthSetConfirm__c> fifthSetConfirms) {
        // 更新対象がnullまたは空の場合は何もしない
        if (fifthSetConfirms == null || fifthSetConfirms.isEmpty()) {
            return;
        }
        try {
            update fifthSetConfirms;
        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

    /**
     * 
     * @param tasks 
     */
    public static void insertTask(List<Task> tasks) {
        // 登録対象がnullまたは空の場合は何もしない
        if (tasks == null || tasks.isEmpty()) {
            return;
        }
        try {
            insert tasks;
        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

    /**
     * 
     * @param matchings 
     */
    public static void upsertMatching(List<Matching__c> matchings) {
        // 登録／更新対象がnullまたは空の場合は何もしない
        if (matchings == null || matchings.isEmpty()) {
            return;
        }
        try {
            upsert matchings;
        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

    /**
     * 
     * @param bankAccounts 
     */
    public static void insertBankAccount(List<BankAccount__c> bankAccounts) {
        // 登録／更新対象がnullまたは空の場合は何もしない
        if (bankAccounts == null || bankAccounts.isEmpty()) {
            return;
        }
        try {
            insert bankAccounts;
        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

}