force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋依頼</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/ApplicationFormReceiptDate__c.field-meta.xml
<CustomField>
    <fullName>ApplicationFormReceiptDate__c</fullName>
    <formula>TEXT(Application__r.ApplicationArriveDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>申請書着日</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/PhaseGate__c.object-meta.xml
<CustomObject>
    <label>フェーズゲート</label>
    <nameField>
        <displayFormat>PhaseGate-{0000}</displayFormat>
        <label>フェーズゲート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PhaseGate__c/fields/AfterStageMandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>AfterStageMandatoryFieldsErrorMessage__c</fullName>
    <label>後フェーズ必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>この項目には項目のAPI名を記述してください。</inlineHelpText>
    <label>チェック項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/MandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>MandatoryFieldsErrorMessage__c</fullName>
    <label>必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhaseGate.cls
public class PhaseGate{
    List<String> dhisplayPhaseGateErrorMassage = new List<String>();//表示エラーメッセージ
    List<String> dhisplayAftterPhaseGateErrorMassage = new List<String>();//表示エラーメッセージ
    SObject record = null;

    /**
     * @description 必須項目が入力されているかをチェックする。
     * @param List<PhaseGate__c> 必須項目のリスト
     * @return `void`
     */
    public void checkRequiredFields(SObject record , List<PhaseGate__c> phaseGateList){
        
        for(PhaseGate__c phaseGate :phaseGateList){
            String requiredFieldName = phaseGate.Field__c;
            String fieldValue = getFieldValue(requiredFieldName);
            //System.debug(requiredFieldName+':' + fieldValue);
            if(String.isBlank(fieldValue)){
                //必須項目が入力されていないときの処理
                System.debug('必須項目が入力されていない:' + phaseGate.Field__c);
                //dhisplayErrorMassage(phaseGate.Field__c, phaseGate.MandatoryFieldsErrorMessage__c);
                record.addError(phaseGate.Field__c,phaseGate.MandatoryFieldsErrorMessage__c);
            }
        }
    }

    /**
     * @description 後フェーズでの必須項目が入力されているかをチェックする。
     * @param SObject 業務レコード
     * @param List<PhaseGate__c> 後フェーズでの必須項目のリスト
     * @return `void`
     */
    public void checkAftterPhaseRequiredFields(SObject record , List<PhaseGate__c> phaseGateList){
        
        for(PhaseGate__c phaseGate : phaseGateList){
            String requiredFieldName = phaseGate.Field__c;
            String fieldValue = getFieldValue(requiredFieldName);
            //System.debug(requiredFieldName + ':' + fieldValue);
            if(fieldValue != null){
                //後フェーズでの必須項目が入力されている
                System.debug('後フェーズでの必須項目が入力されている:' + phaseGate.Field__c);
                //dhisplayErrorMassage(phaseGate.Field__c, phaseGate.AfterStageMandatoryFieldsErrorMessage__c);
                record.addError(phaseGate.Field__c,phaseGate.AfterStageMandatoryFieldsErrorMessage__c);
            }

        }
    }

    /**
     * @description 項目名から項目の値を取得する。
     * @param String 項目名
     * @return String　取得した項目
     */
    public String getFieldValue(String fieldName){
        String result = '';
        System.debug('fieldName:'+fieldName);
        try{
            result = String.valueOf(this.record.get(fieldName));
        }catch(SObjectException e){
            System.debug(e.getMessage());
            System.debug('フェーズゲートレコードに格納されている項目名が誤っています。');
        }
        return result;
    }
    /**
     * @description エラーを表示する。
     * @param String 項目名
     * @return 'void'
     
    public void dhisplayErrorMassage(String fieldName, String massageText){
        //this.record.addError(fieldName, massageText);

        this.record.addError('ApplicationFormReceiptDate__c',massageText);
        
    }
    */

    /**
     * @description 斡旋不要かをチェックする。
     * @param SObject 
     * @return 'void'
     */
    public boolean isNewMatter(String objectName){
        boolean result = false;
        System.debug('objectName:'+objectName);
        
        if(objectName == 'NewMatter__c'){
            System.debug('MediationRequest__c:'+getFieldValue('Application__r.MediationRequest__c'));
            Id applicationId = getFieldValue('Application__c');
            Application__c application = [SELECT MediationRequest__c FROM Application__c WHERE Id = :applicationId];
            if(application.MediationRequest__c == false){
                result = true;
            }
        }
        return result;
    }


     /**
     * @description SObjectを設定する。
     * @param SObject 
     * @return 'void'
     */
    public void setRecord(SObject objectRecod){
        this.record = objectRecod;
    }

}