force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>口座</label>
    <nameField>
        <label>口座番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>口座</relationshipLabel>
    <relationshipName>VCdf</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpenseItem__c/ExpenseItem__c.object-meta.xml
<CustomObject>
    <label>費目</label>
    <nameField>
        <label>費目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseItem__c/fields/IsPaymentTarget__c.field-meta.xml
<CustomField>
    <fullName>IsPaymentTarget__c</fullName>
    <defaultValue>false</defaultValue>
    <label>支払対象</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>支払</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>支払ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>支払</relationshipLabel>
    <relationshipName>PaymentAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/AccountingTicketType__c.field-meta.xml
<CustomField>
    <fullName>AccountingTicketType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>経理伝票種別</label>
    <referenceTo>SlipType__c</referenceTo>
    <relationshipName>PaymentSlipTypeRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>PaymentBankAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RealEstate__c.field-meta.xml
<CustomField>
    <fullName>RealEstate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>物件</label>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipName>PaymentRealEstateRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RemittanceDate__c.field-meta.xml
<CustomField>
    <fullName>RemittanceDate__c</fullName>
    <label>送金日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RentId__c.field-meta.xml
<CustomField>
    <fullName>RentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>家賃ID</label>
    <referenceTo>Rent__c</referenceTo>
    <relationshipName>PaymentRentRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentDetail__c/PaymentDetail__c.object-meta.xml
<CustomObject>
    <label>支払明細</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>支払明細ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentDetail__c/fields/DetailName__c.field-meta.xml
<CustomField>
    <fullName>DetailName__c</fullName>
    <label>明細名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentDetail__c/fields/ExpenseItem__c.field-meta.xml
<CustomField>
    <fullName>ExpenseItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>費目名</label>
    <referenceTo>ExpenseItem__c</referenceTo>
    <relationshipLabel>支払明細</relationshipLabel>
    <relationshipName>PaymentDetailExpenseItemRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentDetail__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>支払</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>支払明細</relationshipLabel>
    <relationshipName>PaymentDetailPaymentRelation1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProcessControl__c/ProcessControl__c.object-meta.xml
<CustomObject>
    <label>作業工程管理</label>
    <nameField>
        <displayFormat>PC-{000000000}</displayFormat>
        <label>作業工程管理ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessControl__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ProcessControl</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcessControl__c/fields/RentRemittanceDate__c.field-meta.xml
<CustomField>
    <fullName>RentRemittanceDate__c</fullName>
    <label>家賃送金日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RealEstate__c/RealEstate__c.object-meta.xml
<CustomObject>
    <label>物件</label>
    <nameField>
        <label>物件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RealEstate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>物件 (取引先)</relationshipLabel>
    <relationshipName>RealEstate_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/Rent__c.object-meta.xml
<CustomObject>
    <label>家賃</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>家賃名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>RentBankAccountRelation19</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/PaymentEndDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentEndDate__c</fullName>
    <label>支払終了年月</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/PaymentStartDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentStartDate__c</fullName>
    <label>支払開始年月</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/RealEstateName__c.field-meta.xml
<CustomField>
    <fullName>RealEstateName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>物件</label>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipName>RentRealEstateRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>家賃</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/RentId__c.field-meta.xml
<CustomField>
    <fullName>RentId__c</fullName>
    <externalId>true</externalId>
    <label>家賃ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RentDetail__c/RentDetail__c.object-meta.xml
<CustomObject>
    <label>家賃明細</label>
    <nameField>
        <displayFormat>RD-{000000000}</displayFormat>
        <label>家賃明細名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RentDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>送金先口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>家賃明細</relationshipLabel>
    <relationshipName>RentDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/CostCategory__c.field-meta.xml
<CustomField>
    <fullName>CostCategory__c</fullName>
    <label>費用分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>固定費</fullName>
            </value>
            <value>
                <fullName>季節変動費</fullName>
            </value>
            <value>
                <fullName>月次変動費</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/ExpenseItem__c.field-meta.xml
<CustomField>
    <fullName>ExpenseItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>費目</label>
    <referenceTo>ExpenseItem__c</referenceTo>
    <relationshipLabel>家賃明細</relationshipLabel>
    <relationshipName>RentDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/HandlingType__c.field-meta.xml
<CustomField>
    <fullName>HandlingType__c</fullName>
    <label>取扱種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>振込</fullName>
            </value>
            <value>
                <fullName>変動費立替分</fullName>
            </value>
            <value>
                <fullName>個別送金分</fullName>
            </value>
            <value>
                <fullName>海外家主納税分</fullName>
            </value>
            <value>
                <fullName>公団引落分</fullName>
            </value>
            <value>
                <fullName>送金停止プール分</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>家賃</label>
    <referenceTo>Rent__c</referenceTo>
    <relationshipLabel>家賃明細</relationshipLabel>
    <relationshipName>RentDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/SeasonVariableCostOccurrenceMonth__c.field-meta.xml
<CustomField>
    <fullName>SeasonVariableCostOccurrenceMonth__c</fullName>
    <label>季節変動費発生月</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlipType__c/SlipType__c.object-meta.xml
<CustomObject>
    <label>伝票種別</label>
    <nameField>
        <label>伝票種別名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/PaymentCategoryNotCreateSpotFbData__c.field-meta.xml
<CustomField>
    <fullName>PaymentCategoryNotCreateSpotFbData__c</fullName>
    <label>スポットFBデータ作成対象外支払区分</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyatakusanSetting__c/fields/PaymentTargetHandlingType__c.field-meta.xml
<CustomField>
    <fullName>PaymentTargetHandlingType__c</fullName>
    <label>支払対象取扱種別</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecreatePayment.cls
/**
 * @description        : 支払再作成
 * @author             : h-nakata
**/
public class RecreatePayment {
    /**
    * @description 支払再作成
    * @author h-nakata
    * @param String realEstateId 物件ID
    * @param String executionUserId フロー実行ユーザID
    * @return void
    **/
    @future
    public static void RecreatePayment(String realEstateId, String executionUserId) {
        Integer thisYear = Date.today().year();
        Integer thisMonth = Date.today().month();
        //削除対象の支払取得
        List<Payment__c> deletePayments = 
            [SELECT Id
            FROM Payment__c 
            WHERE RealEstate__c = :realEstateId
            AND CALENDAR_YEAR(RemittanceDate__c) = :thisYear
            AND CALENDAR_MONTH(RemittanceDate__c) = :thisMonth];
        List<String> paymentIds = new List<String>();
        for(Payment__c payment : deletePayments){
            paymentIds.add(payment.Id);
        }
        //削除対象で費用分類が月次変動費の支払明細取得
        List<PaymentDetail__c> deletePaymentDetails = 
            [SELECT ExpenseItem__c, Amount__c
            FROM PaymentDetail__c 
            WHERE Payment__c IN :paymentIds
            AND CostCategory__c = '月次変動費'];
        //費目Idをkeyとし、支払明細の金額をvalueとするマップを作成
        Map<Id, Decimal> expenseItemIds = new Map<Id, Decimal>();
        //削除対象で費用分類が月次変動費の支払明細の金額をマップに保存
        for(PaymentDetail__c paymentDetail : deletePaymentDetails){
            expenseItemIds.put(paymentDetail.ExpenseItem__c, paymentDetail.Amount__c);
        }
        //支払&支払明細削除
        Delete deletePayments;

        //物件に紐づく支払開始年月≦今日≦支払終了年月の家賃取得
        Date today = Date.today();
        String thisMonthText = String.valueOf(thisMonth);
        List<Rent__c> rents = 
            [SELECT Id, RealEstateName__r.Account__c
            FROM Rent__c
            WHERE RealEstateName__c = :realEstateId
            AND PaymentStartDate__c <= :today
            AND PaymentEndDate__c >= :today];
        String rentId = rents[0].Id;
        //家賃明細取得(季節変動費は今月が発生月の場合のみ取得)
        List<RentDetail__c> rentDetails = 
            [SELECT BankAccount__c,
            ExpenseItem__c,
            ExpenseItem__r.Name,
            ExpenseItem__r.IsPaymentTarget__c,
            HandlingType__c,
            Amount__c,
            Rent__c,
            CostCategory__c,
            SeasonVariableCostOccurrenceMonth__c
            FROM RentDetail__c 
            WHERE Rent__c = :rentId
            AND (CostCategory__c != '季節変動費' OR (CostCategory__c = '季節変動費' AND SeasonVariableCostOccurrenceMonth__c INCLUDES (:thisMonthText)))];
            String accountId = rents[0].RealEstateName__r.Account__c;
        //工程管理から今月の家賃送金日取得
        List<ProcessControl__c> processControls = 
            [SELECT RentRemittanceDate__c
            FROM ProcessControl__c
            WHERE Account__c = :accountId
            AND CALENDAR_YEAR(RentRemittanceDate__c) = :thisYear
            AND CALENDAR_MONTH(RentRemittanceDate__c) = :thisMonth];
        Date rentRemittanceDate;
        If(!processControls.isEmpty()){
            rentRemittanceDate = processControls[0].RentRemittanceDate__c;
        }
        //しゃたくさん設定取得
        SyatakusanSetting__c syatakusanSetting = SyatakusanSetting__c.getOrgDefaults();
        //毎月支払用FBデータ作成対象の支払区分を取得
        String paymentCategoryCreateMonthlyPaymentFbData = syatakusanSetting.PaymentCategoryNotCreateSpotFbData__c;
        //伝票種別取得
        List<SlipType__c> slipTypes = 
            [SELECT Id, Name
            FROM SlipType__c
            WHERE PaymentCategory__c = :paymentCategoryCreateMonthlyPaymentFbData];

        //送金先口座Idをkeyとし、家賃明細をvalueとするマップを作成
        Map<String, RentDetail__c> bankAccountIds = new Map<String, RentDetail__c>();
        List<Payment__c> payments = new List<Payment__c>();
        for(RentDetail__c rentDetail : rentDetails){
            String bankAccountId = rentDetail.BankAccount__c;
            if(!bankAccountIds.containsKey(bankAccountId)){
                //支払編集
                Payment__c payment = new Payment__c(
                    //取引先
                    Account__c = rents[0].RealEstateName__r.Account__c,
                    //物件
                    RealEstate__c = realEstateId,
                    //家賃
                    RentId__c = rentId,
                    //口座
                    BankAccount__c = bankAccountId,
                    //送金日
                    RemittanceDate__c = rentRemittanceDate,
                    //経理伝票種別
                    AccountingTicketType__c = slipTypes[0].Id
                );
                payments.add(payment);
                bankAccountIds.put(bankAccountId, rentDetail);
            }
        }
        //支払Insert
        Insert payments;

        //送金先口座IDをkeyとし、支払Idをvalueとするマップを作成
        Map<String, String> bankAccounts = new Map<String, String>();
        for(Payment__c payment : payments){
            bankAccounts.put(payment.BankAccount__c, payment.Id);
        }
        List<PaymentDetail__c> paymentDetails = new List<PaymentDetail__c>();
        for(RentDetail__c rentDetail : rentDetails){
            //金額編集(月次変動費の場合マップに保存した金額をセット)
            Decimal amount;
            if(expenseItemIds.containsKey(rentDetail.ExpenseItem__c)){
                amount = expenseItemIds.get(rentDetail.ExpenseItem__c);
            } else {
                amount = rentDetail.Amount__c;
            }
            //支払対象の取扱種別を取得
            String paymentTargetHandlingType = syatakusanSetting.PaymentTargetHandlingType__c;
            //支払対象編集(費目.支払対象がTRUEかつ取扱種別が振込の場合のみTRUEをセット)
            Boolean isPaymentTarget = FALSE;
            if(rentDetail.ExpenseItem__r.IsPaymentTarget__c && rentDetail.HandlingType__c == paymentTargetHandlingType){
                isPaymentTarget = TRUE;
            }
            //支払明細編集
            PaymentDetail__c paymentDetail = new PaymentDetail__c(
                //支払
                Payment__c = bankAccounts.get(rentDetail.BankAccount__c),
                //金額
                Amount__c = amount,
                //費目名
                ExpenseItem__c = rentDetail.ExpenseItem__c,
                //取扱種別
                HandlingType__c = rentDetail.HandlingType__c,
                //支払対象
                IsPaymentTarget__c = isPaymentTarget,
                //費用分類
                CostCategory__c = rentDetail.CostCategory__c,
                //明細名
                DetailName__c = rentDetail.ExpenseItem__r.Name
            );
            paymentDetails.add(paymentDetail);
        }
        //支払明細Insert
        Insert paymentDetails;

        //カスタム通知送信
        Set<String> executionUserIds = new Set<String>();
        executionUserIds.add(executionUserId);
        RecreatePaymentCustomNotification.notifyUsers(executionUserIds);
    }
}