force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>口座</label>
    <nameField>
        <label>口座番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>口座</relationshipLabel>
    <relationshipName>VCdf</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpenseItem__c/ExpenseItem__c.object-meta.xml
<CustomObject>
    <label>費目</label>
    <nameField>
        <label>費目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseItem__c/fields/IsPaymentTarget__c.field-meta.xml
<CustomField>
    <fullName>IsPaymentTarget__c</fullName>
    <defaultValue>false</defaultValue>
    <label>支払対象</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>支払</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>支払ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>支払</relationshipLabel>
    <relationshipName>PaymentAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/AccountingTicketType__c.field-meta.xml
<CustomField>
    <fullName>AccountingTicketType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>経理伝票種別</label>
    <referenceTo>SlipType__c</referenceTo>
    <relationshipName>PaymentSlipTypeRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>PaymentBankAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RealEstate__c.field-meta.xml
<CustomField>
    <fullName>RealEstate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>物件</label>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipName>PaymentRealEstateRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RemittanceDate__c.field-meta.xml
<CustomField>
    <fullName>RemittanceDate__c</fullName>
    <label>送金日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RentId__c.field-meta.xml
<CustomField>
    <fullName>RentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>家賃ID</label>
    <referenceTo>Rent__c</referenceTo>
    <relationshipName>PaymentRentRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentDetail__c/PaymentDetail__c.object-meta.xml
<CustomObject>
    <label>支払明細</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>支払明細ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentDetail__c/fields/DetailName__c.field-meta.xml
<CustomField>
    <fullName>DetailName__c</fullName>
    <label>明細名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentDetail__c/fields/ExpenseItem__c.field-meta.xml
<CustomField>
    <fullName>ExpenseItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>費目名</label>
    <referenceTo>ExpenseItem__c</referenceTo>
    <relationshipLabel>支払明細</relationshipLabel>
    <relationshipName>PaymentDetailExpenseItemRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentDetail__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>支払</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>支払明細</relationshipLabel>
    <relationshipName>PaymentDetailPaymentRelation1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProcessControl__c/ProcessControl__c.object-meta.xml
<CustomObject>
    <label>作業工程管理</label>
    <nameField>
        <displayFormat>PC-{000000000}</displayFormat>
        <label>作業工程管理ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessControl__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ProcessControl</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcessControl__c/fields/RentRemittanceDate__c.field-meta.xml
<CustomField>
    <fullName>RentRemittanceDate__c</fullName>
    <label>家賃送金日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RealEstate__c/RealEstate__c.object-meta.xml
<CustomObject>
    <label>物件</label>
    <nameField>
        <label>物件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RealEstate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>物件 (取引先)</relationshipLabel>
    <relationshipName>RealEstate_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/Rent__c.object-meta.xml
<CustomObject>
    <label>家賃</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>家賃名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>RentBankAccountRelation19</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/PaymentEndDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentEndDate__c</fullName>
    <label>支払終了年月</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/PaymentStartDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentStartDate__c</fullName>
    <label>支払開始年月</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/RealEstateName__c.field-meta.xml
<CustomField>
    <fullName>RealEstateName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>物件</label>
    <referenceTo>RealEstate__c</referenceTo>
    <relationshipName>RentRealEstateRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>家賃</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/RentId__c.field-meta.xml
<CustomField>
    <fullName>RentId__c</fullName>
    <externalId>true</externalId>
    <label>家賃ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RentDetail__c/RentDetail__c.object-meta.xml
<CustomObject>
    <label>家賃明細</label>
    <nameField>
        <displayFormat>RD-{000000000}</displayFormat>
        <label>家賃明細名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RentDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>送金先口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>家賃明細</relationshipLabel>
    <relationshipName>RentDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/CostCategory__c.field-meta.xml
<CustomField>
    <fullName>CostCategory__c</fullName>
    <label>費用分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>固定費</fullName>
            </value>
            <value>
                <fullName>季節変動費</fullName>
            </value>
            <value>
                <fullName>月次変動費</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/ExpenseItem__c.field-meta.xml
<CustomField>
    <fullName>ExpenseItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>費目</label>
    <referenceTo>ExpenseItem__c</referenceTo>
    <relationshipLabel>家賃明細</relationshipLabel>
    <relationshipName>RentDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/HandlingType__c.field-meta.xml
<CustomField>
    <fullName>HandlingType__c</fullName>
    <label>取扱種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>振込</fullName>
            </value>
            <value>
                <fullName>変動費立替分</fullName>
            </value>
            <value>
                <fullName>個別送金分</fullName>
            </value>
            <value>
                <fullName>海外家主納税分</fullName>
            </value>
            <value>
                <fullName>公団引落分</fullName>
            </value>
            <value>
                <fullName>送金停止プール分</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>家賃</label>
    <referenceTo>Rent__c</referenceTo>
    <relationshipLabel>家賃明細</relationshipLabel>
    <relationshipName>RentDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RentDetail__c/fields/SeasonVariableCostOccurrenceMonth__c.field-meta.xml
<CustomField>
    <fullName>SeasonVariableCostOccurrenceMonth__c</fullName>
    <label>季節変動費発生月</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SlipType__c/SlipType__c.object-meta.xml
<CustomObject>
    <label>伝票種別</label>
    <nameField>
        <label>伝票種別名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/PaymentCategoryNotCreateSpotFbData__c.field-meta.xml
<CustomField>
    <fullName>PaymentCategoryNotCreateSpotFbData__c</fullName>
    <label>スポットFBデータ作成対象外支払区分</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyatakusanSetting__c/fields/PaymentTargetHandlingType__c.field-meta.xml
<CustomField>
    <fullName>PaymentTargetHandlingType__c</fullName>
    <label>支払対象取扱種別</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreatePayment.cls
/**
 * @description        : 支払作成バッチ
 * @author             : h-nakata
**/
public class CreatePayment extends AbstractBaseBatch {
    /**
    * @description 初期処理 対象データ抽出　
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return Iterable 
    **/
    public override Iterable<SObject> start(Database.BatchableContext BC) {
        String today = String.valueOf(Date.today());
        String thisMonthText = String.valueOf(Date.today().month());
        //処理対象の家賃明細レコード取得
        String query = 'SELECT Rent__c, ';
        query += 'Rent__r.RealEstateName__r.Account__c, ';
        query += 'Rent__r.RealEstateName__c, ';
        query += 'BankAccount__c, ';
        query += 'ExpenseItem__c, ';
        query += 'ExpenseItem__r.Name, ';
        query += 'ExpenseItem__r.IsPaymentTarget__c, ';
        query += 'HandlingType__c, ';
        query += 'Amount__c, ';
        query += 'CostCategory__c, ';
        query += 'SeasonVariableCostOccurrenceMonth__c ';
        query += 'FROM RentDetail__c ';
        query += 'WHERE Rent__r.PaymentStartDate__c <= ';
        query += today;
        query += ' AND Rent__r.PaymentEndDate__c >=';
        query += today;
        query += ' AND (CostCategory__c != \'季節変動費\' OR (CostCategory__c = \'季節変動費\' AND SeasonVariableCostOccurrenceMonth__c INCLUDES (\'';
        query += thisMonthText;
        query += '\')))';
        //クエリロケーターを利用し、最大5000万件までレコード参照可能とする
        System.debug('---CreatePayment---');
        System.debug('start query: ' + query);
        return Database.getQueryLocator(query);
    }
    /**
    * @description 処理実行
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @param List<SObject> records 
    * @return void 
    **/
    public override void execute(Database.BatchableContext BC, List<SObject> records) {        
        Integer thisYear = Date.today().year();
        Integer thisMonth = Date.today().month();
        //しゃたくさん設定取得
        SyatakusanSetting__c syatakusanSetting = SyatakusanSetting__c.getOrgDefaults();
        //毎月支払用FBデータ作成対象の支払区分を取得
        String paymentCategoryCreateMonthlyPaymentFbData = syatakusanSetting.PaymentCategoryNotCreateSpotFbData__c;
        //伝票種別取得
        List<SlipType__c> slipTypes = 
            [SELECT Id, Name
            FROM SlipType__c
            WHERE PaymentCategory__c = :paymentCategoryCreateMonthlyPaymentFbData];
        //工程管理から今月の家賃送金日を取得し取引先IDをキーとしたマップに格納
        List<ProcessControl__c> processControls = 
            [SELECT Account__c, RentRemittanceDate__c
            FROM ProcessControl__c
            WHERE CALENDAR_YEAR(RentRemittanceDate__c) = :thisYear
            AND CALENDAR_MONTH(RentRemittanceDate__c) = :thisMonth];
        Map<String, Date> accountIds = new Map<String, Date>();
        for(ProcessControl__c processControl : processControls){
            accountIds.put(processControl.Account__c, processControl.RentRemittanceDate__c);
        }

        //家賃ID+送金先口座Idをkeyとし、家賃明細をvalueとするマップを作成
        Map<String, RentDetail__c> uniqueIds = new Map<String, RentDetail__c>();
        List<Payment__c> payments = new List<Payment__c>();
        for (SObject record : records) {
            RentDetail__c rentDetail = (RentDetail__c)record;
            String accountId = rentDetail.Rent__r.RealEstateName__r.Account__c;
            Date rentRemittanceDate = accountIds.get(accountId);
            
            String uniqueId = String.valueOf(rentDetail.Rent__c) + String.valueOf(rentDetail.BankAccount__c);
            if(!uniqueIds.containsKey(uniqueId)){
                //支払編集
                Payment__c payment = new Payment__c(
                    //取引先
                    Account__c = rentDetail.Rent__r.RealEstateName__r.Account__c,
                    //物件
                    RealEstate__c = rentDetail.Rent__r.RealEstateName__c,
                    //家賃
                    RentId__c = rentDetail.Rent__c,
                    //口座
                    BankAccount__c = rentDetail.BankAccount__c,
                    //送金日
                    RemittanceDate__c = rentRemittanceDate,
                    //経理伝票種別
                    AccountingTicketType__c = slipTypes[0].Id
                );
                payments.add(payment);
                uniqueIds.put(uniqueId, rentDetail);
            }
        }
        //支払Insert
        Insert payments;

        //家賃ID+送金先口座Idをkeyとし、支払Idをvalueとするマップを作成
        Map<String, String> uniqueIdPayments = new Map<String, String>();
        for(Payment__c payment : payments){
            uniqueIdPayments.put(String.valueOf(payment.RentId__c) + String.valueOf(payment.BankAccount__c), payment.Id);
        }
        //支払対象の取扱種別を取得
        String paymentTargetHandlingType = syatakusanSetting.PaymentTargetHandlingType__c;
        List<PaymentDetail__c> paymentDetails = new List<PaymentDetail__c>();
        for (SObject record : records) {
            RentDetail__c rentDetail = (RentDetail__c)record;
            //支払対象編集(費目.支払対象がTRUEかつ取扱種別が振込の場合のみTRUEをセット)
            Boolean isPaymentTarget = FALSE;
            if(rentDetail.ExpenseItem__r.IsPaymentTarget__c && rentDetail.HandlingType__c == paymentTargetHandlingType){
                isPaymentTarget = TRUE;
            }
            //支払明細編集
            PaymentDetail__c paymentDetail = new PaymentDetail__c(
                //支払
                Payment__c = uniqueIdPayments.get(String.valueOf(rentDetail.Rent__c) + String.valueOf(rentDetail.BankAccount__c)),
                //金額
                Amount__c = rentDetail.Amount__c,
                //費目名
                ExpenseItem__c = rentDetail.ExpenseItem__c,
                //取扱種別
                HandlingType__c = rentDetail.HandlingType__c,
                //支払対象
                IsPaymentTarget__c = isPaymentTarget,
                //費用分類
                CostCategory__c = rentDetail.CostCategory__c,
                //明細名
                DetailName__c = rentDetail.ExpenseItem__r.Name
            );
            paymentDetails.add(paymentDetail);
        }
        //支払明細Insert
        Insert paymentDetails;
    }
    /**
    * @description 終了処理
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return void 
    **/
    public override void finish(Database.BatchableContext BC) {}
}