force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>口座</label>
    <nameField>
        <label>口座番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/fields/BankCode__c.field-meta.xml
<CustomField>
    <fullName>BankCode__c</fullName>
    <label>銀行コード</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BankKana__c.field-meta.xml
<CustomField>
    <fullName>BankKana__c</fullName>
    <label>銀行フリガナ</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BranchOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>BranchOfficeCode__c</fullName>
    <label>支店コード</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/BranchOfficeKana__c.field-meta.xml
<CustomField>
    <fullName>BranchOfficeKana__c</fullName>
    <label>支店フリガナ</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/ContractorKana__c.field-meta.xml
<CustomField>
    <fullName>ContractorKana__c</fullName>
    <label>名義フリガナ</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/CustomerCode2__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode2__c</fullName>
    <label>顧客コード2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/DepositTypeForFbData__c.field-meta.xml
<CustomField>
    <fullName>DepositTypeForFbData__c</fullName>
    <formula>IF ( TEXT(DepositType__c) = &quot;普通預金&quot;, &quot;1&quot;, IF ( TEXT(DepositType__c)= &quot;当座預金&quot;, &quot;2&quot;, IF ( TEXT(DepositType__c)= &quot;貯蓄預金&quot;, &quot;4&quot;, &quot;1&quot;) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>預金種目(FBデータ用)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>支払</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>支払ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/AccountingTicketType__c.field-meta.xml
<CustomField>
    <fullName>AccountingTicketType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>経理伝票種別</label>
    <referenceTo>SlipType__c</referenceTo>
    <relationshipName>PaymentSlipTypeRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>口座</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipName>PaymentBankAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/FBDataName__c.field-meta.xml
<CustomField>
    <fullName>FBDataName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FBデータ名</label>
    <referenceTo>FbData__c</referenceTo>
    <relationshipName>PaymentFbDataRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/IsTransferFeeSubtract__c.field-meta.xml
<CustomField>
    <fullName>IsTransferFeeSubtract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>振手差引フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RemittanceDate__c.field-meta.xml
<CustomField>
    <fullName>RemittanceDate__c</fullName>
    <label>送金日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/TotalAmount_PaymentTarget__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount_PaymentTarget__c</fullName>
    <label>合計金額_支払対象</label>
    <summarizedField>PaymentDetail__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>PaymentDetail__c.IsPaymentTarget__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>PaymentDetail__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/TransfererAccountContractor__c.field-meta.xml
<CustomField>
    <fullName>TransfererAccountContractor__c</fullName>
    <label>送金元口座名義</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SlipType__c/SlipType__c.object-meta.xml
<CustomObject>
    <label>伝票種別</label>
    <nameField>
        <label>伝票種別名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/PaymentCategoryNotCreateSpotFbData__c.field-meta.xml
<CustomField>
    <fullName>PaymentCategoryNotCreateSpotFbData__c</fullName>
    <label>スポットFBデータ作成対象外支払区分</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateSpotFbData.cls
/**
 * @description        : スポットFBデータ作成バッチ
 * @author             : h-nakata
**/
public class CreateSpotFbData implements Database.Batchable<sObject>, Database.Stateful {
    //送金日
    public Date remittanceDate {get; set;}
    //FBデータレコードIDリスト
    public List<String> fbDataIds {get; set;}
    //フロー実行ユーザ
    public String executionUser {get; set;}
    //終了フラグ
    public Boolean isEnd {get; set;}

    /**
    * @description 初期処理 対象データ抽出　
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return Iterable 
    **/
    public Iterable<SObject> start(Database.BatchableContext BC) {
        this.isEnd = TRUE;
        //しゃたくさん設定取得
        SyatakusanSetting__c syatakusanSetting = SyatakusanSetting__c.getOrgDefaults();
        //スポットFBデータ作成対象外の支払区分を取得
        String paymentCategoryNotCreateSpotFbData = syatakusanSetting.PaymentCategoryNotCreateSpotFbData__c;
        //処理対象の支払レコード取得(2000件)
        String query = 'SELECT BankAccount__c, AccountingTicketType__r.PaymentCategory__c, ';
        query += 'TransfererAccountContractor__c, ';
        query += 'RemittanceDate__c, ';
        query += 'BankAccount__r.BankCode__c, ';
        query += 'BankAccount__r.BankKana__c, ';
        query += 'BankAccount__r.BranchOfficeCode__c, ';
        query += 'BankAccount__r.BranchOfficeKana__c, ';
        query += 'BankAccount__r.DepositTypeForFbData__c, ';
        query += 'BankAccount__r.Name, ';
        query += 'BankAccount__r.ContractorKana__c, ';
        query += 'BankAccount__r.CustomerCode1__c, ';
        query += 'BankAccount__r.CustomerCode2__c, ';
        query += 'IsTransferFeeSubtract__c, ';
        query += 'TotalAmount_PaymentTarget__c, ';
        query += 'FBDataName__c ';
        query += 'FROM Payment__c ';
        query += 'WHERE RemittanceDate__c = ';
        query += String.valueOf(this.remittanceDate);
        query += ' AND FBDataName__c = NULL ';
        query += ' AND AccountingTicketType__r.PaymentCategory__c != \'';
        query += paymentCategoryNotCreateSpotFbData;
        query += '\' ORDER BY RemittanceDate__c,BankAccount__c';
        query += ' LIMIT 2000';
        //クエリロケーターを利用し、最大5000万件までレコード参照可能とする
        System.debug('---CreateSpotFbData---');
        System.debug('start query: ' + query);
        return Database.getQueryLocator(query);
    }
    /**
    * @description 処理実行
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @param List<SObject> records 
    * @return void 
    **/
    public void execute(Database.BatchableContext BC, List<SObject> records) {
        this.isEnd = FALSE;
        Boolean isSpotFb = TRUE;
        if(this.fbDataIds == NULL){
            this.fbDataIds = new List<String>();
        }
        //FBデータを作成し、作成したFBデータのIDをリストに追加
        this.fbDataIds.addAll(CreateFbData.CreateFbData(records, this.remittanceDate, this.fbDataIds, isSpotFb));
    }
    /**
    * @description 終了処理 同バッチを再実行する/カスタム通知送信
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return void 
    **/
    public void finish(Database.BatchableContext BC) {
        if(!this.isEnd){
            //スポットFBデータ作成バッチを再実行
            String batchName = 'CreateSpotFbData';
            CreateSpotFbData batch = new CreateSpotFbData();
            batch.remittanceDate = this.remittanceDate;
            batch.executionUser = this.executionUser;
            batch.fbDataIds = this.fbDataIds;
            //バッチサイズを取得
            Integer batchSize = ApexBatchUtils.getBatchSize(batchName);
            Database.executeBatch(batch, batchSize);
        } else {
            //カスタム通知送信
            Set<String> executionUserIds = new Set<String>();
            executionUserIds.add(this.executionUser);
            CreateFbDataCustomNotification.notifyUsers(executionUserIds);
        }
    }
}