force-app/main/default/objects/Account/fields/AcceptForContactRealEstatePhone__c.field-meta.xml
<CustomField>
    <fullName>AcceptForContactRealEstatePhone__c</fullName>
    <label>(削除)受付連絡用_不動産TEL</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccountAbbreviation__c.field-meta.xml
<CustomField>
    <fullName>AccountAbbreviation__c</fullName>
    <label>取引先略称</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <externalId>true</externalId>
    <label>取引先ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ConsignmentCollectionCancel__c.field-meta.xml
<CustomField>
    <fullName>ConsignmentCollectionCancel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>委託料徴収_解約</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ConsignmentCollectionNew__c.field-meta.xml
<CustomField>
    <fullName>ConsignmentCollectionNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>委託料徴収_新規</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>契約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ContractMailOperatingCostsNote__c.field-meta.xml
<CustomField>
    <fullName>ContractMailOperatingCostsNote__c</fullName>
    <label>(削除)契約書郵送業務費備考</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractMoneyBillingDate__c.field-meta.xml
<CustomField>
    <fullName>ContractMoneyBillingDate__c</fullName>
    <label>(削除)契約金請求日</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractMoneyDeadline__c.field-meta.xml
<CustomField>
    <fullName>ContractMoneyDeadline__c</fullName>
    <label>(削除)契約金締日</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractorCopied__c.field-meta.xml
<CustomField>
    <fullName>ContractorCopied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>(削除)契約者転記済</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractSignatureRepresentative__c.field-meta.xml
<CustomField>
    <fullName>ContractSignatureRepresentative__c</fullName>
    <label>(削除)契約書署名代表者</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractTermEndDate__c.field-meta.xml
<CustomField>
    <fullName>ContractTermEndDate__c</fullName>
    <label>契約期間終期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractTermStartDate__c.field-meta.xml
<CustomField>
    <fullName>ContractTermStartDate__c</fullName>
    <label>契約期間始期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsContractPossible__c.field-meta.xml
<CustomField>
    <fullName>IsContractPossible__c</fullName>
    <label>契約不可マーク</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>有り</fullName>
            </value>
            <value>
                <fullName>無し</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PracticeChargeEmail1__c.field-meta.xml
<CustomField>
    <fullName>PracticeChargeEmail1__c</fullName>
    <label>実務担当メール１</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PracticeChargeEmail2__c.field-meta.xml
<CustomField>
    <fullName>PracticeChargeEmail2__c</fullName>
    <label>実務担当メール２</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <label>代表者</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/WorkPlacePhone__c.field-meta.xml
<CustomField>
    <fullName>WorkPlacePhone__c</fullName>
    <label>(削除)勤務先TEL</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>Account.AccountId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>取引先ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Character__c.field-meta.xml
<CustomField>
    <fullName>Character__c</fullName>
    <label>担当者1キャラ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CompanyStaffCharacteristic__c.field-meta.xml
<CustomField>
    <fullName>CompanyStaffCharacteristic__c</fullName>
    <label>(削除)企業担当者特性</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <label>メール2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailContactRanking__c.field-meta.xml
<CustomField>
    <fullName>EmailContactRanking__c</fullName>
    <label>メール連絡先順位</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/InaugurationDate__c.field-meta.xml
<CustomField>
    <fullName>InaugurationDate__c</fullName>
    <label>(削除)着任日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsNoResident__c.field-meta.xml
<CustomField>
    <fullName>IsNoResident__c</fullName>
    <defaultValue>false</defaultValue>
    <label>入居者不在</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mobile2__c.field-meta.xml
<CustomField>
    <fullName>Mobile2__c</fullName>
    <label>携帯2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OtherDestinationCategory__c.field-meta.xml
<CustomField>
    <fullName>OtherDestinationCategory__c</fullName>
    <label>(削除)その他宛先区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OtherPriorityRanking__c.field-meta.xml
<CustomField>
    <fullName>OtherPriorityRanking__c</fullName>
    <label>その他優先順位</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RetireDate__c.field-meta.xml
<CustomField>
    <fullName>RetireDate__c</fullName>
    <label>退職日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TransferMemo__c.field-meta.xml
<CustomField>
    <fullName>TransferMemo__c</fullName>
    <label>(削除)移管メモ</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DeletePersonalInfoFlowActionTest.cls
/**
 * 
 * @author 
 * @since 
 */
@isTest(SeeAllData=true)
private class DeletePersonalInfoFlowActionTest {
    /**
     * 取引先レコードタイプ：委託企業
     */
    /*
    @isTest
    static void deletePersonalInfo_001() {
        // テスト対象取引先ID
        String accountId = '90000001a';

        // データ生成
        DeletePersonalInfoTestDataFactory.createAccount_Mass_TraderSelection(1, 'メール');

        List<Account> accountEexpecteds = [
            SELECT
                Id,
                RecordTypeId,
                IsContractPossible__c,
                ContractCategory__c,
                AccountAbbreviation__c,
                Representative__c,
                ContractMoneyDeadline__c,
                ContractMoneyBillingDate__c,
                ContractTermStartDate__c,
                ContractTermEndDate__c,
                ContractorCopied__c,
                ConsignmentCollectionNew__c,
                ConsignmentCollectionCancel__c,
                ContractSignatureRepresentative__c,
                ContractMailOperatingCostsNote__c,
                PracticeChargeEmail1__c,
                PracticeChargeEmail2__c,
                WorkPlacePhone__c,
                AcceptForContactRealEstatePhone__c
            FROM Account
            WHERE AccountId__c = :accountId
        ];

        List<Contact> contactEexpecteds = [
            SELECT
                Id,
                OtherDestinationCategory__c,
                CompanyStaffCharacteristic__c,
                Character__c,
                Department,
                OtherPriorityRanking__c,
                EmailContactRanking__c,
                InaugurationDate__c,
                RetireDate__c,
                HasOptedOutOfFax,
                HasOptedOutOfEmail,
                IsNoResident__c,
                TransferMemo__c,
                Description,
                Email,
                Email2__c,
                MobilePhone,
                Mobile2__c
            FROM Contact
            WHERE AccountId = :accountEexpecteds.get(0).Id
        ];

        List<User> userEexpecteds = [
            SELECT
                Id,
                IsActive
            FROM User
            WHERE Contact.AccountId = :accountEexpecteds.get(0).Id
        ];

        Test.startTest();
        List<DeletePersonalInfoFlowAction.Request> requests = new List<DeletePersonalInfoFlowAction.Request>();
        DeletePersonalInfoFlowAction.Request request = new DeletePersonalInfoFlowAction.Request();
        request.accountId = accountEexpecteds.get(0).Id;
        request.recordTypeId = accountEexpecteds.get(0).RecordTypeId;
        requests.add(request);
        DeletePersonalInfoFlowAction.deletePersonalInfo(requests);
        Test.stopTest();

        List<Account> accountActuals = [
            SELECT
                Id,
                RecordTypeId,
                IsContractPossible__c,
                ContractCategory__c,
                AccountAbbreviation__c,
                Representative__c,
                ContractMoneyDeadline__c,
                ContractMoneyBillingDate__c,
                ContractTermStartDate__c,
                ContractTermEndDate__c,
                ContractorCopied__c,
                ConsignmentCollectionNew__c,
                ConsignmentCollectionCancel__c,
                ContractSignatureRepresentative__c,
                ContractMailOperatingCostsNote__c,
                PracticeChargeEmail1__c,
                PracticeChargeEmail2__c,
                WorkPlacePhone__c,
                AcceptForContactRealEstatePhone__c
            FROM Account
            WHERE AccountId__c = :accountId
        ];

        System.assertEquals(accountEexpecteds.get(0).Id, accountActuals.get(0).Id);
        System.assertEquals(accountEexpecteds.get(0).RecordTypeId, accountActuals.get(0).RecordTypeId);

        List<Contact> contactActuals = [
            SELECT
                Id,
                OtherDestinationCategory__c,
                CompanyStaffCharacteristic__c,
                Character__c,
                Department,
                OtherPriorityRanking__c,
                EmailContactRanking__c,
                InaugurationDate__c,
                RetireDate__c,
                HasOptedOutOfFax,
                HasOptedOutOfEmail,
                IsNoResident__c,
                TransferMemo__c,
                Description,
                Email,
                Email2__c,
                MobilePhone,
                Mobile2__c
            FROM Contact
            WHERE AccountId = :accountActuals.get(0).Id
        ];

        System.assertEquals(contactEexpecteds.get(0).Id, contactActuals.get(0).Id);

        List<User> userActuals = [
            SELECT
                Id,
                IsActive
            FROM User
            WHERE Contact.AccountId = :accountActuals.get(0).Id
        ];

        System.assertEquals(userEexpecteds.get(0).Id, userActuals.get(0).Id);
        System.assertEquals(false, userActuals.get(0).IsActive);
    }
    */
    /**
     * 取引先レコードタイプ：不動産会社/家主
     */
    /*
    @isTest
    static void deletePersonalInfo_002() {
        // テスト対象取引先ID
        String accountId = '90000001b';

        // データ生成
        DeletePersonalInfoTestDataFactory.createAccount_Mass_TraderSelection(1, 'メール');

        List<Account> accountEexpecteds = [
            SELECT
                Id,
                RecordTypeId,
                IsContractPossible__c,
                ContractCategory__c,
                AccountAbbreviation__c,
                Representative__c,
                ContractMoneyDeadline__c,
                ContractMoneyBillingDate__c,
                ContractTermStartDate__c,
                ContractTermEndDate__c,
                ContractorCopied__c,
                ConsignmentCollectionNew__c,
                ConsignmentCollectionCancel__c,
                ContractSignatureRepresentative__c,
                ContractMailOperatingCostsNote__c,
                PracticeChargeEmail1__c,
                PracticeChargeEmail2__c,
                WorkPlacePhone__c,
                AcceptForContactRealEstatePhone__c
            FROM Account
            WHERE AccountId__c = :accountId
        ];

        Test.startTest();
        List<DeletePersonalInfoFlowAction.Request> requests = new List<DeletePersonalInfoFlowAction.Request>();
        DeletePersonalInfoFlowAction.Request request = new DeletePersonalInfoFlowAction.Request();
        request.accountId = accountEexpecteds.get(0).Id;
        request.recordTypeId = accountEexpecteds.get(0).RecordTypeId;
        requests.add(request);
        DeletePersonalInfoFlowAction.deletePersonalInfo(requests);
        Test.stopTest();

        List<Account> accountActuals = [
            SELECT
                Id,
                RecordTypeId,
                IsContractPossible__c,
                ContractCategory__c,
                AccountAbbreviation__c,
                Representative__c,
                ContractMoneyDeadline__c,
                ContractMoneyBillingDate__c,
                ContractTermStartDate__c,
                ContractTermEndDate__c,
                ContractorCopied__c,
                ConsignmentCollectionNew__c,
                ConsignmentCollectionCancel__c,
                ContractSignatureRepresentative__c,
                ContractMailOperatingCostsNote__c,
                PracticeChargeEmail1__c,
                PracticeChargeEmail2__c,
                WorkPlacePhone__c,
                AcceptForContactRealEstatePhone__c
            FROM Account
            WHERE AccountId__c = :accountId
        ];

        System.assertEquals(accountEexpecteds.get(0).Id, accountActuals.get(0).Id);
        System.assertEquals(accountEexpecteds.get(0).RecordTypeId, accountActuals.get(0).RecordTypeId);

        // System.assertEquals(accountEexpecteds.get(0).IsContractPossible__c, accountActuals.get(0).IsContractPossible__c);
        // System.assertEquals('1', accountActuals.get(0).ContractCategory__c);
        // System.assertEquals(accountEexpecteds.get(0).AccountAbbreviation__c, accountActuals.get(0).AccountAbbreviation__c);
        // System.assertEquals('○○', accountActuals.get(0).Representative__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractMoneyDeadline__c, accountActuals.get(0).ContractMoneyDeadline__c);
        // System.assertEquals(Decimal.valueOf('99'), accountActuals.get(0).ContractMoneyBillingDate__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractTermStartDate__c, accountActuals.get(0).ContractTermStartDate__c);
        // System.assertEquals(Date.valueOf('4000-12-31'), accountActuals.get(0).ContractTermEndDate__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractorCopied__c, accountActuals.get(0).ContractorCopied__c);
        // System.assertEquals(false, accountActuals.get(0).ConsignmentCollectionNew__c);
        // System.assertEquals(accountEexpecteds.get(0).ConsignmentCollectionCancel__c, accountActuals.get(0).ConsignmentCollectionCancel__c);
        // System.assertEquals(null, accountActuals.get(0).ContractSignatureRepresentative__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractMailOperatingCostsNote__c, accountActuals.get(0).ContractMailOperatingCostsNote__c);
        // System.assertEquals(null, accountActuals.get(0).PracticeChargeEmail1__c);
        // System.assertEquals(accountEexpecteds.get(0).PracticeChargeEmail2__c, accountActuals.get(0).PracticeChargeEmail2__c);
        // System.assertEquals(null, accountActuals.get(0).WorkPlacePhone__c);
        // System.assertEquals('0300000000', accountActuals.get(0).AcceptForContactRealEstatePhone__c);
    }
    */
    /**
     * 取引先レコードタイプ：引越業者
     */
    /*
    @isTest
    static void deletePersonalInfo_003() {
        // テスト対象取引先ID
        String accountId = '90000001c';

        // データ生成
        DeletePersonalInfoTestDataFactory.createAccount_Mass_TraderSelection(1, 'メール');

        List<Account> accountEexpecteds = [
            SELECT
                Id,
                RecordTypeId,
                IsContractPossible__c,
                ContractCategory__c,
                AccountAbbreviation__c,
                Representative__c,
                ContractMoneyDeadline__c,
                ContractMoneyBillingDate__c,
                ContractTermStartDate__c,
                ContractTermEndDate__c,
                ContractorCopied__c,
                ConsignmentCollectionNew__c,
                ConsignmentCollectionCancel__c,
                ContractSignatureRepresentative__c,
                ContractMailOperatingCostsNote__c,
                PracticeChargeEmail1__c,
                PracticeChargeEmail2__c,
                WorkPlacePhone__c,
                AcceptForContactRealEstatePhone__c
            FROM Account
            WHERE AccountId__c = :accountId
        ];

        Test.startTest();
        List<DeletePersonalInfoFlowAction.Request> requests = new List<DeletePersonalInfoFlowAction.Request>();
        DeletePersonalInfoFlowAction.Request request = new DeletePersonalInfoFlowAction.Request();
        request.accountId = accountEexpecteds.get(0).Id;
        request.recordTypeId = accountEexpecteds.get(0).RecordTypeId;
        requests.add(request);
        DeletePersonalInfoFlowAction.deletePersonalInfo(requests);
        Test.stopTest();

        List<Account> accountActuals = [
            SELECT
                Id,
                RecordTypeId,
                IsContractPossible__c,
                ContractCategory__c,
                AccountAbbreviation__c,
                Representative__c,
                ContractMoneyDeadline__c,
                ContractMoneyBillingDate__c,
                ContractTermStartDate__c,
                ContractTermEndDate__c,
                ContractorCopied__c,
                ConsignmentCollectionNew__c,
                ConsignmentCollectionCancel__c,
                ContractSignatureRepresentative__c,
                ContractMailOperatingCostsNote__c,
                PracticeChargeEmail1__c,
                PracticeChargeEmail2__c,
                WorkPlacePhone__c,
                AcceptForContactRealEstatePhone__c
            FROM Account
            WHERE AccountId__c = :accountId
        ];
        System.assertEquals(accountEexpecteds.get(0).Id, accountActuals.get(0).Id);
        System.assertEquals(accountEexpecteds.get(0).RecordTypeId, accountActuals.get(0).RecordTypeId);

        // System.assertEquals(accountEexpecteds.get(0).IsContractPossible__c, accountActuals.get(0).IsContractPossible__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractCategory__c, accountActuals.get(0).ContractCategory__c);
        // System.assertEquals(null, accountActuals.get(0).AccountAbbreviation__c);
        // System.assertEquals('○○', accountActuals.get(0).Representative__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractMoneyDeadline__c, accountActuals.get(0).ContractMoneyDeadline__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractMoneyBillingDate__c, accountActuals.get(0).ContractMoneyBillingDate__c);
        // System.assertEquals(null, accountActuals.get(0).ContractTermStartDate__c);
        // System.assertEquals(Date.valueOf('4000-12-31'), accountActuals.get(0).ContractTermEndDate__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractorCopied__c, accountActuals.get(0).ContractorCopied__c);
        // System.assertEquals(accountEexpecteds.get(0).ConsignmentCollectionNew__c, accountActuals.get(0).ConsignmentCollectionNew__c);
        // System.assertEquals(false, accountActuals.get(0).ConsignmentCollectionCancel__c);
        // System.assertEquals(null, accountActuals.get(0).ContractSignatureRepresentative__c);
        // System.assertEquals(accountEexpecteds.get(0).ContractMailOperatingCostsNote__c, accountActuals.get(0).ContractMailOperatingCostsNote__c);
        // System.assertEquals(accountEexpecteds.get(0).PracticeChargeEmail1__c, accountActuals.get(0).PracticeChargeEmail1__c);
        // System.assertEquals('xxx@xxx.xxx', accountActuals.get(0).PracticeChargeEmail2__c);
        // System.assertEquals(null, accountActuals.get(0).WorkPlacePhone__c);
        // System.assertEquals('0300000000', accountActuals.get(0).AcceptForContactRealEstatePhone__c);
    }
    */
}