force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <externalId>true</externalId>
    <label>取引先ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Case/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ケース</relationshipLabel>
    <relationshipName>bnKj</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CompletedReportDate__c.field-meta.xml
<CustomField>
    <fullName>CompletedReportDate__c</fullName>
    <label>完了報告日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/PhaseGate__c.object-meta.xml
<CustomObject>
    <label>フェーズゲート</label>
    <nameField>
        <displayFormat>PhaseGate-{0000}</displayFormat>
        <label>フェーズゲート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PhaseGate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>フェーズゲート</relationshipLabel>
    <relationshipName>PhaseGate7BO6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/AfterStageMandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>AfterStageMandatoryFieldsErrorMessage__c</fullName>
    <label>後フェーズ必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>この項目には項目のAPI名を記述してください。</inlineHelpText>
    <label>チェック項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/MandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>MandatoryFieldsErrorMessage__c</fullName>
    <label>必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>業務</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewMatter__c</fullName>
                <default>true</default>
                <label>新規</label>
            </value>
            <value>
                <fullName>Cancel__c</fullName>
                <label>解約申入</label>
            </value>
            <value>
                <fullName>CancelCalculate__c</fullName>
                <label>解約精算</label>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
                <label>更新</label>
            </value>
            <value>
                <fullName>ConditionChange__c</fullName>
                <label>条件変更</label>
            </value>
            <value>
                <fullName>Case</fullName>
                <label>ケース</label>
            </value>
            <value>
                <fullName>Change__c</fullName>
                <label>入替</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>ステップ</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>種別</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>必須項目</fullName>
            </value>
            <value>
                <fullName>表示メッセージ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PhaseGateCreateCaseTestData.cls
public class PhaseGateCreateCaseTestData{
    public static List<Case> createData(){
        
        //取引先を作成
        List<Account> accountList= new List<Account>();
        // レコードタイプ（委託企業）取得
        RecordType recordTypeCompany = [
            SELECT Id
            FROM RecordType
            WHERE 
                SobjectType = 'Account' 
                AND Name = '委託企業' 
                AND IsActive = true
            LIMIT 1
        ];
        Account account1 = new Account(
            RecordTypeId = recordTypeCompany.id,//レコードタイプ
            AccountId__c = '312312312', //取引先ID
            Name = 'フェーズゲートテスト取引先132'//取引先名
        );
        accountList.add(account1);

        Account account2 = new Account(
            RecordTypeId = recordTypeCompany.id,//レコードタイプ
            AccountId__c = '423423423', //取引先ID
            Name = 'フェーズゲートテスト取引先133'//取引先名
        );
        accountList.add(account2);

        insert accountList;

        //フェーズゲートレコードを作成
        List<PhaseGate__c> phaseGateList = new List<PhaseGate__c>();
        PhaseGate__c phaseGate1 = new PhaseGate__c(
            Operation__c = 'Case',
            Stage__c = '対応中',
            Step__c = 2,
            Type__c = '必須項目',
            Field__c = 'AcceptDate__c',
            MandatoryFieldsErrorMessage__c = '必須項目です。入力してください。',
            AfterStageMandatoryFieldsErrorMessage__c =  '後フェーズでの必須項目です。入力しないでください。'
        );
        phaseGateList.add(phaseGate1);

        PhaseGate__c phaseGate2 = new PhaseGate__c(
            Operation__c = 'Case',
            Stage__c = '完了報告',
            Step__c = 3,
            Type__c = '必須項目',
            Field__c = 'CompletedReportDate__c',
            MandatoryFieldsErrorMessage__c = '必須項目です。入力してください。',
            AfterStageMandatoryFieldsErrorMessage__c =  '後フェーズでの必須項目です。入力しないでください。'
        );
        phaseGateList.add(phaseGate2);

        insert phaseGateList;

        //ケースレコードを作成
        List<Case> caseList = new List<Case>();
        Case case1 = new Case(
            Status = '対応中',
            Account__c = account1.id,
            Origin = '電話'//受付方法
        );
        caseList.add(case1);

        Case case2 = new Case(
            Status = '対応中',
            Account__c = account2.id,
            Origin = '電話' ,//受付方法
            AcceptDate__c = Date.valueOf('2022-08-17')
        );
        caseList.add(case2);

        Case case3 = new Case(
            Status = '対応中',
            Account__c = account2.id,
            Origin = '電話',//受付方法
            CompletedReportDate__c = Date.valueOf('2022-08-17')
        );
        caseList.add(case3);
        insert caseList;
        return caseList;

    }
}