force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <externalId>true</externalId>
    <label>取引先ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メールAD（テキスト型）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>Account.AccountId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>取引先ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Masking__c/Masking__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>マスキング</label>
</CustomObject>

force-app/main/default/objects/Masking__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>ユーザマスキング値_別名</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Masking__c/fields/CommunityNickname__c.field-meta.xml
<CustomField>
    <fullName>CommunityNickname__c</fullName>
    <label>ユーザマスキング値_ニックネーム</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Masking__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>ユーザマスキング値_メール</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Masking__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>ユーザマスキング値_名</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Masking__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>ユーザマスキング値_姓</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Masking__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>ユーザマスキング値_ユーザ名</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonalInfoDeleteTarget__mdt/PersonalInfoDeleteTarget__mdt.object-meta.xml
<CustomObject>
    <label>個人情報削除対象オブジェクト</label>
</CustomObject>

force-app/main/default/objects/PersonalInfoDeleteTarget__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PersonalInfoDeleteTarget__mdt/fields/SObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>SObjectApiName__c</fullName>
    <label>オブジェクトAPI名</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>(不要)メール２</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/DeletePersonalInfoUserMasking.cls
/**
 * @description        : ユーザマスキング
 * @author             : h-nakata
**/
public class DeletePersonalInfoUserMasking implements Database.Batchable<sObject> {
    //取引先ID
    public String accountId {get; set;}

    /**
    * @description 開始処理 対象データ抽出　
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return Iterable 
    **/
    public Iterable<SObject> start(Database.BatchableContext BC) {
        String accountId = this.accountId;
        //マスキング対象のユーザレコード取得
        String query = 'SELECT Id, ';
        query += 'LastName, ';
        query += 'FirstName, ';
        query += 'Alias, ';
        query += 'Email, ';
        query += 'Username, ';
        query += 'CommunityNickname, ';
        query += 'IsActive, ';
        query += 'ContactId ';
        query += 'FROM User ';
        query += 'WHERE Contact.AccountId__c = \'';
        query += accountId;
        query += '\'';
        //クエリロケーターを利用し、最大5000万件までレコード参照可能とする
        System.debug('---DeletePersonalInfoUserMasking---');
        System.debug('start query: ' + query);
        return Database.getQueryLocator(query);
    }
    /**
    * @description 実行処理
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @param List<SObject> records 
    * @return void 
    **/
    public void execute(Database.BatchableContext BC, List<SObject> records) {
        //カスタム設定
        Masking__c masking = Masking__c.getOrgDefaults();
        for (SObject record : records) {
            User user = (User)record;
            //姓
            user.LastName = masking.LastName__c;
            //名
            user.FirstName = masking.FirstName__c;
            //別名
            user.Alias = masking.Alias__c;
            //メール
            user.Email = masking.Email__c;
            //ユーザ名
            user.Username = masking.Username__c;
            //ニックネーム
            user.CommunityNickname = masking.CommunityNickname__c;
            // //有効
            // user.IsActive = FALSE;
            // //取引先責任者
            // user.ContactId = NULL;
        }
        //ユーザUpdate
        Update records;

    }
    /**
    * @description 終了処理
    * @author h-nakata
    * @param Database.BatchableContext BC 
    * @return void 
    **/
    public void finish(Database.BatchableContext BC) {
        //カスタマーポータル取引先無効化
        String updateAccountId = this.accountId;
        List<Account> updateAccounts = [SELECT Id, IsCustomerPortal FROM Account WHERE AccountId__c = :updateAccountId AND IsCustomerPortal = TRUE];
        If(!updateAccounts.isEmpty()){
            for(Account updateAccount : updateAccounts){
                updateAccount.IsCustomerPortal = FALSE;
            }
            Update updateAccounts;
        }
        // カスタムメタデータ型：削除対象オブジェクト取得
        List<PersonalInfoDeleteTarget__mdt> deleteTargets = [
            SELECT SObjectApiName__c
            FROM PersonalInfoDeleteTarget__mdt
            WHERE IsActive__c = TRUE
        ];
        List<String> deleteTargetObjects = new List<String>();
        for(PersonalInfoDeleteTarget__mdt deleteTarget : deleteTargets){
            deleteTargetObjects.add(deleteTarget.SObjectApiName__c);
        }
        //個人情報削除バッチ
        String batchName = 'DeletePersonalInfoBatch';
        DeletePersonalInfoBatch batch = new DeletePersonalInfoBatch();
        batch.accountId = accountId;
        batch.deleteTargetObjects = deleteTargetObjects;
        batch.count = 0;
        //バッチサイズを取得
        Integer batchSize = ApexBatchUtils.getBatchSize(batchName);
        Database.executeBatch(batch, batchSize);
    }
}