force-app/main/default/objects/Account/fields/AccountGroupId__c.field-meta.xml
<CustomField>
    <fullName>AccountGroupId__c</fullName>
    <label>取引先グループID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BasicRank__c.field-meta.xml
<CustomField>
    <fullName>BasicRank__c</fullName>
    <label>基本ランク</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CapacityNum__c.field-meta.xml
<CustomField>
    <fullName>CapacityNum__c</fullName>
    <label>キャパ件数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChatterGroupName__c.field-meta.xml
<CustomField>
    <fullName>ChatterGroupName__c</fullName>
    <label>Chatterグループ名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsTokutokuService__c.field-meta.xml
<CustomField>
    <fullName>IsTokutokuService__c</fullName>
    <defaultValue>false</defaultValue>
    <label>得々サービス有無</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MainEmail__c.field-meta.xml
<CustomField>
    <fullName>MainEmail__c</fullName>
    <label>連絡先メール</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/NewMatterTeam__c.field-meta.xml
<CustomField>
    <fullName>NewMatterTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>斡旋/新規チーム</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipName>Account_cSectionRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NotificationMethod__c.field-meta.xml
<CustomField>
    <fullName>NotificationMethod__c</fullName>
    <label>自動通知方法</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>メール</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>FAX</fullName>
            </value>
            <value>
                <fullName>郵送</fullName>
            </value>
            <value>
                <fullName>メール+FAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>通知テンプレート</label>
    <referenceTo>NotificationTemplate__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNotificationTemplate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PriorityMediationContactMethod__c.field-meta.xml
<CustomField>
    <fullName>PriorityMediationContactMethod__c</fullName>
    <label>優先斡旋依頼書連絡方法</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>メール</fullName>
                <default>true</default>
                <label>メール</label>
            </value>
            <value>
                <fullName>FAX</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>メール+Chatter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RequestingNewCommodity__c.field-meta.xml
<CustomField>
    <fullName>RequestingNewCommodity__c</fullName>
    <label>依頼中件数(新商材)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/RequestingNum__c.field-meta.xml
<CustomField>
    <fullName>RequestingNum__c</fullName>
    <label>依頼中件数計算</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ServiceContractNewMatter__c.field-meta.xml
<CustomField>
    <fullName>ServiceContractNewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>サービス_新規</label>
    <referenceTo>ServiceContractNewMatter__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>ServiceContractNewMatterbDdw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/AgencyCapacity__c/AgencyCapacity__c.object-meta.xml
<CustomObject>
    <label>不動産キャパ</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>不動産キャパNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AgencyCapacity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>不動産キャパ</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgencyCapacity__c/fields/CapacityNum__c.field-meta.xml
<CustomField>
    <fullName>CapacityNum__c</fullName>
    <label>キャパ件数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgencyCapacity__c/fields/RequestingFmNum__c.field-meta.xml
<CustomField>
    <fullName>RequestingFmNum__c</fullName>
    <label>依頼中件数(基幹)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgencyCapacity__c/fields/RequestingNewCommodity__c.field-meta.xml
<CustomField>
    <fullName>RequestingNewCommodity__c</fullName>
    <label>新商材</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgencyCapacity__c/fields/RequestingNum__c.field-meta.xml
<CustomField>
    <fullName>RequestingNum__c</fullName>
    <label>依頼中件数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgencyCapacity__c/fields/ReserveNum__c.field-meta.xml
<CustomField>
    <fullName>ReserveNum__c</fullName>
    <formula>CapacityNum__c  -  RequestingNum__c  -  RequestingFmNum__c  -  RequestingNewCommodity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>余力</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>申請</relationshipLabel>
    <relationshipName>RequestAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CancelCalculateCheck__c/CancelCalculateCheck__c.object-meta.xml
<CustomObject>
    <label>解約精算チェック</label>
    <nameField>
        <label>解約精算チェック</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CancelCalculateCheck__c/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipLabel>解約精算チェック</relationshipLabel>
    <relationshipName>CorporateHousingRegulation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipLabel>取引先担当者</relationshipLabel>
    <relationshipName>CorporateHousingRegulation_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/CorporateHousingRegulation__c.object-meta.xml
<CustomObject>
    <label>社宅規定</label>
    <nameField>
        <label>社宅規定名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>社宅規定</relationshipLabel>
    <relationshipName>CorporateHousingRegulation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/SelectionCount__c.field-meta.xml
<CustomField>
    <fullName>SelectionCount__c</fullName>
    <label>選定数</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/SelectionRule__c.field-meta.xml
<CustomField>
    <fullName>SelectionRule__c</fullName>
    <label>不動産選定ルール</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/DesiredCondition__c/DesiredCondition__c.object-meta.xml
<CustomObject>
    <label>希望条件</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>希望条件NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DesiredCondition__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>希望条件</relationshipLabel>
    <relationshipName>DesiredTermsApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DesiredCondition__c/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>ServiceContractNewMatter__c</referenceTo>
    <relationshipLabel>希望条件</relationshipLabel>
    <relationshipName>DesiredConditionServiceContractNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <label>通知テンプレート</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>テンプレート一覧コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>通知テンプレート</relationshipLabel>
    <relationshipName>AccountNotificationTemplate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/MediationRequestMail__c.field-meta.xml
<CustomField>
    <fullName>MediationRequestMail__c</fullName>
    <label>斡旋依頼メールテンプレート</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContractNewMatter__c/ServiceContractNewMatter__c.object-meta.xml
<CustomObject>
    <label>サービス_新規</label>
    <nameField>
        <label>サービス契約_新規名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceContractNewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountServiceContractNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TraderSelectionSetting__c/TraderSelectionSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>斡旋不動産会社自動選定</label>
</CustomObject>

force-app/main/default/objects/TraderSelectionSetting__c/fields/RecordTypeNameTrader__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeNameTrader__c</fullName>
    <label>レコードタイプ名不動産会社</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TraderSelectionSetting__c/fields/SobjectTypeAccount__c.field-meta.xml
<CustomField>
    <fullName>SobjectTypeAccount__c</fullName>
    <label>オブジェクトタイプ取引先</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TraderSelectionModel.cls
/**
 * 斡旋業者選定画面のモデルクラス
 */
public class TraderSelectionModel {
    /**
     * @description 取引先担当者取得（単数）
     * @param contactId // 取引先担当者ID
     * @return `Contact`
     */
    public static Contact getContact(Id contactId) {
        system.debug(limits.getQueries());

        // 取引先担当者取得
        Contact result = ([
            SELECT 
                Id
                , CorporateHousingRegulation__c // 社宅規定
                , CorporateHousingRegulation__r.SelectionRule__c // 不動産選定ルール
                , CorporateHousingRegulation__r.SelectionCount__c // 選定数 
            FROM Contact
            WHERE Id = :contactId  
            LIMIT 1
        ]);
        return result;
    }
    
    
    
    /**
     * @description 本店を取得
     * @author t-sato
     * @param requestTraders 
     * @param tsSetting 
     * @return  `Map<String,Account>`
     */
    //通知
    public static Map<String,Account> getAccountSendMediationRequest(
        Map<Id,Account> requestTraders,
        TraderSelectionSetting__c tsSetting
    ){
        Map<String,Account> result =  new Map<String,Account>();

        //グループIDをリストで取得
        List<String> GroupIds = new List<String>();
        for(Id id : requestTraders.keySet()){
            GroupIds.add(requestTraders.get(id).AccountGroupId__c);//TODO 取引先グループIDを格納
        }

        // レコードタイプ（不動産会社/家主）取得
        RecordType recordType = [
            SELECT Id, Name, DeveloperName, SobjectType, IsActive
            FROM RecordType
            WHERE SobjectType = :tsSetting.SobjectTypeAccount__c
                AND Name = :tsSetting.RecordTypeNameTrader__c 
                AND IsActive = true
            LIMIT 1
        ];

        // 取引先（不動産会社）取得
        Map<Id, Account> accounts = new Map<Id, Account>([
            SELECT 
                Id
                , Name
                , BasicRank__c // 基本ランク
                , IsTokutokuService__c // 得々サービス有無
                , MainEmail__c // メール
                , NotificationMethod__c // 自動通知方法
                , ChatterGroupName__c //Chatterグループ名
                , NotificationTemplate__r.MediationRequestMail__c // メールテンプレート
                , NewMatterTeam__r.OwnerId//新規/斡旋チーム キューグループ
                , PriorityMediationContactMethod__c//優先斡旋依頼書連絡方法
            FROM Account
            WHERE 
                Id IN :GroupIds
                AND Name != null
                AND RecordTypeId = :recordType.Id
        ]);

        for(Id id : accounts.keySet()){
            Account account = accounts.get(id);
            String groupId = account.Name;
            result.put(groupId,account);
        }

        return result;
    }
    /**
     * @description 社宅規定を取得
     * @param newMatterId // 新規Id
     * @return DesiredCondition__c
     */
    public static CorporateHousingRegulation__c getCorporateHousingRegulation(
        Id accountId
    ){
        CorporateHousingRegulation__c result = [
            SELECT 
                Id, 
                SelectionCount__c //選定数
            FROM CorporateHousingRegulation__c
            WHERE
                Account__c = :accountId
            LIMIT 1
        ];
        return result;
    }

    /**
     * @description 不動産キャパ取得
     * @param accountIds // 取引先ID
     * @return `Map<Id, AgencyCapacity__c>`
     */
    //手動　斡旋
    public static Map<Id, AgencyCapacity__c> getAgencyCapacityToAccountId(
        Set<Id> accountIds) {

        // 返却マップ 
        Map<Id, AgencyCapacity__c> agencyCapacitys = 
            new Map<Id, AgencyCapacity__c>();

        // 引数が空の場合は処理終了
        if(accountIds.isEmpty()){
            return agencyCapacitys;
        }

        for (AgencyCapacity__c agencyCapacity : [
            SELECT 
                Id
                , Account__c // 取引先
                , CapacityNum__c // キャパ件数
                , ReserveNum__c // 依頼中件数
                , RequestingFmNum__c // 依頼中件数(基幹)
                , RequestingNum__c // 新商材
                , RequestingNewCommodity__c // 余力
            FROM AgencyCapacity__c
            WHERE Account__c IN :accountIds
        ]) {

            if(String.isNotBlank(agencyCapacity.Account__c)){
                agencyCapacitys.put(
                    agencyCapacity.Account__c, agencyCapacity);
            }
        }
      
        return agencyCapacitys;
    }

    /**
     * @description 希望条件を取得
     * @param newMatterId // 新規Id
     * @return `DesiredCondition__c`
     */
    //TODO両方
    public static DesiredCondition__c getDesiredCondition(Id applicationId) {
        System.debug('DesiredCondition__c:'+applicationId);

        // 希望条件を取得      
        DesiredCondition__c result = new DesiredCondition__c();
        result = [
            SELECT 
                Id ,Application__c
            FROM DesiredCondition__c
            WHERE Application__c = :applicationId
            LIMIT 1
        ];
        return result;
    }

    /**
     * @description 取引先の取得
     * @param accountIds // 取引先IDリスト
     * @return `Map<Id, Account>`
     */
    public static Account getAccount(
        Id accountId) {

        Account result = new Account();

        // 引数が空の場合は処理終了
        if(accountId == null){
            return result;
        }
        result = [
            SELECT 
                Id
                , ServiceContractNewMatter__c // サービス_新規
                , ServiceContractNewMatter__r.IsAutoMediationRequest__c // 斡旋自動対応不可フラグ
            FROM Account
            WHERE Id = :accountId
            ];
        return result;
    }

     /**
     * @description 取引先(不動産)の取得
     * @param accountIds // 取引先IDリスト
     * @return `Map<Id, Account>`
     */
    public static Account getTrader(
        Id accountId) {

        Account result = new Account();

        // 引数が空の場合は処理終了
        if(accountId == null){
            return result;
        }
        result = [
            SELECT 
                Id
                , Name
                , IsTokutokuService__c // 得々サービス
                , BasicRank__c //基本ランク
                , ParticipatingStore__r.Name //加盟店名
            FROM Account
            WHERE Id = :accountId
            ];
        return result;
    }

     

     /**
     * @description 休日有無取得
     * @author sato-takumi
     * @param  emailTemplateNames //メールテンプレート名
     * @return Boolean
     */
    //手動
    public static Boolean getHolidayToday() {
        //返却値
        Boolean result = True;

        //取得結果を返却マップに格納
        for(Holiday holiday: [
            SELECT ActivityDate
            FROM Holiday
            WHERE ActivityDate = :Date.today()
            ])result = False;
        
        return result;
    }

    public static Map<Id,NotificationTemplate__c> getNotificationTemplates(
        Set<Id> AccountIds
        ){
            Map<Id,NotificationTemplate__c> result = new Map<Id,NotificationTemplate__c>();
            //取得結果を返却マップに格納
            for(NotificationTemplate__c notificationTemplate: [
                SELECT 
                Id,
                MediationRequestMail__c
                FROM NotificationTemplate__c
                WHERE Account__c IN :AccountIds 
            ])result.put(notificationTemplate.Id,notificationTemplate);
            return result;

    }

    
}