force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <externalId>true</externalId>
    <label>取引先ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/NewMatterTeam__c.field-meta.xml
<CustomField>
    <fullName>NewMatterTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>斡旋/新規チーム</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipName>Account_cSectionRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>申請</relationshipLabel>
    <relationshipName>RequestAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/ApplicantCode__c.field-meta.xml
<CustomField>
    <fullName>ApplicantCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社員</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>申請 (社員)</relationshipLabel>
    <relationshipName>RequestContactRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>承認ステップ</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>申請待ち</fullName>
            </value>
            <value>
                <fullName>確認中</fullName>
            </value>
            <value>
                <fullName>受付済み</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>申請種別</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>入居申請</fullName>
            </value>
            <value>
                <fullName>退去申請</fullName>
            </value>
            <value>
                <fullName>転居申請</fullName>
            </value>
            <value>
                <fullName>駐車場利用申請</fullName>
            </value>
            <value>
                <fullName>駐車場利用停止申請</fullName>
            </value>
            <value>
                <fullName>駐車場借換申請</fullName>
            </value>
            <value>
                <fullName>その他申請</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>Account.AccountId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>取引先ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>新規 (委託企業)</relationshipLabel>
    <relationshipName>Account_NewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/ProjectImportantMatter__c.field-meta.xml
<CustomField>
    <fullName>ProjectImportantMatter__c</fullName>
    <label>案件重要事項</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>申請待ち</fullName>
                <default>true</default>
                <label>申請待ち</label>
            </value>
            <value>
                <fullName>申請確認中</fullName>
            </value>
            <value>
                <fullName>選定中</fullName>
            </value>
            <value>
                <fullName>書類準備中</fullName>
            </value>
            <value>
                <fullName>契約条件確認中</fullName>
            </value>
            <value>
                <fullName>申請中</fullName>
            </value>
            <value>
                <fullName>締結中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>決裁申請中</fullName>
            </value>
            <value>
                <fullName>作業中</fullName>
                <isActive>false</isActive>
                <label>作業中</label>
            </value>
            <value>
                <fullName>再査中</fullName>
                <isActive>false</isActive>
                <label>再査中</label>
            </value>
            <value>
                <fullName>契約内容確認中</fullName>
                <isActive>false</isActive>
                <label>契約内容確認中</label>
            </value>
            <value>
                <fullName>契約書原本保管</fullName>
                <isActive>false</isActive>
                <label>契約書原本保管</label>
            </value>
            <value>
                <fullName>承認連絡準備中</fullName>
                <isActive>false</isActive>
                <label>承認連絡準備中</label>
            </value>
            <value>
                <fullName>新規</fullName>
                <isActive>false</isActive>
                <label>新規</label>
            </value>
            <value>
                <fullName>書類到着待ち</fullName>
                <isActive>false</isActive>
                <label>書類到着待ち</label>
            </value>
            <value>
                <fullName>書類締結中</fullName>
                <isActive>false</isActive>
                <label>書類締結中</label>
            </value>
            <value>
                <fullName>条件確認中</fullName>
                <isActive>false</isActive>
                <label>条件確認中</label>
            </value>
            <value>
                <fullName>物件決定待ち</fullName>
                <isActive>false</isActive>
                <label>物件決定待ち</label>
            </value>
            <value>
                <fullName>申請受付</fullName>
                <isActive>false</isActive>
                <label>申請受付</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PhaseGate__c/PhaseGate__c.object-meta.xml
<CustomObject>
    <label>フェーズゲート</label>
    <nameField>
        <displayFormat>PhaseGate-{0000}</displayFormat>
        <label>フェーズゲート名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PhaseGate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>フェーズゲート</relationshipLabel>
    <relationshipName>PhaseGate7BO6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/AfterStageMandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>AfterStageMandatoryFieldsErrorMessage__c</fullName>
    <label>後フェーズ必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>この項目には項目のAPI名を記述してください。</inlineHelpText>
    <label>チェック項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/MandatoryFieldsErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>MandatoryFieldsErrorMessage__c</fullName>
    <label>必須項目エラーメッセージ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>業務</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewMatter__c</fullName>
                <default>true</default>
                <label>新規</label>
            </value>
            <value>
                <fullName>Cancel__c</fullName>
                <label>解約申入</label>
            </value>
            <value>
                <fullName>CancelCalculate__c</fullName>
                <label>解約精算</label>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
                <label>更新</label>
            </value>
            <value>
                <fullName>ConditionChange__c</fullName>
                <label>条件変更</label>
            </value>
            <value>
                <fullName>Case</fullName>
                <label>ケース</label>
            </value>
            <value>
                <fullName>Change__c</fullName>
                <label>入替</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>フェーズ</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>ステップ</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PhaseGate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>種別</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>必須項目</fullName>
            </value>
            <value>
                <fullName>表示メッセージ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>セクション</label>
    <nameField>
        <label>セクション名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <externalId>true</externalId>
    <label>セクションID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/SystemUserId__c.field-meta.xml
<CustomField>
    <fullName>SystemUserId__c</fullName>
    <label>システムユーザId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhaseGateCreateNewMatterTestData.cls
public class PhaseGateCreateNewMatterTestData{
    public static List<NewMatter__c> createData(){
         //セクションを作成
        Section__c section = new Section__c(
            Name = '新規チーム', //セクション名
            SectionId__c = '12' //セクションID
        );
        insert section;

        //取引先を作成
        List<Account> accountList= new List<Account>();
        // レコードタイプ（委託企業）取得
        RecordType recordTypeCompany = [
            SELECT Id
            FROM RecordType
            WHERE 
                SobjectType = 'Account' 
                AND Name = '委託企業' 
                AND IsActive = true
            LIMIT 1
        ];
        Account account1 = new Account(
            RecordTypeId = recordTypeCompany.id,//レコードタイプ
            AccountId__c = '111222333', //取引先ID
            Name = 'フェーズゲートテスト取引先1',//取引先名
            NewMatterTeam__c = section.id //斡旋/新規チーム
        );
        accountList.add(account1);

        Account account2 = new Account(
            RecordTypeId = recordTypeCompany.id,//レコードタイプ
            AccountId__c = '222333444', //取引先ID
            Name = 'フェーズゲートテスト取引先2',//取引先名
            NewMatterTeam__c = section.id //斡旋/新規チーム
        );
        accountList.add(account2);

        insert accountList;

        //取引先担当者を作成
        List<Contact> contactList = new List<Contact>();

        Contact contact1 = new Contact(
            LastName = 'フェーゲート取引先担当者1',//名前
            AccountId = account1.id //取引先ID
        );
        contactList.add(contact1);

        Contact contact2 = new Contact(
            LastName = 'フェーゲート取引先担当者2',//名前
            AccountId = account2.id //取引先ID
        );
        contactList.add(contact2);

        insert contactList;

        //申請レコードを作成
        List<Application__c> applicationList = new List<Application__c>();
        Application__c application1 = new Application__c(
            Account__c = account1.id,//申請
            ApplicantCode__c = contact1.id
        );
        applicationList.add(application1);

        Application__c application2 = new Application__c(
            Account__c = account2.id,//申請
            ApplicantCode__c = contact2.id
        );
        applicationList.add(application2);

        insert applicationList;

        //フェーズゲートレコードを作成
        List<PhaseGate__c> phaseGateList = new List<PhaseGate__c>();
        PhaseGate__c phaseGate1 = new PhaseGate__c(
            Operation__c = 'NewMatter__c',
            Stage__c = '申請',
            Step__c = 1,
            Type__c = '必須項目',
            Field__c = 'ProjectImportantMatter__c',
            MandatoryFieldsErrorMessage__c = '必須項目です。入力してください。',
            AfterStageMandatoryFieldsErrorMessage__c =  '後フェーズでの必須項目です。入力しないでください。'
        );
        phaseGateList.add(phaseGate1);

        PhaseGate__c phaseGate2 = new PhaseGate__c(
            Operation__c = 'NewMatter__c',
            Stage__c = '申請確認中',
            Step__c = 2,
            Type__c = '必須項目',
            Field__c = 'ConfirmContent__c',
            MandatoryFieldsErrorMessage__c = '必須項目です。入力してください。',
            AfterStageMandatoryFieldsErrorMessage__c =  '後フェーズでの必須項目です。入力しないでください。'
        );
        phaseGateList.add(phaseGate2);

        insert phaseGateList;

        //新規レコードを作成
        List<NewMatter__c> newMatterList = new List<NewMatter__c>();
        NewMatter__c newMatter1 = new NewMatter__c(
            Stage__c = '申請',
            Application__c = application1.id,//申請
            Account__c = account1.id//取引先
           
        );
        newMatterList.add(newMatter1);

        NewMatter__c newMatter2 = new NewMatter__c(
            Stage__c = '申請',
            Application__c = application2.id,//申請
            Account__c = account2.id ,//取引先
            ProjectImportantMatter__c = 'a'
        );
        newMatterList.add(newMatter2);

        NewMatter__c newMatter3 = new NewMatter__c(
            Stage__c = '申請',
            Application__c = application2.id,//申請
            Account__c = account2.id ,//取引先
            ConfirmContent__c = 'a'
        );
        newMatterList.add(newMatter3);

        insert newMatterList;
        return newMatterList;
    }

     /**
     * @Description カスタム設定を作成
     */
    private static SyatakusanSetting__c createCustomSetting(){
        SyatakusanSetting__c customSetting = new SyatakusanSetting__c();
        customSetting.SystemUserId__c = '005O0000007fyxo';

        insert customSetting;
        return customSetting;
    }
}