force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <externalId>true</externalId>
    <label>取引先ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>契約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NotificationMethod__c.field-meta.xml
<CustomField>
    <fullName>NotificationMethod__c</fullName>
    <label>自動通知方法</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>メール</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>FAX</fullName>
            </value>
            <value>
                <fullName>郵送</fullName>
            </value>
            <value>
                <fullName>メール+FAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PriorityMediationContactMethod__c.field-meta.xml
<CustomField>
    <fullName>PriorityMediationContactMethod__c</fullName>
    <label>優先斡旋依頼書連絡方法</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>メール</fullName>
                <default>true</default>
                <label>メール</label>
            </value>
            <value>
                <fullName>FAX</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>メール+Chatter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ServiceContractNewMatter__c.field-meta.xml
<CustomField>
    <fullName>ServiceContractNewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>サービス_新規</label>
    <referenceTo>ServiceContractNewMatter__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>ServiceContractNewMatterbDdw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>申請</relationshipLabel>
    <relationshipName>RequestAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/ApplicantCode__c.field-meta.xml
<CustomField>
    <fullName>ApplicantCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社員</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>申請 (社員)</relationshipLabel>
    <relationshipName>RequestContactRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/ApplicantCodeText__c.field-meta.xml
<CustomField>
    <fullName>ApplicantCodeText__c</fullName>
    <label>申請者社員コード</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/CompanyIdText__c.field-meta.xml
<CustomField>
    <fullName>CompanyIdText__c</fullName>
    <externalId>true</externalId>
    <label>企業ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋依頼</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Delete.recordType-meta.xml
<RecordType>
    <fullName>Delete</fullName>
    <active>true</active>
    <label>削除申請</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>Account.AccountId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>取引先ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipLabel>取引先担当者</relationshipLabel>
    <relationshipName>CorporateHousingRegulation_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmployeeNum__c.field-meta.xml
<CustomField>
    <fullName>EmployeeNum__c</fullName>
    <externalId>true</externalId>
    <label>社員番号</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/CorporateHousingRegulation__c.object-meta.xml
<CustomObject>
    <label>社宅規定</label>
    <nameField>
        <label>社宅規定名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>社宅規定</relationshipLabel>
    <relationshipName>CorporateHousingRegulation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/SelectionCount__c.field-meta.xml
<CustomField>
    <fullName>SelectionCount__c</fullName>
    <label>選定数</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CorporateHousingRegulation__c/fields/SelectionRule__c.field-meta.xml
<CustomField>
    <fullName>SelectionRule__c</fullName>
    <label>不動産選定ルール</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>成約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>依頼前</fullName>
                <default>true</default>
                <label>依頼前</label>
            </value>
            <value>
                <fullName>依頼中</fullName>
            </value>
            <value>
                <fullName>成約</fullName>
            </value>
            <value>
                <fullName>他決</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipName>MediationRegulationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約手続き</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>斡旋依頼 (新規No)</relationshipLabel>
    <relationshipName>MediationRequestIdNewMatterRelation10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>新規 (委託企業)</relationshipLabel>
    <relationshipName>Account_NewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/CorporateHousingRegulation__c.field-meta.xml
<CustomField>
    <fullName>CorporateHousingRegulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社宅規定</label>
    <referenceTo>CorporateHousingRegulation__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>CorporateHousingRegulationNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <label>新規ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/ServiceContractNewMatter__c.field-meta.xml
<CustomField>
    <fullName>ServiceContractNewMatter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業ルール</label>
    <referenceTo>ServiceContractNewMatter__c</referenceTo>
    <relationshipLabel>新規</relationshipLabel>
    <relationshipName>ServiceContractNewMatter_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContractNewMatter__c/ServiceContractNewMatter__c.object-meta.xml
<CustomObject>
    <label>サービス_新規</label>
    <nameField>
        <label>サービス契約_新規名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceContractNewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountServiceContractNewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContractNewMatter__c/fields/IsAutoCreateRecord__c.field-meta.xml
<CustomField>
    <fullName>IsAutoCreateRecord__c</fullName>
    <defaultValue>true</defaultValue>
    <label>コード自動作成対象</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceContractNewMatter__c/fields/IsAutoMediationRequest__c.field-meta.xml
<CustomField>
    <fullName>IsAutoMediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋自動対応不可フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RequestTraderDataFactory.cls
@isTest
public with sharing class RequestTraderDataFactory {
    public static Application__c application = new Application__c(); 
    public static NewMatter__c  newMatter = new NewMatter__c();
    public static List<Account> rquestTraders = new List<Account>();
    public static Account account = new Account();
    public static Contact resident = new Contact();


    public static void createRequestTraders(Id NewMatterId) {
        delete [SELECT ID FROM MediationRequest__c];
        Account account1 = new Account(
            Name = 'テスト（不動産会社）_101',
            AccountId__c = '92200001b',
            PriorityMediationContactMethod__c = 'メール'
        );
        Account account2 = new Account(
            Name = 'テスト（不動産会社）_102',
            AccountId__c = '92200002b',
            PriorityMediationContactMethod__c = 'Chatter'
        );
        Account account3 = new Account(
            Name = 'テスト（不動産会社）_103',
            AccountId__c = '92200003b',
            PriorityMediationContactMethod__c = 'FAX'
        );

        List<Account> createAccounts = new List<Account>();
        createAccounts.add(account1);
        createAccounts.add(account2);
        createAccounts.add(account3);
        insert createAccounts;

        List<MediationRequest__c> mediationRequests = new List<MediationRequest__c>();
        MediationRequest__c mediationRequest1 = new MediationRequest__c(
            RequestTraderId__c = account1.Id, // 依頼業者名
            NewMatterId__c = NewMatterId, // 新規ＩＤ
            ContractCategory__c = '依頼前' // 成約区分
        );
        MediationRequest__c mediationRequest2 = new MediationRequest__c(
            RequestTraderId__c = account2.Id, // 依頼業者名
            NewMatterId__c = NewMatterId, // 新規ＩＤ
            ContractCategory__c = '依頼前' // 成約区分
        );
        MediationRequest__c mediationRequest3 = new MediationRequest__c(
            RequestTraderId__c = account3.Id, // 依頼業者名
            NewMatterId__c = NewMatterId, // 新規ＩＤ
            ContractCategory__c = '依頼前' // 成約区分
        );
        mediationRequests.add(mediationRequest1);
        mediationRequests.add(mediationRequest2);
        mediationRequests.add(mediationRequest3);
        insert mediationRequests;
        rquestTraders = createAccounts;
    }

    public static void createAccountData(){
        // レコードタイプ（委託企業）取得
        RecordType recordTypeCompany = [
            SELECT Id
            FROM RecordType
            WHERE SobjectType = 'Account' 
                AND Name = '委託企業' AND IsActive = true
            LIMIT 1
        ];

        //サービス新規
        ServiceContractNewMatter__c serviceContractNewMatter = new ServiceContractNewMatter__c(
            IsAutoCreateRecord__c = false,
            IsAutoMediationRequest__c = false
        );
        insert serviceContractNewMatter;


        Account createAccount = new Account(
            Name = 'テスト（企業）_001',
            AccountId__c = '91000001c',
            RecordTypeId = recordTypeCompany.Id,
            NotificationMethod__c = 'メール',
            ServiceContractNewMatter__c = serviceContractNewMatter.Id
        );
        insert createAccount;
        account = createAccount;

        CorporateHousingRegulation__c cR_1 = new CorporateHousingRegulation__c(
                Name = 'テスト（社宅規定）_001',
                Account__c = createAccount.Id,
                SelectionRule__c = '<p><span>XXXXXXXXXXXX</span></p>',
                SelectionCount__c = 4
            );

        Contact contact = new Contact(
            EmployeeNum__c = '400011',
            LastName = 'TESTCLASS（取引先担当者）_1001',
            AccountId = createAccount.Id,
            CorporateHousingRegulation__c = cR_1.Id,
            Email = 'ml-snt-sfdc@virtualex.co.jp'
        );
        resident = contact;
        
    }

    public static void createApplicationData(){
        Application__c createApplication = new Application__c(
            CompanyIdText__c = account.AccountId__c,
            ApplicantCodeText__c = resident.EmployeeNum__c,
            Account__c = account.Id,
            ApplicantCode__c = resident.Id,
            MediationRequest__c = false,
            DesiredAreaState__c = '神奈川県',
            DesiredAreaCity__c = null
        );
        insert createApplication;
        application = createApplication;
    }
}