force-app/main/default/objects/Account/fields/ChatterGroupName__c.field-meta.xml
<CustomField>
    <fullName>ChatterGroupName__c</fullName>
    <label>Chatterグループ名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>契約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>申請</relationshipLabel>
    <relationshipName>RequestAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/ApplicantCode__c.field-meta.xml
<CustomField>
    <fullName>ApplicantCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社員</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>申請 (社員)</relationshipLabel>
    <relationshipName>RequestContactRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DesiredAgency__c.field-meta.xml
<CustomField>
    <fullName>DesiredAgency__c</fullName>
    <label>希望不動産会社</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/EmployeeComment__c.field-meta.xml
<CustomField>
    <fullName>EmployeeComment__c</fullName>
    <label>社員コメント</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>エラーメッセージ</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋依頼</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/ToSNTComment__c.field-meta.xml
<CustomField>
    <fullName>ToSNTComment__c</fullName>
    <label>SNT連絡事項</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Delete.recordType-meta.xml
<RecordType>
    <fullName>Delete</fullName>
    <active>true</active>
    <label>削除申請</label>
</RecordType>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>地区</label>
    <nameField>
        <label>地区名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区郡</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/District__c/fields/IsAllCity__c.field-meta.xml
<CustomField>
    <fullName>IsAllCity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>都道府県全域</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>都道府県</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>北海道</fullName>
            </value>
            <value>
                <fullName>青森県</fullName>
            </value>
            <value>
                <fullName>岩手県</fullName>
            </value>
            <value>
                <fullName>宮城県</fullName>
            </value>
            <value>
                <fullName>秋田県</fullName>
            </value>
            <value>
                <fullName>山形県</fullName>
            </value>
            <value>
                <fullName>福島県</fullName>
            </value>
            <value>
                <fullName>茨城県</fullName>
            </value>
            <value>
                <fullName>栃木県</fullName>
            </value>
            <value>
                <fullName>群馬県</fullName>
            </value>
            <value>
                <fullName>埼玉県</fullName>
            </value>
            <value>
                <fullName>千葉県</fullName>
            </value>
            <value>
                <fullName>東京都</fullName>
            </value>
            <value>
                <fullName>神奈川県</fullName>
            </value>
            <value>
                <fullName>新潟県</fullName>
            </value>
            <value>
                <fullName>富山県</fullName>
            </value>
            <value>
                <fullName>石川県</fullName>
            </value>
            <value>
                <fullName>福井県</fullName>
            </value>
            <value>
                <fullName>山梨県</fullName>
            </value>
            <value>
                <fullName>長野県</fullName>
            </value>
            <value>
                <fullName>岐阜県</fullName>
            </value>
            <value>
                <fullName>静岡県</fullName>
            </value>
            <value>
                <fullName>愛知県</fullName>
            </value>
            <value>
                <fullName>三重県</fullName>
            </value>
            <value>
                <fullName>滋賀県</fullName>
            </value>
            <value>
                <fullName>京都府</fullName>
            </value>
            <value>
                <fullName>大阪府</fullName>
            </value>
            <value>
                <fullName>兵庫県</fullName>
            </value>
            <value>
                <fullName>奈良県</fullName>
            </value>
            <value>
                <fullName>和歌山県</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/District__c/fields/StateSortOrder__c.field-meta.xml
<CustomField>
    <fullName>StateSortOrder__c</fullName>
    <label>都道府県並び順</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MediationPossibleArea__c/MediationPossibleArea__c.object-meta.xml
<CustomObject>
    <label>紹介可能エリア</label>
    <nameField>
        <label>紹介可能エリア名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationPossibleArea__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>紹介可能エリア</relationshipLabel>
    <relationshipName>MediationPossibleArea</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationPossibleArea__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>District__r.City__c</formula>
    <label>市区町村</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MediationPossibleArea__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>地区</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>紹介可能エリア</relationshipLabel>
    <relationshipName>District</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>AccountName__r.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>市区</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>成約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>依頼前</fullName>
                <default>true</default>
                <label>依頼前</label>
            </value>
            <value>
                <fullName>依頼中</fullName>
            </value>
            <value>
                <fullName>成約</fullName>
            </value>
            <value>
                <fullName>他決</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/MediationInputDate__c.field-meta.xml
<CustomField>
    <fullName>MediationInputDate__c</fullName>
    <label>斡旋入力日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約手続き</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>斡旋依頼 (新規No)</relationshipLabel>
    <relationshipName>MediationRequestIdNewMatterRelation10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>AccountName__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>都道府県</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>新規 (委託企業)</relationshipLabel>
    <relationshipName>Account_NewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/MediationRequestDate__c.field-meta.xml
<CustomField>
    <fullName>MediationRequestDate__c</fullName>
    <label>斡旋依頼日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <label>新規ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>都道府県</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <label>通知テンプレート</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>テンプレート一覧コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>通知テンプレート</relationshipLabel>
    <relationshipName>AccountNotificationTemplate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ManualTraderSelectionModel.cls
public class ManualTraderSelectionModel{

    /**
     * @description 新規情報取得（単数）
     * @param newMatterId // 新規ID
     * @return `NewMatter__c`
     */
    //TODO手動
    public static NewMatter__c getNewMatter(String newMatterId) {

        // 新規取得
        return [
            SELECT 
                Id
                , Name
                , Application__c // 申請
                , Application__r.ErrorMessage__c//エラーメッセージ	
                , Application__r.Account__c // 取引先
                , Application__r.MediationRequest__c // 斡旋依頼
                , Application__r.ApplicantCode__c // 申請者社員コード
                , Application__r.DesiredAgency__c // 希望不動産会社
                , Application__r.EmployeeComment__c // 社員コメント
                , Application__r.ToSNTComment__c // SNT宛コメント
                , MediationRequestDate__c //斡旋依頼日	
            FROM NewMatter__c
            WHERE Id = :newMatterId
            LIMIT 1
        ];
    }

     /**
     * @description 都道府県情報取得
     * @return `List<District__c>`
     */
    //TODO手動
    public static List<District__c> getDistrictStates() {

        // 都道府県情報取得（都道府県並び順で取得）
        return [
            SELECT Id, State__c
            FROM District__c
            WHERE IsAllCity__c = true
            ORDER BY StateSortOrder__c
        ];
    }


    public static Map<Id , Account> getAccounts(set<Id> newMatterIds,TraderSelectionSetting__c tsSetting){
        Map<Id , Account> result = new Map<Id , Account>();
        return result;
    }

    /**
     * @description 斡旋依頼取得（新規ID、取引先（不動産会社）ID検索）
     * @param newMatterId // 新規ID
     * @param accountIds // 取引先ID
     * @return `List<MediationRequest__c>`
     */
    //TODO手動
    public static List<MediationRequest__c> getMediationRequestRegistereds(
        Id newMatterId) {

        // 登録済みの斡旋依頼を取得
        try{
        List<MediationRequest__c> result = [
            SELECT 
                Id 
                , MediationInputDate__c
                , ContractCategory__c
                , RequestTraderId__c
                , RequestTraderId__r.Name
            FROM MediationRequest__c
            WHERE NewMatterId__c = :newMatterId 
                AND ContractCategory__c != '成約'
        ];
        return result;
        } catch (AuraHandledException e) {
            return null;
        }   
        
    }
    
    /**
     * @description 斡旋依頼取得（斡旋依頼ID検索）
     * @param mediationRequestIds // 斡旋依頼IDリスト
     * @return `List<MediationRequest__c>`
     */
    public static List<MediationRequest__c> getMediationRequestRequestId(
        Set<Id> mediationRequestIds) {

        // 斡旋依頼を取得    
        return [
            SELECT 
                Id,
                Name,
                ContractCategory__c, 
                RequestTraderId__c,//依頼業者
                RequestTraderId__r.ChatterGroupName__c,//依頼業者.Chatterグループ名
                RequestTraderId__r.NotificationTemplate__r.MediationRequestFeed__c,//依頼業者.通知テンプレート.斡旋依頼テンプレート名
                RequestTraderId__r.NotificationTemplate__r.MediationRequestReportNum__c,//斡旋依頼業者_帳票番号
                RequestTraderId__r.PriorityMediationContactMethod__c//依頼業者.優先斡旋依頼書連絡方法
            
            FROM MediationRequest__c
            WHERE Id IN :mediationRequestIds
        ];
    }
    
    

    /**
     * @description 都道府県、市区郡から紹介可能エリア
     * @param state // 取引先ID
     * @param city // 取引先ID
     * @return `Set<Id>`
     */
    //手動
    public static Set<Id> getAccountIdStateMediationPossibleArea(
        String state, String city) {

        Set<Id> mpAreaAccountId = new Set<Id>();

        if(String.isBlank(state)){
            return mpAreaAccountId;
        }

        // 対応可能エリア検索SQL文
        String selectQuery = '';
        selectQuery += 'SELECT ';
        selectQuery += 'Id, ';
        selectQuery += 'Name, ';
        selectQuery += 'Account__c ';
        selectQuery += 'FROM ';
        selectQuery += 'MediationPossibleArea__c ';

        // WHERE句
        List<String> wheres = new List<String>();

        if(String.isNotBlank(state)){
            wheres.add('State__c = :state');
        }
        if(String.isNotBlank(city)){
            wheres.add('City__c = :city');
        }
        if (!wheres.isEmpty()) {
            selectQuery += 'WHERE ';
            selectQuery += String.join(wheres, ' AND ');
        }

        // 検索SQL実行
        List<MediationPossibleArea__c> mpAreas = Database.query(selectQuery);

        if(!mpAreas.isEmpty()){
            for (MediationPossibleArea__c mpArea : mpAreas){
                mpAreaAccountId.add(mpArea.Account__c);
            }
        }
      
        return mpAreaAccountId;
    }


     /**
     * @description 斡旋依頼取得（登録済み）
     * @param newMatterId // 新規ID
     * @param accountId // 取引先ID
     * @return `List<MediationRequest__c>`
     */
    public static List<MediationRequest__c> getMediationRequestDelete(
        String newMatterId, String accountId) {

        // 登録済みの斡旋依頼を取得    
        return [
            SELECT 
                Id
            FROM MediationRequest__c
            WHERE NewMatterId__c = :newMatterId 
                AND RequestTraderId__c = :accountId
        ];
    }

     /**
     * @description 画面入力内容から取引先（不動産会社）検索
     * @param accountId // 取引先ID
     * @param accountName // 取引先名
     * @param state // 都道府県
     * @param city // 市区郡
     * @param mpAreaAccountId // 紹介可能エリアの取引先ID
     * @return `Map<Id, Account>`
     */
    //TODO手動
    public static Map<Id, Account> getAccountInput(
        String accountId, String accountName,
        String state, String city, Set<Id> mpAreaAccountId,
        TraderSelectionSetting__c tsSetting
        ) {

        // レコードタイプ（不動産会社/家主）取得
        RecordType recordType = [
            SELECT Id, Name, DeveloperName, SobjectType, IsActive
            FROM RecordType
            WHERE SobjectType = :tsSetting.SobjectTypeAccount__c 
                AND Name = :tsSetting.RecordTypeNameTrader__c 
                AND IsActive = true
            LIMIT 1
        ];
        String recordTypeId = recordType.Id;

        // 取引先（不動産会社）検索SQL文
        String selectQuery = '';
        selectQuery += 'SELECT ';
        selectQuery += 'Id, ';
        selectQuery += 'Name, ';
        selectQuery += 'BasicRank__c, ';
        selectQuery += 'ParticipatingStore__r.Name, ';
        selectQuery += 'IsTokutokuService__c ';
        selectQuery += 'FROM ';
        selectQuery += 'Account ';

        // WHERE句
        List<String> wheres = new List<String>();
        wheres.add('RecordTypeId = :recordTypeId');

        if(String.isNotBlank(accountId)){
            wheres.add('Id = :accountId');
        }
        if(String.isNotBlank(accountName)){
            wheres.add('Name LIKE ' + '\'%'+ accountName + '%\'');
        }
        if(String.isNotBlank(state) && !mpAreaAccountId.isEmpty()){
            wheres.add('Id IN :mpAreaAccountId');
        }
        if (!wheres.isEmpty()) {
            selectQuery += 'WHERE ';
            selectQuery += String.join(wheres, ' AND ');
        }

        // 検索SQL実行
        List<Account> accounts = Database.query(selectQuery);
        return new Map<Id, Account>(accounts);
    }

    /**
     * @description 市区郡取得
     * @param stateName // 都道府県ID
     * @return `List<District__c>`
     */
    //TODO手動(画面)
    public static List<District__c> getDistrictCitys(String stateName) {

        // 市区郡取得（市区群並び順で取得）
        return [
            SELECT Id, City__c
            FROM District__c
            WHERE State__c = :stateName AND IsAllCity__c = false 
            ORDER BY CitySortOrder__c
        ];
    }

    /**
     * @description 斡旋依頼を登録／更新
     * @param mediationRequests // 斡旋依頼リスト
     * @return `void`
     */
    //手動(画面でも使われている)
    public static void upsertMediationRequest(
        List<MediationRequest__c> mediationRequests) {

        try {

            if (!mediationRequests.isEmpty()) {
                upsert mediationRequests;
            }

        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

    /**
     * @description 斡旋依頼を更新
     * @param mediationRequests // 斡旋依頼リスト
     * @return `void`
     */
    //手動
    public static void updateMediationRequest(
        List<MediationRequest__c> mediationRequests) {

        try {

            if (!mediationRequests.isEmpty()) {
                update mediationRequests;
            }

        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }


    /**
     * @description 斡旋依頼を削除
     * @param mediationRequests // 斡旋依頼リスト
     * @return `void`
     */
    //TODO手動(画面)
    public static void deleteMediationRequest(
        List<MediationRequest__c> mediationRequests) {

        try {

            if (!mediationRequests.isEmpty()) {
                delete mediationRequests;
            }

        } catch(DmlException e) {
            System.debug('--- DmlException ---');
            System.debug('--- e.getNumDml() ---> ' + e.getNumDml());
            for (Integer index = 0; index < e.getNumDml(); index++) {
                System.debug('--- index ---> ' + index);
                System.debug('--- e.getDmlId(index) ---> ' + e.getDmlId(index));
                System.debug('--- e.getDmlIndex(index) ---> ' + e.getDmlIndex(index));
                System.debug('--- e.getDmlFieldNames(index) ---> ' + e.getDmlFieldNames(index));
                System.debug('--- e.getDmlMessage(index) ---> ' + e.getDmlMessage(index));
                System.debug('--- e.getDmlType(index).name() ---> ' + e.getDmlType(index).name());
            }
            throw e;
        } catch(Exception e) {
            System.debug('--- Exception ---');
            System.debug('--- e.getTypeName() ---> ' + e.getTypeName());
            System.debug('--- e.getCause() ---> ' + e.getCause());
            System.debug('--- e.getLineNumber() ---> ' + e.getLineNumber());
            System.debug('--- e.getMessage() ---> ' + e.getMessage());

            throw e;
        }
    }

     

}