force-app/main/default/objects/Account/fields/ChatterGroupName__c.field-meta.xml
<CustomField>
    <fullName>ChatterGroupName__c</fullName>
    <label>Chatterグループ名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>通知テンプレート</label>
    <referenceTo>NotificationTemplate__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNotificationTemplate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/DefaultFeedTemplate__c/DefaultFeedTemplate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>デフォルトChatterテンプレート</label>
</CustomObject>

force-app/main/default/objects/DefaultFeedTemplate__c/fields/MediationRequestSend__c.field-meta.xml
<CustomField>
    <fullName>MediationRequestSend__c</fullName>
    <label>斡旋_斡旋依頼送付</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <label>通知テンプレート</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>テンプレート一覧コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>通知テンプレート</relationshipLabel>
    <relationshipName>AccountNotificationTemplate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/MediationRequestFeed__c.field-meta.xml
<CustomField>
    <fullName>MediationRequestFeed__c</fullName>
    <label>斡旋依頼Chatterテンプレート</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MediationRequestSendChatter.cls
public with sharing class MediationRequestSendChatter {
    public static List<MediationRequest__c> sendChatter(
        List<MediationRequest__c> mediationRequests,
        Map<Id, Account> requestTraders
        ) {
        
        System.debug('--sendChatter');

        SendChatter sendChatter = new SendChatter();

        //カスタム設定
        DefaultFeedTemplate__c defaultFeedTemplate = DefaultFeedTemplate__c.getOrgDefaults();

        //返却値の初期化
        List<MediationRequest__c> resultList = new List<MediationRequest__c>();

        //本店のグループ名を取得
        Set<String> groupNames = new Set<String>();
        Map<String,Id> requestTraderGroupNames = new Map<String,Id>();
        for(Id id: requestTraders.keySet()){
            String groupName = requestTraders.get(id).ChatterGroupName__c;
            groupNames.add(groupName);
            requestTraderGroupNames.put(groupName,id);
        }

        //本店のグループIDを取得
        Map<Id,CollaborationGroup> collaborationGroups = getCollaborationGroups(groupNames);
        
        //本店のグループIDを紐づけ
        Map<Id,Id> requestTraderCollaborationGroups = new Map<Id,Id>();
        for(Id id : collaborationGroups.keySet()){
            String collaborationGroupName = collaborationGroups.get(id).Name;
            Id requestTraderId = requestTraderGroupNames.get(collaborationGroupName);

            requestTraderCollaborationGroups.put(requestTraderId , id);
        }

        //本文テンプレートの取得
        Map<Id,String> chatterTemplate = getChatterTemlate(requestTraders.keySet());
        //デフォルトのテンプレート取得
        String DefaultChatterTemplate = defaultFeedTemplate.MediationRequestSend__c;

        // Chatterの通知
        List<ConnectApi.BatchInput> batchInputs = new List<ConnectApi.BatchInput>();
        List<MediationRequest__c> sendChatterMediationRequests = new List<MediationRequest__c>();
        for(MediationRequest__c mediationRequest: mediationRequests){
        
            Id requestTraderId = mediationRequest.RequestTraderId__c;
            sendChatter.SendChatterObject.mentionId = requestTraderCollaborationGroups.get(requestTraderId);
            if(String.isBlank(sendChatter.SendChatterObject.mentionId))sendChatter.SendChatterObject.mentionId = requestTraderId;
            // テキスト
            sendChatter.SendChatterObject.text = chatterTemplate.get(sendChatter.SendChatterObject.mentionId);
            if(String.isBlank(sendChatter.SendChatterObject.text))sendChatter.SendChatterObject.text = DefaultChatterTemplate;
        
            //投稿先
            sendChatter.SendChatterObject.feedItemInput = mediationRequest.Id;

            System.debug('-sendChatter:'+sendChatter);

            sendChatter.addObject();

        }
        
        //Chatter送信
        List<ConnectApi.BatchResult> batchResults = sendChatter.send();

        // 送信結果確認
        List<MediationRequest__c> updateMediationRequest = new List<MediationRequest__c>();
        for(Integer n=0; n < batchResults.size(); n++){
            ConnectApi.BatchResult batchResult = batchResults[n];
            MediationRequest__c mediationRequest = mediationRequests[n];
            if (batchResult.isSuccess()) {
                System.debug('sendChatter Success!!');
                System.debug('mediationRequest.Id:'+mediationRequest.Id);
                //斡旋依頼送信日時を更新するレコードを格納
                resultList.add(mediationRequest);
            } else {
                System.debug('sendChatter Error');
                System.debug('mediationRequest.Id:'+mediationRequest.Id);
                System.debug(batchResult.getErrorMessage());
            }
        }
        return resultList;
    }

     /**
     * @description グループ情報取得
     * @author sato-takumi
     * @param accountId // 取引先IDリスト
     * @return CollaborationGroup 
     */
    public static Map<Id,CollaborationGroup> getCollaborationGroups(
        Set<String> groupName 
    ) {
        Map<Id,CollaborationGroup> result = new Map<Id,CollaborationGroup>();
        for(CollaborationGroup collaborationGroup: [
            SELECT Id,Name
            FROM CollaborationGroup
            WHERE 
                Name IN : groupName
        ]){
            result.put(collaborationGroup.Id,collaborationGroup);
        }
        return result;
    }

    public static Map<Id,String> getChatterTemlate(Set<Id> AccountIds){
        Map<Id,String> result = new Map<Id,String>();
        for(NotificationTemplate__c notificationTemplate:[
            SELECT 
                Id,
                MediationRequestFeed__c
            FROM NotificationTemplate__c
            WHERE
                Account__c IN :AccountIds
        ])result.put(notificationTemplate.Id, notificationTemplate.MediationRequestFeed__c);
        return result;
    }
}