force-app/main/default/objects/Account/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>契約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋依頼</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>成約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>依頼前</fullName>
                <default>true</default>
                <label>依頼前</label>
            </value>
            <value>
                <fullName>依頼中</fullName>
            </value>
            <value>
                <fullName>成約</fullName>
            </value>
            <value>
                <fullName>他決</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TraderSelectionSetting__c/TraderSelectionSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>斡旋不動産会社自動選定</label>
</CustomObject>

force-app/main/default/objects/TraderSelectionSetting__c/fields/TaskPriority__c.field-meta.xml
<CustomField>
    <fullName>TaskPriority__c</fullName>
    <label>TODO通知_優先度</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TraderSelectionSetting__c/fields/TaskStatus__c.field-meta.xml
<CustomField>
    <fullName>TaskStatus__c</fullName>
    <label>TODO通知_ステータス</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TraderSelectionSetting__c/fields/TaskSubtype__c.field-meta.xml
<CustomField>
    <fullName>TaskSubtype__c</fullName>
    <label>TODO通知_サブ種別</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewMatterTriggerTest.cls
/**
 * @Description: Testing for class NewMatterTrigger.
 * 
 * @author hi-takada
 * @date 
 */
@isTest
private class NewMatterTriggerTest {

    /**
     * @Description テストレコード作成
     */
    @testSetup
    static void setup() {
    }

    /**
     * @Description 新規トリガ：登録処理（単一）
     */
    /*
    @isTest
    static void onInsertAfterTest_001() {        

        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        List<Account> aMCList =
            TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();
        // 申請データ生成
        List<Application__c> applicationList =
            TraderSelectionTestDataFactory.createApplication_TraderSelection();
        Test.startTest();
        // 新規データ作成（単一）
        // NewMatter__c newMatter =
        //     TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(
        //         applicationList.get(0)
        //     );
        Test.stopTest();

        // 新規
        List<NewMatter__c> newMatterCreateData =
            [SELECT Id, Name FROM NewMatter__c];
        for (NewMatter__c nMCD : newMatterCreateData) {
            System.debug(nMCD);
        }
        System.assertEquals(3, newMatterCreateData.size());

        // 斡旋依頼
        List<MediationRequest__c> mediationRequestCreateDatas =
            [SELECT Id, Name, ContractCategory__c, RequestTraderId__c FROM MediationRequest__c];
        for (MediationRequest__c mRCD : mediationRequestCreateDatas) {
            System.debug(mRCD);
        }
        System.assertEquals(16, mediationRequestCreateDatas.size());

        // Task
        List<Task> taskCreateDatas = [SELECT Id, Subject FROM Task];
        for (Task tCD : taskCreateDatas) {
            System.debug(tCD);
        }
        // System.assert(mediationRequestCreateDatas.size() <=
        //      taskCreateDatas.size());
    }
*/

    /**
     * @Description 新規トリガ：登録処理（複数）
     */
    /*
    @isTest
    static void onInsertAfterTest_002() {

        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        List<Account> aMCList =
            TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();
        // 申請データ生成
        List<Application__c> applicationList =
            TraderSelectionTestDataFactory.createApplication_TraderSelection();
        
        Test.startTest();
        // 新規データ作成（複数）
        // List<NewMatter__c> newMatter =
        //     TraderSelectionTestDataFactory.createNewMatter_TraderSelection(
        //         applicationList
        //     );
        Test.stopTest();

        // 新規
        List<NewMatter__c> newMatterCreateDatas =
            [SELECT Id, Name FROM NewMatter__c];
        for (NewMatter__c nMCD : newMatterCreateDatas) {
            System.debug(nMCD);
        }
        System.assertEquals(3, newMatterCreateDatas.size());

        // 斡旋依頼
        List<MediationRequest__c> mediationRequestCreateDatas =
            [SELECT Id, Name, ContractCategory__c, RequestTraderId__c 
            FROM MediationRequest__c];
        for (MediationRequest__c mRCD : mediationRequestCreateDatas) {
            System.debug(mRCD);
        }
        System.assertEquals(16, mediationRequestCreateDatas.size());

    }
*/

    /**
     * @Description 新規トリガ：登録処理（大量データ）
     */
    /*
    @isTest
    
    static void onInsertAfterTest_003() {        

        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        Application__c application =
            TraderSelectionTestDataFactory.createAccount_Mass_TraderSelection(
                5, 'メール');
        Test.startTest();
        // 新規データ作成（単一）
        // NewMatter__c newMatter =
        //     TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(
        //         application
        //     );
        Test.stopTest();

        // 斡旋依頼
        List<MediationRequest__c> mediationRequestCreateDatas =
            [SELECT Id, Name, ContractCategory__c, RequestTraderId__c 
            FROM MediationRequest__c];

        System.assertEquals(5, mediationRequestCreateDatas.size());

    }
*/
    /**
     * @Description 新規トリガ：登録処理（大量データ）
     */
    /*
    @isTest
    static void onInsertAfterTest_004() {  

        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        Application__c application =
            TraderSelectionTestDataFactory.createAccount_Mass_TraderSelection(
                190, 'Chatter');
        Test.startTest();

        // ※テスト内でチャターにアクセスするConnectApiを使用するとエラーが発生する

        // 新規データ作成（単一）
        // NewMatter__c newMatter =
        //     TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(
        //         application
        //     );
        Test.stopTest();

        // 斡旋依頼
        List<MediationRequest__c> mediationRequestCreateDatas =
            [SELECT Id, Name, ContractCategory__c, RequestTraderId__c 
            FROM MediationRequest__c];

        System.assertEquals(190, mediationRequestCreateDatas.size());

    }
    */
    /**
     * @Description 新規トリガ：異常
     */
    /*
    @isTest
    static void onInsertAfterTest_005_E() {        

        // カスタム設定を作成
        TraderSelectionSetting__c traderSelectionSetting = 
            TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // エラー発生のため修正
        traderSelectionSetting.TaskSubtype__c = 'XXXXXXXXXXXXXXXXXXXX';
        traderSelectionSetting.TaskStatus__c = 'XXXXXXXXXXXXXXXXXXXX';
        traderSelectionSetting.TaskPriority__c = 'XXXXXXXXXXXXXXXXXXXX';
        update traderSelectionSetting;

        // 取引先（不動産会社）データ生成
        List<Account> aMCList =
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();
        Test.startTest();
        try {
        // 申請データ生成
        List<Application__c> applicationList =
            TraderSelectionTestDataFactory.createApplication_TraderSelection();

        // Test.startTest();
        // try {

            // 新規データ作成（単一）
            // NewMatter__c newMatter =
            //     TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(
            //     applicationList.get(0)
            // );

        } catch (Exception e) {
            System.assert(false);
            return;
        }
        System.assert(true);
        Test.stopTest();
    }

*/
}