force-app/main/default/objects/Account/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>契約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RequestingNum__c.field-meta.xml
<CustomField>
    <fullName>RequestingNum__c</fullName>
    <label>依頼中件数計算</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/AgencyCapacity__c/AgencyCapacity__c.object-meta.xml
<CustomObject>
    <label>不動産キャパ</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>不動産キャパNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AgencyCapacity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>不動産キャパ</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgencyCapacity__c/fields/RequestingNum__c.field-meta.xml
<CustomField>
    <fullName>RequestingNum__c</fullName>
    <label>依頼中件数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>申請</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>申請No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>申請</relationshipLabel>
    <relationshipName>RequestAccountRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>斡旋依頼</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Delete.recordType-meta.xml
<RecordType>
    <fullName>Delete</fullName>
    <active>true</active>
    <label>削除申請</label>
</RecordType>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/ContractCategory__c.field-meta.xml
<CustomField>
    <fullName>ContractCategory__c</fullName>
    <label>成約区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>依頼前</fullName>
                <default>true</default>
                <label>依頼前</label>
            </value>
            <value>
                <fullName>依頼中</fullName>
            </value>
            <value>
                <fullName>成約</fullName>
            </value>
            <value>
                <fullName>他決</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約手続き</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>斡旋依頼 (新規No)</relationshipLabel>
    <relationshipName>MediationRequestIdNewMatterRelation10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/NewMatter__c.object-meta.xml
<CustomObject>
    <label>新規</label>
    <nameField>
        <displayFormat>NM-{000000000}</displayFormat>
        <label>契約手続き</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NewMatter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>企業名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>新規 (委託企業)</relationshipLabel>
    <relationshipName>Account_NewMatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申請</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>NewMatterApplicationRelation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NewMatter__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <label>新規ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MediationRequestTriggerTest.cls
/**
 * @Description: Testing for class MediationRequestTrigger.
 * 
 * @author hi-takada
 * @date 2022/01/27
 */
@isTest
private class MediationRequestTriggerTest {


    /**
     * @Description 斡旋依頼トリガ：斡旋依頼登録処理
     */
    /*
    @isTest
    static void onInsertAfterTest_001() {

        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        List<Account> aMCList =
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();
        // 申請データ生成
        List<Application__c> applicationList =
            TraderSelectionTestDataFactory.createApplication_TraderSelection();
        // 新規データ作成（単一）
        // NewMatter__c newMatter =
        // TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(
        //     applicationList.get(0)
        // );

        Test.startTest();
        // 斡旋依頼
        MediationRequest__c mediationRequest =
            [SELECT Id,NewMatterId__c,RequestTraderId__c, ContractCategory__c 
                FROM MediationRequest__c LIMIT 1];
        // 取引先IDを斡旋依頼から取得
        Id accountId = mediationRequest.RequestTraderId__c;

        // 不動産キャパ
        AgencyCapacity__c agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 登録前斡旋依頼数
        Integer requestingNum = 
            Integer.valueOf(agencyCapacity.RequestingNum__c);


        // 登録斡旋依頼
        List<MediationRequest__c>  insertMediationRequests = new List<MediationRequest__c>();

        MediationRequest__c insertmediationRequest_1 = new MediationRequest__c(
            Name = 'Test_1',
            NewMatterId__c = mediationRequest.NewMatterId__c,
            RequestTraderId__c = accountId,
            ContractCategory__c = '依頼中'
        );
        insertMediationRequests.add(insertmediationRequest_1);
        MediationRequest__c insertmediationRequest_2 = new MediationRequest__c(
            Name = 'Test_2',
            NewMatterId__c = mediationRequest.NewMatterId__c,
            RequestTraderId__c = accountId,
            ContractCategory__c = '依頼中'
        );
        insertMediationRequests.add(insertmediationRequest_2);
        MediationRequest__c insertmediationRequest_3 = new MediationRequest__c(
            Name = 'Test_3',
            NewMatterId__c = mediationRequest.NewMatterId__c,
            RequestTraderId__c = accountId,
            ContractCategory__c = 'キャンセル'
        );
        insertMediationRequests.add(insertmediationRequest_3);
        MediationRequest__c insertmediationRequest_4 = new MediationRequest__c(
            Name = 'Test_4',
            NewMatterId__c = mediationRequest.NewMatterId__c,
            RequestTraderId__c = accountId,
            ContractCategory__c = null
        );
        insertMediationRequests.add(insertmediationRequest_4);

        // 斡旋依頼を削除
        insert insertMediationRequests;

        // 不動産キャパ再取得
        agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 斡旋依頼数が異なることを確認
        System.assertNotEquals(requestingNum, 
            Integer.valueOf(agencyCapacity.RequestingNum__c));
        Test.stopTest();
    }
*/

    /**
     * @Description 斡旋依頼トリガ：斡旋依頼変更処理
     */
    /*
    @isTest
    static void onUpdateAfterTest_001() {

        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        List<Account> aMCList =
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();
        // 申請データ生成
        List<Application__c> applicationList =
            TraderSelectionTestDataFactory.createApplication_TraderSelection();
        // 新規データ作成（単一）
        // NewMatter__c newMatter =
        // TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(
        //     applicationList.get(0)
        // );

        Test.startTest();
        // 斡旋依頼
        MediationRequest__c mediationRequest =
            [SELECT Id, RequestTraderId__c, ContractCategory__c 
                FROM MediationRequest__c LIMIT 1];
        // 取引先IDを斡旋依頼から取得
        Id accountId = mediationRequest.RequestTraderId__c;

        // 不動産キャパ
        AgencyCapacity__c agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 削除前斡旋依頼数
        Integer requestingNum = 
            Integer.valueOf(agencyCapacity.RequestingNum__c);

        // 斡旋依頼を更新
        mediationRequest.ContractCategory__c = 'キャンセル';
        update mediationRequest;

        // 不動産キャパ再取得
        agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 斡旋依頼数が異なることを確認
        System.assertNotEquals(requestingNum, 
            Integer.valueOf(agencyCapacity.RequestingNum__c));
        Test.stopTest();

    }
*/
    /**
     * @Description 斡旋依頼トリガ：斡旋依頼削除処理 
     */
    /*
    @isTest
    static void onDeleteAfterTest_001() {
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        List<Account> aMCList =
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();
        // 申請データ生成
        List<Application__c> applicationList =
            TraderSelectionTestDataFactory.createApplication_TraderSelection();
        // 新規データ作成（単一）
        // NewMatter__c newMatter =
        //     TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(
        //         applicationList.get(0)
        //     );

        Test.startTest();

        // 斡旋依頼
        MediationRequest__c mediationRequest =
            [SELECT Id, RequestTraderId__c, ContractCategory__c 
                FROM MediationRequest__c LIMIT 1];
        // 取引先IDを斡旋依頼から取得
        Id accountId = mediationRequest.RequestTraderId__c;
        
        // 不動産キャパ
        AgencyCapacity__c agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 削除前斡旋依頼数
        Integer requestingNum = 
            Integer.valueOf(agencyCapacity.RequestingNum__c);

        // 斡旋依頼を削除
        delete mediationRequest;

        // 不動産キャパ再取得
        agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 斡旋依頼数が異なることを確認
        System.assertNotEquals(requestingNum, 
            Integer.valueOf(agencyCapacity.RequestingNum__c));
        Test.stopTest();
    }
*/

    /**
     * @Description 斡旋依頼トリガ：斡旋依頼削除処理 （複数）
     */
    /*
    @isTest
    static void onDeleteAfterTest_002() {

        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        // 取引先（不動産会社）データ生成
        List<Account> aMCList =
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();
        // 申請データ生成
        List<Application__c> applicationList =
            TraderSelectionTestDataFactory.createApplication_TraderSelection();
        // 新規データ作成（複数）
        // List<NewMatter__c> newMatter =
        // TraderSelectionTestDataFactory.createNewMatter_TraderSelection(
        //     applicationList
        // );

        Test.startTest();
        // 斡旋依頼
        list<MediationRequest__c> mediationRequests =
            [SELECT Id, RequestTraderId__c, ContractCategory__c 
                FROM MediationRequest__c ];
        // 取引先IDを斡旋依頼から取得
        Id accountId = mediationRequests.get(0).RequestTraderId__c;

        // 不動産キャパ
        AgencyCapacity__c agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 削除前斡旋依頼数
        Integer requestingNum = 
            Integer.valueOf(agencyCapacity.RequestingNum__c);

        // 斡旋依頼を削除
        delete mediationRequests;

        // 不動産キャパ再取得
        agencyCapacity =
            [SELECT Id, RequestingNum__c 
            FROM AgencyCapacity__c WHERE Account__c = :accountId];

        // 斡旋依頼数が異なることを確認
        System.assertNotEquals(requestingNum, 
            Integer.valueOf(agencyCapacity.RequestingNum__c));
        Test.stopTest();

    }
*/
}