force-app/main/default/objects/Account/fields/NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>通知テンプレート</label>
    <referenceTo>NotificationTemplate__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNotificationTemplate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>委託企業</label>
</RecordType>

force-app/main/default/objects/DefaultReportNum__c/DefaultReportNum__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>デフォルト帳票番号</label>
</CustomObject>

force-app/main/default/objects/DefaultReportNum__c/fields/MediationRequest__c.field-meta.xml
<CustomField>
    <fullName>MediationRequest__c</fullName>
    <label>斡旋依頼</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <label>通知テンプレート</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>テンプレート一覧コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/MediationRequestReportNum__c.field-meta.xml
<CustomField>
    <fullName>MediationRequestReportNum__c</fullName>
    <label>斡旋依頼帳票番号</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MediationRequestSendFax.cls
public with sharing class MediationRequestSendFax {
    public static List<MediationRequest__c> SendFax(
        List<MediationRequest__c> mediationRequests,
        Map<Id, Account> requestTraders
    ){
        System.debug('--SendFax--');
        //カスタム設定
        DefaultReportNum__c tsSetting = DefaultReportNum__c.getOrgDefaults();

        //固定値：出力種別
        String VAR_TYPE = '0'; 

        List<MediationRequest__c> resultList = new List<MediationRequest__c>();
        for(MediationRequest__c mediationRequest:mediationRequests){
            //通知テンプレートの斡旋依頼帳票番号を取得
            Integer mediationRequestReportNum = Integer.valueOf(mediationRequest.RequestTraderId__r.NotificationTemplate__r.MediationRequestReportNum__c);
            //カスタム値なない場合デフォルト値を使用
            if(mediationRequestReportNum == null){
                mediationRequestReportNum = Integer.valueOf(tsSetting.MediationRequest__c);
            }

            //パラメータを設定
            Id mediationRequestId = mediationRequest.Id; //斡旋依頼レコードID
            String destination = String.valueOf(
                requestTraders.get(mediationRequest.RequestTraderId__c)); //本店の取引先を取得

            Map<String,Integer> result = ReportOutput.StartUpReportOutPut(
                mediationRequestReportNum,
                mediationRequestId,
                destination,
                VAR_TYPE
            );
            Integer resultCode = result.get('resultCode');
            Integer resultErrorCode = result.get('resultErrorCode');

            
            if(resultCode == 0){
                //送信成功処理
                System.debug('-SendFaxSucces');
                resultList.add(mediationRequest);
                }
            else if(resultCode == 1){
                //接続失敗処理
                System.debug('AccesError:'+resultErrorCode);
            }else if(resultCode == 9){
                //処理失敗処理
                System.debug('SystemError:'+resultErrorCode);
            }else {
                    
            }
        }
        return resultList;

    }
}