force-app/main/default/objects/MediationRequest__c/MediationRequest__c.object-meta.xml
<CustomObject>
    <label>斡旋依頼</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>斡旋依頼NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MediationRequest__c/fields/NewMatterId__c.field-meta.xml
<CustomField>
    <fullName>NewMatterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約手続き</label>
    <referenceTo>NewMatter__c</referenceTo>
    <relationshipLabel>斡旋依頼 (新規No)</relationshipLabel>
    <relationshipName>MediationRequestIdNewMatterRelation10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MediationRequest__c/fields/RequestTraderId__c.field-meta.xml
<CustomField>
    <fullName>RequestTraderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>依頼業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>斡旋依頼 (依頼業者)</relationshipLabel>
    <relationshipName>MediationRequestIdAccountRelation3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutoTraderSelectionModelErrorTest.cls
@isTest
public with sharing class AutoTraderSelectionModelErrorTest {
    /*
    @isTest
    public static void errorTest1(){
        test.startTest();
        List<MediationRequest__c> mediationRequests = new List<MediationRequest__c>();
        MediationRequest__c mediationRequest = new MediationRequest__c(
            RequestTraderId__c = 'test000000BYu7xMAD',
            NewMatterId__c = 'test000000BYu7xMAD'
        );
        mediationRequests.add(mediationRequest);
        AutoTraderSelectionModel.insertMediationRequest(mediationRequests);
        test.stopTest();
    }
    @isTest
    public static void errorTest2(){
        test.startTest();
        List<Task> tasks = new List<Task>();
        Task task = new Task(
            whatId = 'test000000BYu7xMAD'        );
        tasks.add(task);
        AutoTraderSelectionModel.insertTask(tasks);
        test.stopTest();
    }
    */
}