force-app/main/default/objects/RealEstate__c/RealEstate__c.object-meta.xml
<CustomObject>
    <label>物件</label>
    <nameField>
        <label>物件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/SyatakusanSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>しゃたくさん設定</label>
</CustomObject>

force-app/main/default/objects/SyatakusanSetting__c/fields/RecreatePaymentNotificationBody__c.field-meta.xml
<CustomField>
    <fullName>RecreatePaymentNotificationBody__c</fullName>
    <label>支払再作成完了通知本文</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyatakusanSetting__c/fields/RecreatePaymentNotificationTitle__c.field-meta.xml
<CustomField>
    <fullName>RecreatePaymentNotificationTitle__c</fullName>
    <label>支払再作成完了通知タイトル</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecreatePaymentCustomNotification.cls
/**
 * @description        : 支払再作成カスタム通知
 * @author             : h-nakata
**/
public class RecreatePaymentCustomNotification {
    /**
    * @description カスタム通知送信
    * @author h-nakata
    * @param Set<String> recipientsIds 通知受信ユーザID
    * @return void
    **/
    public static void notifyUsers(Set<String> recipientsIds) {
        //カスタム通知種別取得
        CustomNotificationType notificationType = 
            [SELECT Id
             FROM CustomNotificationType 
             WHERE DeveloperName = 'RecreatePaymentCompleted'];
        
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        //しゃたくさん設定取得
        SyatakusanSetting__c syatakusanSetting = SyatakusanSetting__c.getOrgDefaults();
        //通知タイトル
        notification.setTitle(syatakusanSetting.RecreatePaymentNotificationTitle__c);
        //通知本文
        notification.setBody(syatakusanSetting.RecreatePaymentNotificationBody__c);
        //カスタム通知種別
        notification.setNotificationTypeId(notificationType.Id);
        //遷移先を物件リストビューに設定
        String pageRef = '{"type":"standard__objectPage", "attributes":{"objectApiName":"RealEstate__c", "actionName":"list"}, "state":{"filterName":"Recent"}}';
        notification.setTargetPageRef(pageRef);
        
        //カスタム通知送信
        try {
            notification.send(recipientsIds);
        } catch (Exception e) {
            System.debug('Problem sending notification: ' + e.getMessage());
        }
    }
}